/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CreateScheduleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateScheduleRequest{}

// CreateScheduleRequest struct for CreateScheduleRequest
type CreateScheduleRequest struct {
	AlertOnFailure *bool `json:"alertOnFailure,omitempty"`
	AutoPauseAfterFailures NullableInt32 `json:"autoPauseAfterFailures,omitempty"`
	Destinations []DeliveryDestination `json:"destinations,omitempty"`
	DiffThreshold NullableFloat64 `json:"diffThreshold,omitempty"`
	EndsAt NullableTime `json:"endsAt,omitempty"`
	Name string `json:"name"`
	OnlyOnChange *bool `json:"onlyOnChange,omitempty"`
	Options NullableScheduleScreenshotOptions `json:"options,omitempty"`
	RetentionDays *int32 `json:"retentionDays,omitempty"`
	Schedule string `json:"schedule"`
	StartsAt NullableTime `json:"startsAt,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
	Url string `json:"url"`
	WebhookSecret NullableString `json:"webhookSecret,omitempty"`
	WebhookUrl NullableString `json:"webhookUrl,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateScheduleRequest CreateScheduleRequest

// NewCreateScheduleRequest instantiates a new CreateScheduleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateScheduleRequest(name string, schedule string, url string) *CreateScheduleRequest {
	this := CreateScheduleRequest{}
	var alertOnFailure bool = false
	this.AlertOnFailure = &alertOnFailure
	this.Name = name
	var onlyOnChange bool = false
	this.OnlyOnChange = &onlyOnChange
	var retentionDays int32 = 30
	this.RetentionDays = &retentionDays
	this.Schedule = schedule
	var timezone string = "UTC"
	this.Timezone = &timezone
	this.Url = url
	return &this
}

// NewCreateScheduleRequestWithDefaults instantiates a new CreateScheduleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateScheduleRequestWithDefaults() *CreateScheduleRequest {
	this := CreateScheduleRequest{}
	var alertOnFailure bool = false
	this.AlertOnFailure = &alertOnFailure
	var onlyOnChange bool = false
	this.OnlyOnChange = &onlyOnChange
	var retentionDays int32 = 30
	this.RetentionDays = &retentionDays
	var timezone string = "UTC"
	this.Timezone = &timezone
	return &this
}

// GetAlertOnFailure returns the AlertOnFailure field value if set, zero value otherwise.
func (o *CreateScheduleRequest) GetAlertOnFailure() bool {
	if o == nil || IsNil(o.AlertOnFailure) {
		var ret bool
		return ret
	}
	return *o.AlertOnFailure
}

// GetAlertOnFailureOk returns a tuple with the AlertOnFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateScheduleRequest) GetAlertOnFailureOk() (*bool, bool) {
	if o == nil || IsNil(o.AlertOnFailure) {
		return nil, false
	}
	return o.AlertOnFailure, true
}

// HasAlertOnFailure returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasAlertOnFailure() bool {
	if o != nil && !IsNil(o.AlertOnFailure) {
		return true
	}

	return false
}

// SetAlertOnFailure gets a reference to the given bool and assigns it to the AlertOnFailure field.
func (o *CreateScheduleRequest) SetAlertOnFailure(v bool) {
	o.AlertOnFailure = &v
}

// GetAutoPauseAfterFailures returns the AutoPauseAfterFailures field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetAutoPauseAfterFailures() int32 {
	if o == nil || IsNil(o.AutoPauseAfterFailures.Get()) {
		var ret int32
		return ret
	}
	return *o.AutoPauseAfterFailures.Get()
}

// GetAutoPauseAfterFailuresOk returns a tuple with the AutoPauseAfterFailures field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetAutoPauseAfterFailuresOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AutoPauseAfterFailures.Get(), o.AutoPauseAfterFailures.IsSet()
}

// HasAutoPauseAfterFailures returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasAutoPauseAfterFailures() bool {
	if o != nil && o.AutoPauseAfterFailures.IsSet() {
		return true
	}

	return false
}

// SetAutoPauseAfterFailures gets a reference to the given NullableInt32 and assigns it to the AutoPauseAfterFailures field.
func (o *CreateScheduleRequest) SetAutoPauseAfterFailures(v int32) {
	o.AutoPauseAfterFailures.Set(&v)
}
// SetAutoPauseAfterFailuresNil sets the value for AutoPauseAfterFailures to be an explicit nil
func (o *CreateScheduleRequest) SetAutoPauseAfterFailuresNil() {
	o.AutoPauseAfterFailures.Set(nil)
}

// UnsetAutoPauseAfterFailures ensures that no value is present for AutoPauseAfterFailures, not even an explicit nil
func (o *CreateScheduleRequest) UnsetAutoPauseAfterFailures() {
	o.AutoPauseAfterFailures.Unset()
}

// GetDestinations returns the Destinations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetDestinations() []DeliveryDestination {
	if o == nil {
		var ret []DeliveryDestination
		return ret
	}
	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetDestinationsOk() ([]DeliveryDestination, bool) {
	if o == nil || IsNil(o.Destinations) {
		return nil, false
	}
	return o.Destinations, true
}

// HasDestinations returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasDestinations() bool {
	if o != nil && !IsNil(o.Destinations) {
		return true
	}

	return false
}

// SetDestinations gets a reference to the given []DeliveryDestination and assigns it to the Destinations field.
func (o *CreateScheduleRequest) SetDestinations(v []DeliveryDestination) {
	o.Destinations = v
}

// GetDiffThreshold returns the DiffThreshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetDiffThreshold() float64 {
	if o == nil || IsNil(o.DiffThreshold.Get()) {
		var ret float64
		return ret
	}
	return *o.DiffThreshold.Get()
}

// GetDiffThresholdOk returns a tuple with the DiffThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetDiffThresholdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiffThreshold.Get(), o.DiffThreshold.IsSet()
}

// HasDiffThreshold returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasDiffThreshold() bool {
	if o != nil && o.DiffThreshold.IsSet() {
		return true
	}

	return false
}

// SetDiffThreshold gets a reference to the given NullableFloat64 and assigns it to the DiffThreshold field.
func (o *CreateScheduleRequest) SetDiffThreshold(v float64) {
	o.DiffThreshold.Set(&v)
}
// SetDiffThresholdNil sets the value for DiffThreshold to be an explicit nil
func (o *CreateScheduleRequest) SetDiffThresholdNil() {
	o.DiffThreshold.Set(nil)
}

// UnsetDiffThreshold ensures that no value is present for DiffThreshold, not even an explicit nil
func (o *CreateScheduleRequest) UnsetDiffThreshold() {
	o.DiffThreshold.Unset()
}

// GetEndsAt returns the EndsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetEndsAt() time.Time {
	if o == nil || IsNil(o.EndsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndsAt.Get()
}

// GetEndsAtOk returns a tuple with the EndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetEndsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndsAt.Get(), o.EndsAt.IsSet()
}

// HasEndsAt returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasEndsAt() bool {
	if o != nil && o.EndsAt.IsSet() {
		return true
	}

	return false
}

// SetEndsAt gets a reference to the given NullableTime and assigns it to the EndsAt field.
func (o *CreateScheduleRequest) SetEndsAt(v time.Time) {
	o.EndsAt.Set(&v)
}
// SetEndsAtNil sets the value for EndsAt to be an explicit nil
func (o *CreateScheduleRequest) SetEndsAtNil() {
	o.EndsAt.Set(nil)
}

// UnsetEndsAt ensures that no value is present for EndsAt, not even an explicit nil
func (o *CreateScheduleRequest) UnsetEndsAt() {
	o.EndsAt.Unset()
}

// GetName returns the Name field value
func (o *CreateScheduleRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateScheduleRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateScheduleRequest) SetName(v string) {
	o.Name = v
}

// GetOnlyOnChange returns the OnlyOnChange field value if set, zero value otherwise.
func (o *CreateScheduleRequest) GetOnlyOnChange() bool {
	if o == nil || IsNil(o.OnlyOnChange) {
		var ret bool
		return ret
	}
	return *o.OnlyOnChange
}

// GetOnlyOnChangeOk returns a tuple with the OnlyOnChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateScheduleRequest) GetOnlyOnChangeOk() (*bool, bool) {
	if o == nil || IsNil(o.OnlyOnChange) {
		return nil, false
	}
	return o.OnlyOnChange, true
}

// HasOnlyOnChange returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasOnlyOnChange() bool {
	if o != nil && !IsNil(o.OnlyOnChange) {
		return true
	}

	return false
}

// SetOnlyOnChange gets a reference to the given bool and assigns it to the OnlyOnChange field.
func (o *CreateScheduleRequest) SetOnlyOnChange(v bool) {
	o.OnlyOnChange = &v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetOptions() ScheduleScreenshotOptions {
	if o == nil || IsNil(o.Options.Get()) {
		var ret ScheduleScreenshotOptions
		return ret
	}
	return *o.Options.Get()
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetOptionsOk() (*ScheduleScreenshotOptions, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options.Get(), o.Options.IsSet()
}

// HasOptions returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasOptions() bool {
	if o != nil && o.Options.IsSet() {
		return true
	}

	return false
}

// SetOptions gets a reference to the given NullableScheduleScreenshotOptions and assigns it to the Options field.
func (o *CreateScheduleRequest) SetOptions(v ScheduleScreenshotOptions) {
	o.Options.Set(&v)
}
// SetOptionsNil sets the value for Options to be an explicit nil
func (o *CreateScheduleRequest) SetOptionsNil() {
	o.Options.Set(nil)
}

// UnsetOptions ensures that no value is present for Options, not even an explicit nil
func (o *CreateScheduleRequest) UnsetOptions() {
	o.Options.Unset()
}

// GetRetentionDays returns the RetentionDays field value if set, zero value otherwise.
func (o *CreateScheduleRequest) GetRetentionDays() int32 {
	if o == nil || IsNil(o.RetentionDays) {
		var ret int32
		return ret
	}
	return *o.RetentionDays
}

// GetRetentionDaysOk returns a tuple with the RetentionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateScheduleRequest) GetRetentionDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.RetentionDays) {
		return nil, false
	}
	return o.RetentionDays, true
}

// HasRetentionDays returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasRetentionDays() bool {
	if o != nil && !IsNil(o.RetentionDays) {
		return true
	}

	return false
}

// SetRetentionDays gets a reference to the given int32 and assigns it to the RetentionDays field.
func (o *CreateScheduleRequest) SetRetentionDays(v int32) {
	o.RetentionDays = &v
}

// GetSchedule returns the Schedule field value
func (o *CreateScheduleRequest) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *CreateScheduleRequest) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *CreateScheduleRequest) SetSchedule(v string) {
	o.Schedule = v
}

// GetStartsAt returns the StartsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetStartsAt() time.Time {
	if o == nil || IsNil(o.StartsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartsAt.Get()
}

// GetStartsAtOk returns a tuple with the StartsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetStartsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartsAt.Get(), o.StartsAt.IsSet()
}

// HasStartsAt returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasStartsAt() bool {
	if o != nil && o.StartsAt.IsSet() {
		return true
	}

	return false
}

// SetStartsAt gets a reference to the given NullableTime and assigns it to the StartsAt field.
func (o *CreateScheduleRequest) SetStartsAt(v time.Time) {
	o.StartsAt.Set(&v)
}
// SetStartsAtNil sets the value for StartsAt to be an explicit nil
func (o *CreateScheduleRequest) SetStartsAtNil() {
	o.StartsAt.Set(nil)
}

// UnsetStartsAt ensures that no value is present for StartsAt, not even an explicit nil
func (o *CreateScheduleRequest) UnsetStartsAt() {
	o.StartsAt.Unset()
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *CreateScheduleRequest) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateScheduleRequest) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *CreateScheduleRequest) SetTimezone(v string) {
	o.Timezone = &v
}

// GetUrl returns the Url field value
func (o *CreateScheduleRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateScheduleRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateScheduleRequest) SetUrl(v string) {
	o.Url = v
}

// GetWebhookSecret returns the WebhookSecret field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetWebhookSecret() string {
	if o == nil || IsNil(o.WebhookSecret.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookSecret.Get()
}

// GetWebhookSecretOk returns a tuple with the WebhookSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetWebhookSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookSecret.Get(), o.WebhookSecret.IsSet()
}

// HasWebhookSecret returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasWebhookSecret() bool {
	if o != nil && o.WebhookSecret.IsSet() {
		return true
	}

	return false
}

// SetWebhookSecret gets a reference to the given NullableString and assigns it to the WebhookSecret field.
func (o *CreateScheduleRequest) SetWebhookSecret(v string) {
	o.WebhookSecret.Set(&v)
}
// SetWebhookSecretNil sets the value for WebhookSecret to be an explicit nil
func (o *CreateScheduleRequest) SetWebhookSecretNil() {
	o.WebhookSecret.Set(nil)
}

// UnsetWebhookSecret ensures that no value is present for WebhookSecret, not even an explicit nil
func (o *CreateScheduleRequest) UnsetWebhookSecret() {
	o.WebhookSecret.Unset()
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScheduleRequest) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookUrl.Get()
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScheduleRequest) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookUrl.Get(), o.WebhookUrl.IsSet()
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *CreateScheduleRequest) HasWebhookUrl() bool {
	if o != nil && o.WebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given NullableString and assigns it to the WebhookUrl field.
func (o *CreateScheduleRequest) SetWebhookUrl(v string) {
	o.WebhookUrl.Set(&v)
}
// SetWebhookUrlNil sets the value for WebhookUrl to be an explicit nil
func (o *CreateScheduleRequest) SetWebhookUrlNil() {
	o.WebhookUrl.Set(nil)
}

// UnsetWebhookUrl ensures that no value is present for WebhookUrl, not even an explicit nil
func (o *CreateScheduleRequest) UnsetWebhookUrl() {
	o.WebhookUrl.Unset()
}

func (o CreateScheduleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateScheduleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlertOnFailure) {
		toSerialize["alertOnFailure"] = o.AlertOnFailure
	}
	if o.AutoPauseAfterFailures.IsSet() {
		toSerialize["autoPauseAfterFailures"] = o.AutoPauseAfterFailures.Get()
	}
	if o.Destinations != nil {
		toSerialize["destinations"] = o.Destinations
	}
	if o.DiffThreshold.IsSet() {
		toSerialize["diffThreshold"] = o.DiffThreshold.Get()
	}
	if o.EndsAt.IsSet() {
		toSerialize["endsAt"] = o.EndsAt.Get()
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.OnlyOnChange) {
		toSerialize["onlyOnChange"] = o.OnlyOnChange
	}
	if o.Options.IsSet() {
		toSerialize["options"] = o.Options.Get()
	}
	if !IsNil(o.RetentionDays) {
		toSerialize["retentionDays"] = o.RetentionDays
	}
	toSerialize["schedule"] = o.Schedule
	if o.StartsAt.IsSet() {
		toSerialize["startsAt"] = o.StartsAt.Get()
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	toSerialize["url"] = o.Url
	if o.WebhookSecret.IsSet() {
		toSerialize["webhookSecret"] = o.WebhookSecret.Get()
	}
	if o.WebhookUrl.IsSet() {
		toSerialize["webhookUrl"] = o.WebhookUrl.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateScheduleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"schedule",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateScheduleRequest := _CreateScheduleRequest{}

	err = json.Unmarshal(data, &varCreateScheduleRequest)

	if err != nil {
		return err
	}

	*o = CreateScheduleRequest(varCreateScheduleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "alertOnFailure")
		delete(additionalProperties, "autoPauseAfterFailures")
		delete(additionalProperties, "destinations")
		delete(additionalProperties, "diffThreshold")
		delete(additionalProperties, "endsAt")
		delete(additionalProperties, "name")
		delete(additionalProperties, "onlyOnChange")
		delete(additionalProperties, "options")
		delete(additionalProperties, "retentionDays")
		delete(additionalProperties, "schedule")
		delete(additionalProperties, "startsAt")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "url")
		delete(additionalProperties, "webhookSecret")
		delete(additionalProperties, "webhookUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateScheduleRequest struct {
	value *CreateScheduleRequest
	isSet bool
}

func (v NullableCreateScheduleRequest) Get() *CreateScheduleRequest {
	return v.value
}

func (v *NullableCreateScheduleRequest) Set(val *CreateScheduleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateScheduleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateScheduleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateScheduleRequest(val *CreateScheduleRequest) *NullableCreateScheduleRequest {
	return &NullableCreateScheduleRequest{value: val, isSet: true}
}

func (v NullableCreateScheduleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateScheduleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


