/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// PageAction - struct for PageAction
type PageAction struct {
	ClickAction *ClickAction
	HoverAction *HoverAction
	PressAction *PressAction
	ScrollAction *ScrollAction
	SelectAction *SelectAction
	TypeAction *TypeAction
	WaitAction *WaitAction
}

// ClickActionAsPageAction is a convenience function that returns ClickAction wrapped in PageAction
func ClickActionAsPageAction(v *ClickAction) PageAction {
	return PageAction{
		ClickAction: v,
	}
}

// HoverActionAsPageAction is a convenience function that returns HoverAction wrapped in PageAction
func HoverActionAsPageAction(v *HoverAction) PageAction {
	return PageAction{
		HoverAction: v,
	}
}

// PressActionAsPageAction is a convenience function that returns PressAction wrapped in PageAction
func PressActionAsPageAction(v *PressAction) PageAction {
	return PageAction{
		PressAction: v,
	}
}

// ScrollActionAsPageAction is a convenience function that returns ScrollAction wrapped in PageAction
func ScrollActionAsPageAction(v *ScrollAction) PageAction {
	return PageAction{
		ScrollAction: v,
	}
}

// SelectActionAsPageAction is a convenience function that returns SelectAction wrapped in PageAction
func SelectActionAsPageAction(v *SelectAction) PageAction {
	return PageAction{
		SelectAction: v,
	}
}

// TypeActionAsPageAction is a convenience function that returns TypeAction wrapped in PageAction
func TypeActionAsPageAction(v *TypeAction) PageAction {
	return PageAction{
		TypeAction: v,
	}
}

// WaitActionAsPageAction is a convenience function that returns WaitAction wrapped in PageAction
func WaitActionAsPageAction(v *WaitAction) PageAction {
	return PageAction{
		WaitAction: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PageAction) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'click'
	if jsonDict["type"] == "click" {
		// try to unmarshal JSON data into ClickAction
		err = json.Unmarshal(data, &dst.ClickAction)
		if err == nil {
			return nil // data stored in dst.ClickAction, return on the first match
		} else {
			dst.ClickAction = nil
			return fmt.Errorf("failed to unmarshal PageAction as ClickAction: %s", err.Error())
		}
	}

	// check if the discriminator value is 'hover'
	if jsonDict["type"] == "hover" {
		// try to unmarshal JSON data into HoverAction
		err = json.Unmarshal(data, &dst.HoverAction)
		if err == nil {
			return nil // data stored in dst.HoverAction, return on the first match
		} else {
			dst.HoverAction = nil
			return fmt.Errorf("failed to unmarshal PageAction as HoverAction: %s", err.Error())
		}
	}

	// check if the discriminator value is 'press'
	if jsonDict["type"] == "press" {
		// try to unmarshal JSON data into PressAction
		err = json.Unmarshal(data, &dst.PressAction)
		if err == nil {
			return nil // data stored in dst.PressAction, return on the first match
		} else {
			dst.PressAction = nil
			return fmt.Errorf("failed to unmarshal PageAction as PressAction: %s", err.Error())
		}
	}

	// check if the discriminator value is 'scroll'
	if jsonDict["type"] == "scroll" {
		// try to unmarshal JSON data into ScrollAction
		err = json.Unmarshal(data, &dst.ScrollAction)
		if err == nil {
			return nil // data stored in dst.ScrollAction, return on the first match
		} else {
			dst.ScrollAction = nil
			return fmt.Errorf("failed to unmarshal PageAction as ScrollAction: %s", err.Error())
		}
	}

	// check if the discriminator value is 'select'
	if jsonDict["type"] == "select" {
		// try to unmarshal JSON data into SelectAction
		err = json.Unmarshal(data, &dst.SelectAction)
		if err == nil {
			return nil // data stored in dst.SelectAction, return on the first match
		} else {
			dst.SelectAction = nil
			return fmt.Errorf("failed to unmarshal PageAction as SelectAction: %s", err.Error())
		}
	}

	// check if the discriminator value is 'type'
	if jsonDict["type"] == "type" {
		// try to unmarshal JSON data into TypeAction
		err = json.Unmarshal(data, &dst.TypeAction)
		if err == nil {
			return nil // data stored in dst.TypeAction, return on the first match
		} else {
			dst.TypeAction = nil
			return fmt.Errorf("failed to unmarshal PageAction as TypeAction: %s", err.Error())
		}
	}

	// check if the discriminator value is 'wait'
	if jsonDict["type"] == "wait" {
		// try to unmarshal JSON data into WaitAction
		err = json.Unmarshal(data, &dst.WaitAction)
		if err == nil {
			return nil // data stored in dst.WaitAction, return on the first match
		} else {
			dst.WaitAction = nil
			return fmt.Errorf("failed to unmarshal PageAction as WaitAction: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PageAction) MarshalJSON() ([]byte, error) {
	if src.ClickAction != nil {
		return json.Marshal(&src.ClickAction)
	}

	if src.HoverAction != nil {
		return json.Marshal(&src.HoverAction)
	}

	if src.PressAction != nil {
		return json.Marshal(&src.PressAction)
	}

	if src.ScrollAction != nil {
		return json.Marshal(&src.ScrollAction)
	}

	if src.SelectAction != nil {
		return json.Marshal(&src.SelectAction)
	}

	if src.TypeAction != nil {
		return json.Marshal(&src.TypeAction)
	}

	if src.WaitAction != nil {
		return json.Marshal(&src.WaitAction)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PageAction) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ClickAction != nil {
		return obj.ClickAction
	}

	if obj.HoverAction != nil {
		return obj.HoverAction
	}

	if obj.PressAction != nil {
		return obj.PressAction
	}

	if obj.ScrollAction != nil {
		return obj.ScrollAction
	}

	if obj.SelectAction != nil {
		return obj.SelectAction
	}

	if obj.TypeAction != nil {
		return obj.TypeAction
	}

	if obj.WaitAction != nil {
		return obj.WaitAction
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PageAction) GetActualInstanceValue() (interface{}) {
	if obj.ClickAction != nil {
		return *obj.ClickAction
	}

	if obj.HoverAction != nil {
		return *obj.HoverAction
	}

	if obj.PressAction != nil {
		return *obj.PressAction
	}

	if obj.ScrollAction != nil {
		return *obj.ScrollAction
	}

	if obj.SelectAction != nil {
		return *obj.SelectAction
	}

	if obj.TypeAction != nil {
		return *obj.TypeAction
	}

	if obj.WaitAction != nil {
		return *obj.WaitAction
	}

	// all schemas are nil
	return nil
}

type NullablePageAction struct {
	value *PageAction
	isSet bool
}

func (v NullablePageAction) Get() *PageAction {
	return v.value
}

func (v *NullablePageAction) Set(val *PageAction) {
	v.value = val
	v.isSet = true
}

func (v NullablePageAction) IsSet() bool {
	return v.isSet
}

func (v *NullablePageAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageAction(val *PageAction) *NullablePageAction {
	return &NullablePageAction{value: val, isSet: true}
}

func (v NullablePageAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


