/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ScreenshotJsonResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScreenshotJsonResponse{}

// ScreenshotJsonResponse struct for ScreenshotJsonResponse
type ScreenshotJsonResponse struct {
	Cached *bool `json:"cached,omitempty"`
	ContentType string `json:"contentType"`
	Data NullableString `json:"data,omitempty"`
	Encoding NullableString `json:"encoding,omitempty"`
	ExpiresAt NullableTime `json:"expiresAt,omitempty"`
	Format string `json:"format"`
	Height NullableInt32 `json:"height,omitempty"`
	RenderTimeMs int64 `json:"renderTimeMs"`
	ResultUrl NullableString `json:"resultUrl,omitempty"`
	Size int32 `json:"size"`
	StorageUrl NullableString `json:"storageUrl,omitempty"`
	Url string `json:"url"`
	Width int32 `json:"width"`
	AdditionalProperties map[string]interface{}
}

type _ScreenshotJsonResponse ScreenshotJsonResponse

// NewScreenshotJsonResponse instantiates a new ScreenshotJsonResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenshotJsonResponse(contentType string, format string, renderTimeMs int64, size int32, url string, width int32) *ScreenshotJsonResponse {
	this := ScreenshotJsonResponse{}
	var cached bool = false
	this.Cached = &cached
	this.ContentType = contentType
	this.Format = format
	this.RenderTimeMs = renderTimeMs
	this.Size = size
	this.Url = url
	this.Width = width
	return &this
}

// NewScreenshotJsonResponseWithDefaults instantiates a new ScreenshotJsonResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenshotJsonResponseWithDefaults() *ScreenshotJsonResponse {
	this := ScreenshotJsonResponse{}
	var cached bool = false
	this.Cached = &cached
	return &this
}

// GetCached returns the Cached field value if set, zero value otherwise.
func (o *ScreenshotJsonResponse) GetCached() bool {
	if o == nil || IsNil(o.Cached) {
		var ret bool
		return ret
	}
	return *o.Cached
}

// GetCachedOk returns a tuple with the Cached field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotJsonResponse) GetCachedOk() (*bool, bool) {
	if o == nil || IsNil(o.Cached) {
		return nil, false
	}
	return o.Cached, true
}

// HasCached returns a boolean if a field has been set.
func (o *ScreenshotJsonResponse) HasCached() bool {
	if o != nil && !IsNil(o.Cached) {
		return true
	}

	return false
}

// SetCached gets a reference to the given bool and assigns it to the Cached field.
func (o *ScreenshotJsonResponse) SetCached(v bool) {
	o.Cached = &v
}

// GetContentType returns the ContentType field value
func (o *ScreenshotJsonResponse) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *ScreenshotJsonResponse) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *ScreenshotJsonResponse) SetContentType(v string) {
	o.ContentType = v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotJsonResponse) GetData() string {
	if o == nil || IsNil(o.Data.Get()) {
		var ret string
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotJsonResponse) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *ScreenshotJsonResponse) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableString and assigns it to the Data field.
func (o *ScreenshotJsonResponse) SetData(v string) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *ScreenshotJsonResponse) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *ScreenshotJsonResponse) UnsetData() {
	o.Data.Unset()
}

// GetEncoding returns the Encoding field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotJsonResponse) GetEncoding() string {
	if o == nil || IsNil(o.Encoding.Get()) {
		var ret string
		return ret
	}
	return *o.Encoding.Get()
}

// GetEncodingOk returns a tuple with the Encoding field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotJsonResponse) GetEncodingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Encoding.Get(), o.Encoding.IsSet()
}

// HasEncoding returns a boolean if a field has been set.
func (o *ScreenshotJsonResponse) HasEncoding() bool {
	if o != nil && o.Encoding.IsSet() {
		return true
	}

	return false
}

// SetEncoding gets a reference to the given NullableString and assigns it to the Encoding field.
func (o *ScreenshotJsonResponse) SetEncoding(v string) {
	o.Encoding.Set(&v)
}
// SetEncodingNil sets the value for Encoding to be an explicit nil
func (o *ScreenshotJsonResponse) SetEncodingNil() {
	o.Encoding.Set(nil)
}

// UnsetEncoding ensures that no value is present for Encoding, not even an explicit nil
func (o *ScreenshotJsonResponse) UnsetEncoding() {
	o.Encoding.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotJsonResponse) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotJsonResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ScreenshotJsonResponse) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *ScreenshotJsonResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *ScreenshotJsonResponse) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *ScreenshotJsonResponse) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetFormat returns the Format field value
func (o *ScreenshotJsonResponse) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *ScreenshotJsonResponse) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *ScreenshotJsonResponse) SetFormat(v string) {
	o.Format = v
}

// GetHeight returns the Height field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotJsonResponse) GetHeight() int32 {
	if o == nil || IsNil(o.Height.Get()) {
		var ret int32
		return ret
	}
	return *o.Height.Get()
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotJsonResponse) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Height.Get(), o.Height.IsSet()
}

// HasHeight returns a boolean if a field has been set.
func (o *ScreenshotJsonResponse) HasHeight() bool {
	if o != nil && o.Height.IsSet() {
		return true
	}

	return false
}

// SetHeight gets a reference to the given NullableInt32 and assigns it to the Height field.
func (o *ScreenshotJsonResponse) SetHeight(v int32) {
	o.Height.Set(&v)
}
// SetHeightNil sets the value for Height to be an explicit nil
func (o *ScreenshotJsonResponse) SetHeightNil() {
	o.Height.Set(nil)
}

// UnsetHeight ensures that no value is present for Height, not even an explicit nil
func (o *ScreenshotJsonResponse) UnsetHeight() {
	o.Height.Unset()
}

// GetRenderTimeMs returns the RenderTimeMs field value
func (o *ScreenshotJsonResponse) GetRenderTimeMs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RenderTimeMs
}

// GetRenderTimeMsOk returns a tuple with the RenderTimeMs field value
// and a boolean to check if the value has been set.
func (o *ScreenshotJsonResponse) GetRenderTimeMsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RenderTimeMs, true
}

// SetRenderTimeMs sets field value
func (o *ScreenshotJsonResponse) SetRenderTimeMs(v int64) {
	o.RenderTimeMs = v
}

// GetResultUrl returns the ResultUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotJsonResponse) GetResultUrl() string {
	if o == nil || IsNil(o.ResultUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ResultUrl.Get()
}

// GetResultUrlOk returns a tuple with the ResultUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotJsonResponse) GetResultUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultUrl.Get(), o.ResultUrl.IsSet()
}

// HasResultUrl returns a boolean if a field has been set.
func (o *ScreenshotJsonResponse) HasResultUrl() bool {
	if o != nil && o.ResultUrl.IsSet() {
		return true
	}

	return false
}

// SetResultUrl gets a reference to the given NullableString and assigns it to the ResultUrl field.
func (o *ScreenshotJsonResponse) SetResultUrl(v string) {
	o.ResultUrl.Set(&v)
}
// SetResultUrlNil sets the value for ResultUrl to be an explicit nil
func (o *ScreenshotJsonResponse) SetResultUrlNil() {
	o.ResultUrl.Set(nil)
}

// UnsetResultUrl ensures that no value is present for ResultUrl, not even an explicit nil
func (o *ScreenshotJsonResponse) UnsetResultUrl() {
	o.ResultUrl.Unset()
}

// GetSize returns the Size field value
func (o *ScreenshotJsonResponse) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ScreenshotJsonResponse) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ScreenshotJsonResponse) SetSize(v int32) {
	o.Size = v
}

// GetStorageUrl returns the StorageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotJsonResponse) GetStorageUrl() string {
	if o == nil || IsNil(o.StorageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.StorageUrl.Get()
}

// GetStorageUrlOk returns a tuple with the StorageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotJsonResponse) GetStorageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageUrl.Get(), o.StorageUrl.IsSet()
}

// HasStorageUrl returns a boolean if a field has been set.
func (o *ScreenshotJsonResponse) HasStorageUrl() bool {
	if o != nil && o.StorageUrl.IsSet() {
		return true
	}

	return false
}

// SetStorageUrl gets a reference to the given NullableString and assigns it to the StorageUrl field.
func (o *ScreenshotJsonResponse) SetStorageUrl(v string) {
	o.StorageUrl.Set(&v)
}
// SetStorageUrlNil sets the value for StorageUrl to be an explicit nil
func (o *ScreenshotJsonResponse) SetStorageUrlNil() {
	o.StorageUrl.Set(nil)
}

// UnsetStorageUrl ensures that no value is present for StorageUrl, not even an explicit nil
func (o *ScreenshotJsonResponse) UnsetStorageUrl() {
	o.StorageUrl.Unset()
}

// GetUrl returns the Url field value
func (o *ScreenshotJsonResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ScreenshotJsonResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ScreenshotJsonResponse) SetUrl(v string) {
	o.Url = v
}

// GetWidth returns the Width field value
func (o *ScreenshotJsonResponse) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *ScreenshotJsonResponse) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *ScreenshotJsonResponse) SetWidth(v int32) {
	o.Width = v
}

func (o ScreenshotJsonResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScreenshotJsonResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cached) {
		toSerialize["cached"] = o.Cached
	}
	toSerialize["contentType"] = o.ContentType
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	if o.Encoding.IsSet() {
		toSerialize["encoding"] = o.Encoding.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expiresAt"] = o.ExpiresAt.Get()
	}
	toSerialize["format"] = o.Format
	if o.Height.IsSet() {
		toSerialize["height"] = o.Height.Get()
	}
	toSerialize["renderTimeMs"] = o.RenderTimeMs
	if o.ResultUrl.IsSet() {
		toSerialize["resultUrl"] = o.ResultUrl.Get()
	}
	toSerialize["size"] = o.Size
	if o.StorageUrl.IsSet() {
		toSerialize["storageUrl"] = o.StorageUrl.Get()
	}
	toSerialize["url"] = o.Url
	toSerialize["width"] = o.Width

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScreenshotJsonResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contentType",
		"format",
		"renderTimeMs",
		"size",
		"url",
		"width",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScreenshotJsonResponse := _ScreenshotJsonResponse{}

	err = json.Unmarshal(data, &varScreenshotJsonResponse)

	if err != nil {
		return err
	}

	*o = ScreenshotJsonResponse(varScreenshotJsonResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cached")
		delete(additionalProperties, "contentType")
		delete(additionalProperties, "data")
		delete(additionalProperties, "encoding")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "format")
		delete(additionalProperties, "height")
		delete(additionalProperties, "renderTimeMs")
		delete(additionalProperties, "resultUrl")
		delete(additionalProperties, "size")
		delete(additionalProperties, "storageUrl")
		delete(additionalProperties, "url")
		delete(additionalProperties, "width")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScreenshotJsonResponse struct {
	value *ScreenshotJsonResponse
	isSet bool
}

func (v NullableScreenshotJsonResponse) Get() *ScreenshotJsonResponse {
	return v.value
}

func (v *NullableScreenshotJsonResponse) Set(val *ScreenshotJsonResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenshotJsonResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenshotJsonResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenshotJsonResponse(val *ScreenshotJsonResponse) *NullableScreenshotJsonResponse {
	return &NullableScreenshotJsonResponse{value: val, isSet: true}
}

func (v NullableScreenshotJsonResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenshotJsonResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


