/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the CrawlPagesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrawlPagesResponse{}

// CrawlPagesResponse struct for CrawlPagesResponse
type CrawlPagesResponse struct {
	Page int32 `json:"page"`
	PageSize int32 `json:"pageSize"`
	Pages []CrawlPageResponse `json:"pages"`
	Total int64 `json:"total"`
	TotalPages int32 `json:"totalPages"`
	AdditionalProperties map[string]interface{}
}

type _CrawlPagesResponse CrawlPagesResponse

// NewCrawlPagesResponse instantiates a new CrawlPagesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrawlPagesResponse(page int32, pageSize int32, pages []CrawlPageResponse, total int64, totalPages int32) *CrawlPagesResponse {
	this := CrawlPagesResponse{}
	this.Page = page
	this.PageSize = pageSize
	this.Pages = pages
	this.Total = total
	this.TotalPages = totalPages
	return &this
}

// NewCrawlPagesResponseWithDefaults instantiates a new CrawlPagesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrawlPagesResponseWithDefaults() *CrawlPagesResponse {
	this := CrawlPagesResponse{}
	return &this
}

// GetPage returns the Page field value
func (o *CrawlPagesResponse) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *CrawlPagesResponse) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *CrawlPagesResponse) SetPage(v int32) {
	o.Page = v
}

// GetPageSize returns the PageSize field value
func (o *CrawlPagesResponse) GetPageSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value
// and a boolean to check if the value has been set.
func (o *CrawlPagesResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageSize, true
}

// SetPageSize sets field value
func (o *CrawlPagesResponse) SetPageSize(v int32) {
	o.PageSize = v
}

// GetPages returns the Pages field value
func (o *CrawlPagesResponse) GetPages() []CrawlPageResponse {
	if o == nil {
		var ret []CrawlPageResponse
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
func (o *CrawlPagesResponse) GetPagesOk() ([]CrawlPageResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pages, true
}

// SetPages sets field value
func (o *CrawlPagesResponse) SetPages(v []CrawlPageResponse) {
	o.Pages = v
}

// GetTotal returns the Total field value
func (o *CrawlPagesResponse) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CrawlPagesResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CrawlPagesResponse) SetTotal(v int64) {
	o.Total = v
}

// GetTotalPages returns the TotalPages field value
func (o *CrawlPagesResponse) GetTotalPages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value
// and a boolean to check if the value has been set.
func (o *CrawlPagesResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPages, true
}

// SetTotalPages sets field value
func (o *CrawlPagesResponse) SetTotalPages(v int32) {
	o.TotalPages = v
}

func (o CrawlPagesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrawlPagesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["pageSize"] = o.PageSize
	toSerialize["pages"] = o.Pages
	toSerialize["total"] = o.Total
	toSerialize["totalPages"] = o.TotalPages

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CrawlPagesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
		"pageSize",
		"pages",
		"total",
		"totalPages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrawlPagesResponse := _CrawlPagesResponse{}

	err = json.Unmarshal(data, &varCrawlPagesResponse)

	if err != nil {
		return err
	}

	*o = CrawlPagesResponse(varCrawlPagesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "page")
		delete(additionalProperties, "pageSize")
		delete(additionalProperties, "pages")
		delete(additionalProperties, "total")
		delete(additionalProperties, "totalPages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCrawlPagesResponse struct {
	value *CrawlPagesResponse
	isSet bool
}

func (v NullableCrawlPagesResponse) Get() *CrawlPagesResponse {
	return v.value
}

func (v *NullableCrawlPagesResponse) Set(val *CrawlPagesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCrawlPagesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCrawlPagesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrawlPagesResponse(val *CrawlPagesResponse) *NullableCrawlPagesResponse {
	return &NullableCrawlPagesResponse{value: val, isSet: true}
}

func (v NullableCrawlPagesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrawlPagesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


