/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the LayoutPreviewResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LayoutPreviewResponse{}

// LayoutPreviewResponse struct for LayoutPreviewResponse
type LayoutPreviewResponse struct {
	CanvasHeight int32 `json:"canvasHeight"`
	CanvasWidth int32 `json:"canvasWidth"`
	Layout string `json:"layout"`
	Metadata map[string]map[string]interface{} `json:"metadata"`
	Placements []PlacementPreview `json:"placements"`
	ResolvedLayout string `json:"resolvedLayout"`
	AdditionalProperties map[string]interface{}
}

type _LayoutPreviewResponse LayoutPreviewResponse

// NewLayoutPreviewResponse instantiates a new LayoutPreviewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLayoutPreviewResponse(canvasHeight int32, canvasWidth int32, layout string, metadata map[string]map[string]interface{}, placements []PlacementPreview, resolvedLayout string) *LayoutPreviewResponse {
	this := LayoutPreviewResponse{}
	this.CanvasHeight = canvasHeight
	this.CanvasWidth = canvasWidth
	this.Layout = layout
	this.Metadata = metadata
	this.Placements = placements
	this.ResolvedLayout = resolvedLayout
	return &this
}

// NewLayoutPreviewResponseWithDefaults instantiates a new LayoutPreviewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLayoutPreviewResponseWithDefaults() *LayoutPreviewResponse {
	this := LayoutPreviewResponse{}
	return &this
}

// GetCanvasHeight returns the CanvasHeight field value
func (o *LayoutPreviewResponse) GetCanvasHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CanvasHeight
}

// GetCanvasHeightOk returns a tuple with the CanvasHeight field value
// and a boolean to check if the value has been set.
func (o *LayoutPreviewResponse) GetCanvasHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanvasHeight, true
}

// SetCanvasHeight sets field value
func (o *LayoutPreviewResponse) SetCanvasHeight(v int32) {
	o.CanvasHeight = v
}

// GetCanvasWidth returns the CanvasWidth field value
func (o *LayoutPreviewResponse) GetCanvasWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CanvasWidth
}

// GetCanvasWidthOk returns a tuple with the CanvasWidth field value
// and a boolean to check if the value has been set.
func (o *LayoutPreviewResponse) GetCanvasWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanvasWidth, true
}

// SetCanvasWidth sets field value
func (o *LayoutPreviewResponse) SetCanvasWidth(v int32) {
	o.CanvasWidth = v
}

// GetLayout returns the Layout field value
func (o *LayoutPreviewResponse) GetLayout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Layout
}

// GetLayoutOk returns a tuple with the Layout field value
// and a boolean to check if the value has been set.
func (o *LayoutPreviewResponse) GetLayoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Layout, true
}

// SetLayout sets field value
func (o *LayoutPreviewResponse) SetLayout(v string) {
	o.Layout = v
}

// GetMetadata returns the Metadata field value
func (o *LayoutPreviewResponse) GetMetadata() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *LayoutPreviewResponse) GetMetadataOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// SetMetadata sets field value
func (o *LayoutPreviewResponse) SetMetadata(v map[string]map[string]interface{}) {
	o.Metadata = v
}

// GetPlacements returns the Placements field value
func (o *LayoutPreviewResponse) GetPlacements() []PlacementPreview {
	if o == nil {
		var ret []PlacementPreview
		return ret
	}

	return o.Placements
}

// GetPlacementsOk returns a tuple with the Placements field value
// and a boolean to check if the value has been set.
func (o *LayoutPreviewResponse) GetPlacementsOk() ([]PlacementPreview, bool) {
	if o == nil {
		return nil, false
	}
	return o.Placements, true
}

// SetPlacements sets field value
func (o *LayoutPreviewResponse) SetPlacements(v []PlacementPreview) {
	o.Placements = v
}

// GetResolvedLayout returns the ResolvedLayout field value
func (o *LayoutPreviewResponse) GetResolvedLayout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResolvedLayout
}

// GetResolvedLayoutOk returns a tuple with the ResolvedLayout field value
// and a boolean to check if the value has been set.
func (o *LayoutPreviewResponse) GetResolvedLayoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolvedLayout, true
}

// SetResolvedLayout sets field value
func (o *LayoutPreviewResponse) SetResolvedLayout(v string) {
	o.ResolvedLayout = v
}

func (o LayoutPreviewResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LayoutPreviewResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["canvasHeight"] = o.CanvasHeight
	toSerialize["canvasWidth"] = o.CanvasWidth
	toSerialize["layout"] = o.Layout
	toSerialize["metadata"] = o.Metadata
	toSerialize["placements"] = o.Placements
	toSerialize["resolvedLayout"] = o.ResolvedLayout

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LayoutPreviewResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"canvasHeight",
		"canvasWidth",
		"layout",
		"metadata",
		"placements",
		"resolvedLayout",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLayoutPreviewResponse := _LayoutPreviewResponse{}

	err = json.Unmarshal(data, &varLayoutPreviewResponse)

	if err != nil {
		return err
	}

	*o = LayoutPreviewResponse(varLayoutPreviewResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "canvasHeight")
		delete(additionalProperties, "canvasWidth")
		delete(additionalProperties, "layout")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "placements")
		delete(additionalProperties, "resolvedLayout")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLayoutPreviewResponse struct {
	value *LayoutPreviewResponse
	isSet bool
}

func (v NullableLayoutPreviewResponse) Get() *LayoutPreviewResponse {
	return v.value
}

func (v *NullableLayoutPreviewResponse) Set(val *LayoutPreviewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLayoutPreviewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLayoutPreviewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLayoutPreviewResponse(val *LayoutPreviewResponse) *NullableLayoutPreviewResponse {
	return &NullableLayoutPreviewResponse{value: val, isSet: true}
}

func (v NullableLayoutPreviewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLayoutPreviewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


