/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the ClickAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClickAction{}

// ClickAction struct for ClickAction
type ClickAction struct {
	Optional *bool `json:"optional,omitempty"`
	Selector string `json:"selector"`
	Timeout NullableInt32 `json:"timeout,omitempty"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _ClickAction ClickAction

// NewClickAction instantiates a new ClickAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClickAction(selector string, type_ string) *ClickAction {
	this := ClickAction{}
	var optional bool = false
	this.Optional = &optional
	this.Selector = selector
	this.Type = type_
	return &this
}

// NewClickActionWithDefaults instantiates a new ClickAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClickActionWithDefaults() *ClickAction {
	this := ClickAction{}
	var optional bool = false
	this.Optional = &optional
	return &this
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *ClickAction) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClickAction) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *ClickAction) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *ClickAction) SetOptional(v bool) {
	o.Optional = &v
}

// GetSelector returns the Selector field value
func (o *ClickAction) GetSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value
// and a boolean to check if the value has been set.
func (o *ClickAction) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selector, true
}

// SetSelector sets field value
func (o *ClickAction) SetSelector(v string) {
	o.Selector = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClickAction) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout.Get()) {
		var ret int32
		return ret
	}
	return *o.Timeout.Get()
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClickAction) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeout.Get(), o.Timeout.IsSet()
}

// HasTimeout returns a boolean if a field has been set.
func (o *ClickAction) HasTimeout() bool {
	if o != nil && o.Timeout.IsSet() {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given NullableInt32 and assigns it to the Timeout field.
func (o *ClickAction) SetTimeout(v int32) {
	o.Timeout.Set(&v)
}
// SetTimeoutNil sets the value for Timeout to be an explicit nil
func (o *ClickAction) SetTimeoutNil() {
	o.Timeout.Set(nil)
}

// UnsetTimeout ensures that no value is present for Timeout, not even an explicit nil
func (o *ClickAction) UnsetTimeout() {
	o.Timeout.Unset()
}

// GetType returns the Type field value
func (o *ClickAction) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ClickAction) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ClickAction) SetType(v string) {
	o.Type = v
}

func (o ClickAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClickAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	toSerialize["selector"] = o.Selector
	if o.Timeout.IsSet() {
		toSerialize["timeout"] = o.Timeout.Get()
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClickAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selector",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClickAction := _ClickAction{}

	err = json.Unmarshal(data, &varClickAction)

	if err != nil {
		return err
	}

	*o = ClickAction(varClickAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "optional")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClickAction struct {
	value *ClickAction
	isSet bool
}

func (v NullableClickAction) Get() *ClickAction {
	return v.value
}

func (v *NullableClickAction) Set(val *ClickAction) {
	v.value = val
	v.isSet = true
}

func (v NullableClickAction) IsSet() bool {
	return v.isSet
}

func (v *NullableClickAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClickAction(val *ClickAction) *NullableClickAction {
	return &NullableClickAction{value: val, isSet: true}
}

func (v NullableClickAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClickAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


