/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CrawlPageOutputResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrawlPageOutputResponse{}

// CrawlPageOutputResponse struct for CrawlPageOutputResponse
type CrawlPageOutputResponse struct {
	ContentType string `json:"contentType"`
	ExpiresAt time.Time `json:"expiresAt"`
	ResultUrl string `json:"resultUrl"`
	Size int64 `json:"size"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _CrawlPageOutputResponse CrawlPageOutputResponse

// NewCrawlPageOutputResponse instantiates a new CrawlPageOutputResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrawlPageOutputResponse(contentType string, expiresAt time.Time, resultUrl string, size int64, type_ string) *CrawlPageOutputResponse {
	this := CrawlPageOutputResponse{}
	this.ContentType = contentType
	this.ExpiresAt = expiresAt
	this.ResultUrl = resultUrl
	this.Size = size
	this.Type = type_
	return &this
}

// NewCrawlPageOutputResponseWithDefaults instantiates a new CrawlPageOutputResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrawlPageOutputResponseWithDefaults() *CrawlPageOutputResponse {
	this := CrawlPageOutputResponse{}
	return &this
}

// GetContentType returns the ContentType field value
func (o *CrawlPageOutputResponse) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *CrawlPageOutputResponse) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *CrawlPageOutputResponse) SetContentType(v string) {
	o.ContentType = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *CrawlPageOutputResponse) GetExpiresAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *CrawlPageOutputResponse) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *CrawlPageOutputResponse) SetExpiresAt(v time.Time) {
	o.ExpiresAt = v
}

// GetResultUrl returns the ResultUrl field value
func (o *CrawlPageOutputResponse) GetResultUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResultUrl
}

// GetResultUrlOk returns a tuple with the ResultUrl field value
// and a boolean to check if the value has been set.
func (o *CrawlPageOutputResponse) GetResultUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResultUrl, true
}

// SetResultUrl sets field value
func (o *CrawlPageOutputResponse) SetResultUrl(v string) {
	o.ResultUrl = v
}

// GetSize returns the Size field value
func (o *CrawlPageOutputResponse) GetSize() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *CrawlPageOutputResponse) GetSizeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *CrawlPageOutputResponse) SetSize(v int64) {
	o.Size = v
}

// GetType returns the Type field value
func (o *CrawlPageOutputResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CrawlPageOutputResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CrawlPageOutputResponse) SetType(v string) {
	o.Type = v
}

func (o CrawlPageOutputResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrawlPageOutputResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contentType"] = o.ContentType
	toSerialize["expiresAt"] = o.ExpiresAt
	toSerialize["resultUrl"] = o.ResultUrl
	toSerialize["size"] = o.Size
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CrawlPageOutputResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contentType",
		"expiresAt",
		"resultUrl",
		"size",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrawlPageOutputResponse := _CrawlPageOutputResponse{}

	err = json.Unmarshal(data, &varCrawlPageOutputResponse)

	if err != nil {
		return err
	}

	*o = CrawlPageOutputResponse(varCrawlPageOutputResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "contentType")
		delete(additionalProperties, "expiresAt")
		delete(additionalProperties, "resultUrl")
		delete(additionalProperties, "size")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCrawlPageOutputResponse struct {
	value *CrawlPageOutputResponse
	isSet bool
}

func (v NullableCrawlPageOutputResponse) Get() *CrawlPageOutputResponse {
	return v.value
}

func (v *NullableCrawlPageOutputResponse) Set(val *CrawlPageOutputResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCrawlPageOutputResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCrawlPageOutputResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrawlPageOutputResponse(val *CrawlPageOutputResponse) *NullableCrawlPageOutputResponse {
	return &NullableCrawlPageOutputResponse{value: val, isSet: true}
}

func (v NullableCrawlPageOutputResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrawlPageOutputResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


