/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the ScrollAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScrollAction{}

// ScrollAction struct for ScrollAction
type ScrollAction struct {
	Optional *bool `json:"optional,omitempty"`
	Selector NullableString `json:"selector,omitempty"`
	Timeout NullableInt32 `json:"timeout,omitempty"`
	ToBottom *bool `json:"toBottom,omitempty"`
	Type string `json:"type"`
	Y NullableInt32 `json:"y,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScrollAction ScrollAction

// NewScrollAction instantiates a new ScrollAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScrollAction(type_ string) *ScrollAction {
	this := ScrollAction{}
	var optional bool = false
	this.Optional = &optional
	var toBottom bool = false
	this.ToBottom = &toBottom
	this.Type = type_
	return &this
}

// NewScrollActionWithDefaults instantiates a new ScrollAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScrollActionWithDefaults() *ScrollAction {
	this := ScrollAction{}
	var optional bool = false
	this.Optional = &optional
	var toBottom bool = false
	this.ToBottom = &toBottom
	return &this
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *ScrollAction) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrollAction) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *ScrollAction) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *ScrollAction) SetOptional(v bool) {
	o.Optional = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScrollAction) GetSelector() string {
	if o == nil || IsNil(o.Selector.Get()) {
		var ret string
		return ret
	}
	return *o.Selector.Get()
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScrollAction) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Selector.Get(), o.Selector.IsSet()
}

// HasSelector returns a boolean if a field has been set.
func (o *ScrollAction) HasSelector() bool {
	if o != nil && o.Selector.IsSet() {
		return true
	}

	return false
}

// SetSelector gets a reference to the given NullableString and assigns it to the Selector field.
func (o *ScrollAction) SetSelector(v string) {
	o.Selector.Set(&v)
}
// SetSelectorNil sets the value for Selector to be an explicit nil
func (o *ScrollAction) SetSelectorNil() {
	o.Selector.Set(nil)
}

// UnsetSelector ensures that no value is present for Selector, not even an explicit nil
func (o *ScrollAction) UnsetSelector() {
	o.Selector.Unset()
}

// GetTimeout returns the Timeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScrollAction) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout.Get()) {
		var ret int32
		return ret
	}
	return *o.Timeout.Get()
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScrollAction) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeout.Get(), o.Timeout.IsSet()
}

// HasTimeout returns a boolean if a field has been set.
func (o *ScrollAction) HasTimeout() bool {
	if o != nil && o.Timeout.IsSet() {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given NullableInt32 and assigns it to the Timeout field.
func (o *ScrollAction) SetTimeout(v int32) {
	o.Timeout.Set(&v)
}
// SetTimeoutNil sets the value for Timeout to be an explicit nil
func (o *ScrollAction) SetTimeoutNil() {
	o.Timeout.Set(nil)
}

// UnsetTimeout ensures that no value is present for Timeout, not even an explicit nil
func (o *ScrollAction) UnsetTimeout() {
	o.Timeout.Unset()
}

// GetToBottom returns the ToBottom field value if set, zero value otherwise.
func (o *ScrollAction) GetToBottom() bool {
	if o == nil || IsNil(o.ToBottom) {
		var ret bool
		return ret
	}
	return *o.ToBottom
}

// GetToBottomOk returns a tuple with the ToBottom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScrollAction) GetToBottomOk() (*bool, bool) {
	if o == nil || IsNil(o.ToBottom) {
		return nil, false
	}
	return o.ToBottom, true
}

// HasToBottom returns a boolean if a field has been set.
func (o *ScrollAction) HasToBottom() bool {
	if o != nil && !IsNil(o.ToBottom) {
		return true
	}

	return false
}

// SetToBottom gets a reference to the given bool and assigns it to the ToBottom field.
func (o *ScrollAction) SetToBottom(v bool) {
	o.ToBottom = &v
}

// GetType returns the Type field value
func (o *ScrollAction) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ScrollAction) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ScrollAction) SetType(v string) {
	o.Type = v
}

// GetY returns the Y field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScrollAction) GetY() int32 {
	if o == nil || IsNil(o.Y.Get()) {
		var ret int32
		return ret
	}
	return *o.Y.Get()
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScrollAction) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Y.Get(), o.Y.IsSet()
}

// HasY returns a boolean if a field has been set.
func (o *ScrollAction) HasY() bool {
	if o != nil && o.Y.IsSet() {
		return true
	}

	return false
}

// SetY gets a reference to the given NullableInt32 and assigns it to the Y field.
func (o *ScrollAction) SetY(v int32) {
	o.Y.Set(&v)
}
// SetYNil sets the value for Y to be an explicit nil
func (o *ScrollAction) SetYNil() {
	o.Y.Set(nil)
}

// UnsetY ensures that no value is present for Y, not even an explicit nil
func (o *ScrollAction) UnsetY() {
	o.Y.Unset()
}

func (o ScrollAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScrollAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	if o.Selector.IsSet() {
		toSerialize["selector"] = o.Selector.Get()
	}
	if o.Timeout.IsSet() {
		toSerialize["timeout"] = o.Timeout.Get()
	}
	if !IsNil(o.ToBottom) {
		toSerialize["toBottom"] = o.ToBottom
	}
	toSerialize["type"] = o.Type
	if o.Y.IsSet() {
		toSerialize["y"] = o.Y.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScrollAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScrollAction := _ScrollAction{}

	err = json.Unmarshal(data, &varScrollAction)

	if err != nil {
		return err
	}

	*o = ScrollAction(varScrollAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "optional")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "toBottom")
		delete(additionalProperties, "type")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScrollAction struct {
	value *ScrollAction
	isSet bool
}

func (v NullableScrollAction) Get() *ScrollAction {
	return v.value
}

func (v *NullableScrollAction) Set(val *ScrollAction) {
	v.value = val
	v.isSet = true
}

func (v NullableScrollAction) IsSet() bool {
	return v.isSet
}

func (v *NullableScrollAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScrollAction(val *ScrollAction) *NullableScrollAction {
	return &NullableScrollAction{value: val, isSet: true}
}

func (v NullableScrollAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScrollAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


