/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the HoverAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HoverAction{}

// HoverAction struct for HoverAction
type HoverAction struct {
	Optional *bool `json:"optional,omitempty"`
	Selector string `json:"selector"`
	Timeout NullableInt32 `json:"timeout,omitempty"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _HoverAction HoverAction

// NewHoverAction instantiates a new HoverAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHoverAction(selector string, type_ string) *HoverAction {
	this := HoverAction{}
	var optional bool = false
	this.Optional = &optional
	this.Selector = selector
	this.Type = type_
	return &this
}

// NewHoverActionWithDefaults instantiates a new HoverAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHoverActionWithDefaults() *HoverAction {
	this := HoverAction{}
	var optional bool = false
	this.Optional = &optional
	return &this
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *HoverAction) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HoverAction) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *HoverAction) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *HoverAction) SetOptional(v bool) {
	o.Optional = &v
}

// GetSelector returns the Selector field value
func (o *HoverAction) GetSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value
// and a boolean to check if the value has been set.
func (o *HoverAction) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selector, true
}

// SetSelector sets field value
func (o *HoverAction) SetSelector(v string) {
	o.Selector = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HoverAction) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout.Get()) {
		var ret int32
		return ret
	}
	return *o.Timeout.Get()
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HoverAction) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeout.Get(), o.Timeout.IsSet()
}

// HasTimeout returns a boolean if a field has been set.
func (o *HoverAction) HasTimeout() bool {
	if o != nil && o.Timeout.IsSet() {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given NullableInt32 and assigns it to the Timeout field.
func (o *HoverAction) SetTimeout(v int32) {
	o.Timeout.Set(&v)
}
// SetTimeoutNil sets the value for Timeout to be an explicit nil
func (o *HoverAction) SetTimeoutNil() {
	o.Timeout.Set(nil)
}

// UnsetTimeout ensures that no value is present for Timeout, not even an explicit nil
func (o *HoverAction) UnsetTimeout() {
	o.Timeout.Unset()
}

// GetType returns the Type field value
func (o *HoverAction) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HoverAction) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HoverAction) SetType(v string) {
	o.Type = v
}

func (o HoverAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HoverAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	toSerialize["selector"] = o.Selector
	if o.Timeout.IsSet() {
		toSerialize["timeout"] = o.Timeout.Get()
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HoverAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selector",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHoverAction := _HoverAction{}

	err = json.Unmarshal(data, &varHoverAction)

	if err != nil {
		return err
	}

	*o = HoverAction(varHoverAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "optional")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHoverAction struct {
	value *HoverAction
	isSet bool
}

func (v NullableHoverAction) Get() *HoverAction {
	return v.value
}

func (v *NullableHoverAction) Set(val *HoverAction) {
	v.value = val
	v.isSet = true
}

func (v NullableHoverAction) IsSet() bool {
	return v.isSet
}

func (v *NullableHoverAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHoverAction(val *HoverAction) *NullableHoverAction {
	return &NullableHoverAction{value: val, isSet: true}
}

func (v NullableHoverAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHoverAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


