/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the CaptureInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CaptureInfo{}

// CaptureInfo struct for CaptureInfo
type CaptureInfo struct {
	Height int32 `json:"height"`
	Id string `json:"id"`
	Label NullableString `json:"label,omitempty"`
	OriginalHeight int32 `json:"originalHeight"`
	OriginalWidth int32 `json:"originalWidth"`
	Url string `json:"url"`
	Width int32 `json:"width"`
	X int32 `json:"x"`
	Y int32 `json:"y"`
	AdditionalProperties map[string]interface{}
}

type _CaptureInfo CaptureInfo

// NewCaptureInfo instantiates a new CaptureInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCaptureInfo(height int32, id string, originalHeight int32, originalWidth int32, url string, width int32, x int32, y int32) *CaptureInfo {
	this := CaptureInfo{}
	this.Height = height
	this.Id = id
	this.OriginalHeight = originalHeight
	this.OriginalWidth = originalWidth
	this.Url = url
	this.Width = width
	this.X = x
	this.Y = y
	return &this
}

// NewCaptureInfoWithDefaults instantiates a new CaptureInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCaptureInfoWithDefaults() *CaptureInfo {
	this := CaptureInfo{}
	return &this
}

// GetHeight returns the Height field value
func (o *CaptureInfo) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *CaptureInfo) SetHeight(v int32) {
	o.Height = v
}

// GetId returns the Id field value
func (o *CaptureInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CaptureInfo) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CaptureInfo) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CaptureInfo) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *CaptureInfo) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *CaptureInfo) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *CaptureInfo) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *CaptureInfo) UnsetLabel() {
	o.Label.Unset()
}

// GetOriginalHeight returns the OriginalHeight field value
func (o *CaptureInfo) GetOriginalHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OriginalHeight
}

// GetOriginalHeightOk returns a tuple with the OriginalHeight field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetOriginalHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalHeight, true
}

// SetOriginalHeight sets field value
func (o *CaptureInfo) SetOriginalHeight(v int32) {
	o.OriginalHeight = v
}

// GetOriginalWidth returns the OriginalWidth field value
func (o *CaptureInfo) GetOriginalWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OriginalWidth
}

// GetOriginalWidthOk returns a tuple with the OriginalWidth field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetOriginalWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalWidth, true
}

// SetOriginalWidth sets field value
func (o *CaptureInfo) SetOriginalWidth(v int32) {
	o.OriginalWidth = v
}

// GetUrl returns the Url field value
func (o *CaptureInfo) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CaptureInfo) SetUrl(v string) {
	o.Url = v
}

// GetWidth returns the Width field value
func (o *CaptureInfo) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *CaptureInfo) SetWidth(v int32) {
	o.Width = v
}

// GetX returns the X field value
func (o *CaptureInfo) GetX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *CaptureInfo) SetX(v int32) {
	o.X = v
}

// GetY returns the Y field value
func (o *CaptureInfo) GetY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *CaptureInfo) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *CaptureInfo) SetY(v int32) {
	o.Y = v
}

func (o CaptureInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CaptureInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["height"] = o.Height
	toSerialize["id"] = o.Id
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	toSerialize["originalHeight"] = o.OriginalHeight
	toSerialize["originalWidth"] = o.OriginalWidth
	toSerialize["url"] = o.Url
	toSerialize["width"] = o.Width
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CaptureInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"height",
		"id",
		"originalHeight",
		"originalWidth",
		"url",
		"width",
		"x",
		"y",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCaptureInfo := _CaptureInfo{}

	err = json.Unmarshal(data, &varCaptureInfo)

	if err != nil {
		return err
	}

	*o = CaptureInfo(varCaptureInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "height")
		delete(additionalProperties, "id")
		delete(additionalProperties, "label")
		delete(additionalProperties, "originalHeight")
		delete(additionalProperties, "originalWidth")
		delete(additionalProperties, "url")
		delete(additionalProperties, "width")
		delete(additionalProperties, "x")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCaptureInfo struct {
	value *CaptureInfo
	isSet bool
}

func (v NullableCaptureInfo) Get() *CaptureInfo {
	return v.value
}

func (v *NullableCaptureInfo) Set(val *CaptureInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCaptureInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCaptureInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCaptureInfo(val *CaptureInfo) *NullableCaptureInfo {
	return &NullableCaptureInfo{value: val, isSet: true}
}

func (v NullableCaptureInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCaptureInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


