/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ScheduleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduleResponse{}

// ScheduleResponse struct for ScheduleResponse
type ScheduleResponse struct {
	AlertOnFailure bool `json:"alertOnFailure"`
	AutoPauseAfterFailures NullableInt32 `json:"autoPauseAfterFailures,omitempty"`
	ConsecutiveFailures int32 `json:"consecutiveFailures"`
	CreatedAt time.Time `json:"createdAt"`
	Destinations []DeliveryDestination `json:"destinations,omitempty"`
	DiffThreshold NullableFloat64 `json:"diffThreshold,omitempty"`
	EndsAt NullableTime `json:"endsAt,omitempty"`
	ExecutionCount int32 `json:"executionCount"`
	FailureCount int32 `json:"failureCount"`
	Id string `json:"id"`
	LastExecutedAt NullableTime `json:"lastExecutedAt,omitempty"`
	Name string `json:"name"`
	NextExecutionAt NullableTime `json:"nextExecutionAt,omitempty"`
	OnlyOnChange bool `json:"onlyOnChange"`
	Options map[string]map[string]interface{} `json:"options,omitempty"`
	RetentionDays int32 `json:"retentionDays"`
	Schedule string `json:"schedule"`
	ScheduleDescription string `json:"scheduleDescription"`
	StartsAt NullableTime `json:"startsAt,omitempty"`
	Status string `json:"status"`
	SuccessCount int32 `json:"successCount"`
	Timezone string `json:"timezone"`
	UpdatedAt time.Time `json:"updatedAt"`
	Url string `json:"url"`
	WebhookUrl NullableString `json:"webhookUrl,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScheduleResponse ScheduleResponse

// NewScheduleResponse instantiates a new ScheduleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduleResponse(alertOnFailure bool, consecutiveFailures int32, createdAt time.Time, executionCount int32, failureCount int32, id string, name string, onlyOnChange bool, retentionDays int32, schedule string, scheduleDescription string, status string, successCount int32, timezone string, updatedAt time.Time, url string) *ScheduleResponse {
	this := ScheduleResponse{}
	this.AlertOnFailure = alertOnFailure
	this.ConsecutiveFailures = consecutiveFailures
	this.CreatedAt = createdAt
	this.ExecutionCount = executionCount
	this.FailureCount = failureCount
	this.Id = id
	this.Name = name
	this.OnlyOnChange = onlyOnChange
	this.RetentionDays = retentionDays
	this.Schedule = schedule
	this.ScheduleDescription = scheduleDescription
	this.Status = status
	this.SuccessCount = successCount
	this.Timezone = timezone
	this.UpdatedAt = updatedAt
	this.Url = url
	return &this
}

// NewScheduleResponseWithDefaults instantiates a new ScheduleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduleResponseWithDefaults() *ScheduleResponse {
	this := ScheduleResponse{}
	return &this
}

// GetAlertOnFailure returns the AlertOnFailure field value
func (o *ScheduleResponse) GetAlertOnFailure() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AlertOnFailure
}

// GetAlertOnFailureOk returns a tuple with the AlertOnFailure field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetAlertOnFailureOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertOnFailure, true
}

// SetAlertOnFailure sets field value
func (o *ScheduleResponse) SetAlertOnFailure(v bool) {
	o.AlertOnFailure = v
}

// GetAutoPauseAfterFailures returns the AutoPauseAfterFailures field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetAutoPauseAfterFailures() int32 {
	if o == nil || IsNil(o.AutoPauseAfterFailures.Get()) {
		var ret int32
		return ret
	}
	return *o.AutoPauseAfterFailures.Get()
}

// GetAutoPauseAfterFailuresOk returns a tuple with the AutoPauseAfterFailures field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetAutoPauseAfterFailuresOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AutoPauseAfterFailures.Get(), o.AutoPauseAfterFailures.IsSet()
}

// HasAutoPauseAfterFailures returns a boolean if a field has been set.
func (o *ScheduleResponse) HasAutoPauseAfterFailures() bool {
	if o != nil && o.AutoPauseAfterFailures.IsSet() {
		return true
	}

	return false
}

// SetAutoPauseAfterFailures gets a reference to the given NullableInt32 and assigns it to the AutoPauseAfterFailures field.
func (o *ScheduleResponse) SetAutoPauseAfterFailures(v int32) {
	o.AutoPauseAfterFailures.Set(&v)
}
// SetAutoPauseAfterFailuresNil sets the value for AutoPauseAfterFailures to be an explicit nil
func (o *ScheduleResponse) SetAutoPauseAfterFailuresNil() {
	o.AutoPauseAfterFailures.Set(nil)
}

// UnsetAutoPauseAfterFailures ensures that no value is present for AutoPauseAfterFailures, not even an explicit nil
func (o *ScheduleResponse) UnsetAutoPauseAfterFailures() {
	o.AutoPauseAfterFailures.Unset()
}

// GetConsecutiveFailures returns the ConsecutiveFailures field value
func (o *ScheduleResponse) GetConsecutiveFailures() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConsecutiveFailures
}

// GetConsecutiveFailuresOk returns a tuple with the ConsecutiveFailures field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetConsecutiveFailuresOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsecutiveFailures, true
}

// SetConsecutiveFailures sets field value
func (o *ScheduleResponse) SetConsecutiveFailures(v int32) {
	o.ConsecutiveFailures = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ScheduleResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ScheduleResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDestinations returns the Destinations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetDestinations() []DeliveryDestination {
	if o == nil {
		var ret []DeliveryDestination
		return ret
	}
	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetDestinationsOk() ([]DeliveryDestination, bool) {
	if o == nil || IsNil(o.Destinations) {
		return nil, false
	}
	return o.Destinations, true
}

// HasDestinations returns a boolean if a field has been set.
func (o *ScheduleResponse) HasDestinations() bool {
	if o != nil && !IsNil(o.Destinations) {
		return true
	}

	return false
}

// SetDestinations gets a reference to the given []DeliveryDestination and assigns it to the Destinations field.
func (o *ScheduleResponse) SetDestinations(v []DeliveryDestination) {
	o.Destinations = v
}

// GetDiffThreshold returns the DiffThreshold field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetDiffThreshold() float64 {
	if o == nil || IsNil(o.DiffThreshold.Get()) {
		var ret float64
		return ret
	}
	return *o.DiffThreshold.Get()
}

// GetDiffThresholdOk returns a tuple with the DiffThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetDiffThresholdOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiffThreshold.Get(), o.DiffThreshold.IsSet()
}

// HasDiffThreshold returns a boolean if a field has been set.
func (o *ScheduleResponse) HasDiffThreshold() bool {
	if o != nil && o.DiffThreshold.IsSet() {
		return true
	}

	return false
}

// SetDiffThreshold gets a reference to the given NullableFloat64 and assigns it to the DiffThreshold field.
func (o *ScheduleResponse) SetDiffThreshold(v float64) {
	o.DiffThreshold.Set(&v)
}
// SetDiffThresholdNil sets the value for DiffThreshold to be an explicit nil
func (o *ScheduleResponse) SetDiffThresholdNil() {
	o.DiffThreshold.Set(nil)
}

// UnsetDiffThreshold ensures that no value is present for DiffThreshold, not even an explicit nil
func (o *ScheduleResponse) UnsetDiffThreshold() {
	o.DiffThreshold.Unset()
}

// GetEndsAt returns the EndsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetEndsAt() time.Time {
	if o == nil || IsNil(o.EndsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.EndsAt.Get()
}

// GetEndsAtOk returns a tuple with the EndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetEndsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndsAt.Get(), o.EndsAt.IsSet()
}

// HasEndsAt returns a boolean if a field has been set.
func (o *ScheduleResponse) HasEndsAt() bool {
	if o != nil && o.EndsAt.IsSet() {
		return true
	}

	return false
}

// SetEndsAt gets a reference to the given NullableTime and assigns it to the EndsAt field.
func (o *ScheduleResponse) SetEndsAt(v time.Time) {
	o.EndsAt.Set(&v)
}
// SetEndsAtNil sets the value for EndsAt to be an explicit nil
func (o *ScheduleResponse) SetEndsAtNil() {
	o.EndsAt.Set(nil)
}

// UnsetEndsAt ensures that no value is present for EndsAt, not even an explicit nil
func (o *ScheduleResponse) UnsetEndsAt() {
	o.EndsAt.Unset()
}

// GetExecutionCount returns the ExecutionCount field value
func (o *ScheduleResponse) GetExecutionCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExecutionCount
}

// GetExecutionCountOk returns a tuple with the ExecutionCount field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetExecutionCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionCount, true
}

// SetExecutionCount sets field value
func (o *ScheduleResponse) SetExecutionCount(v int32) {
	o.ExecutionCount = v
}

// GetFailureCount returns the FailureCount field value
func (o *ScheduleResponse) GetFailureCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailureCount
}

// GetFailureCountOk returns a tuple with the FailureCount field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetFailureCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailureCount, true
}

// SetFailureCount sets field value
func (o *ScheduleResponse) SetFailureCount(v int32) {
	o.FailureCount = v
}

// GetId returns the Id field value
func (o *ScheduleResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ScheduleResponse) SetId(v string) {
	o.Id = v
}

// GetLastExecutedAt returns the LastExecutedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetLastExecutedAt() time.Time {
	if o == nil || IsNil(o.LastExecutedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastExecutedAt.Get()
}

// GetLastExecutedAtOk returns a tuple with the LastExecutedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetLastExecutedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastExecutedAt.Get(), o.LastExecutedAt.IsSet()
}

// HasLastExecutedAt returns a boolean if a field has been set.
func (o *ScheduleResponse) HasLastExecutedAt() bool {
	if o != nil && o.LastExecutedAt.IsSet() {
		return true
	}

	return false
}

// SetLastExecutedAt gets a reference to the given NullableTime and assigns it to the LastExecutedAt field.
func (o *ScheduleResponse) SetLastExecutedAt(v time.Time) {
	o.LastExecutedAt.Set(&v)
}
// SetLastExecutedAtNil sets the value for LastExecutedAt to be an explicit nil
func (o *ScheduleResponse) SetLastExecutedAtNil() {
	o.LastExecutedAt.Set(nil)
}

// UnsetLastExecutedAt ensures that no value is present for LastExecutedAt, not even an explicit nil
func (o *ScheduleResponse) UnsetLastExecutedAt() {
	o.LastExecutedAt.Unset()
}

// GetName returns the Name field value
func (o *ScheduleResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ScheduleResponse) SetName(v string) {
	o.Name = v
}

// GetNextExecutionAt returns the NextExecutionAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetNextExecutionAt() time.Time {
	if o == nil || IsNil(o.NextExecutionAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.NextExecutionAt.Get()
}

// GetNextExecutionAtOk returns a tuple with the NextExecutionAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetNextExecutionAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextExecutionAt.Get(), o.NextExecutionAt.IsSet()
}

// HasNextExecutionAt returns a boolean if a field has been set.
func (o *ScheduleResponse) HasNextExecutionAt() bool {
	if o != nil && o.NextExecutionAt.IsSet() {
		return true
	}

	return false
}

// SetNextExecutionAt gets a reference to the given NullableTime and assigns it to the NextExecutionAt field.
func (o *ScheduleResponse) SetNextExecutionAt(v time.Time) {
	o.NextExecutionAt.Set(&v)
}
// SetNextExecutionAtNil sets the value for NextExecutionAt to be an explicit nil
func (o *ScheduleResponse) SetNextExecutionAtNil() {
	o.NextExecutionAt.Set(nil)
}

// UnsetNextExecutionAt ensures that no value is present for NextExecutionAt, not even an explicit nil
func (o *ScheduleResponse) UnsetNextExecutionAt() {
	o.NextExecutionAt.Unset()
}

// GetOnlyOnChange returns the OnlyOnChange field value
func (o *ScheduleResponse) GetOnlyOnChange() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OnlyOnChange
}

// GetOnlyOnChangeOk returns a tuple with the OnlyOnChange field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetOnlyOnChangeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlyOnChange, true
}

// SetOnlyOnChange sets field value
func (o *ScheduleResponse) SetOnlyOnChange(v bool) {
	o.OnlyOnChange = v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetOptions() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetOptionsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *ScheduleResponse) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]map[string]interface{} and assigns it to the Options field.
func (o *ScheduleResponse) SetOptions(v map[string]map[string]interface{}) {
	o.Options = v
}

// GetRetentionDays returns the RetentionDays field value
func (o *ScheduleResponse) GetRetentionDays() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RetentionDays
}

// GetRetentionDaysOk returns a tuple with the RetentionDays field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetRetentionDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetentionDays, true
}

// SetRetentionDays sets field value
func (o *ScheduleResponse) SetRetentionDays(v int32) {
	o.RetentionDays = v
}

// GetSchedule returns the Schedule field value
func (o *ScheduleResponse) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *ScheduleResponse) SetSchedule(v string) {
	o.Schedule = v
}

// GetScheduleDescription returns the ScheduleDescription field value
func (o *ScheduleResponse) GetScheduleDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScheduleDescription
}

// GetScheduleDescriptionOk returns a tuple with the ScheduleDescription field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetScheduleDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduleDescription, true
}

// SetScheduleDescription sets field value
func (o *ScheduleResponse) SetScheduleDescription(v string) {
	o.ScheduleDescription = v
}

// GetStartsAt returns the StartsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetStartsAt() time.Time {
	if o == nil || IsNil(o.StartsAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.StartsAt.Get()
}

// GetStartsAtOk returns a tuple with the StartsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetStartsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartsAt.Get(), o.StartsAt.IsSet()
}

// HasStartsAt returns a boolean if a field has been set.
func (o *ScheduleResponse) HasStartsAt() bool {
	if o != nil && o.StartsAt.IsSet() {
		return true
	}

	return false
}

// SetStartsAt gets a reference to the given NullableTime and assigns it to the StartsAt field.
func (o *ScheduleResponse) SetStartsAt(v time.Time) {
	o.StartsAt.Set(&v)
}
// SetStartsAtNil sets the value for StartsAt to be an explicit nil
func (o *ScheduleResponse) SetStartsAtNil() {
	o.StartsAt.Set(nil)
}

// UnsetStartsAt ensures that no value is present for StartsAt, not even an explicit nil
func (o *ScheduleResponse) UnsetStartsAt() {
	o.StartsAt.Unset()
}

// GetStatus returns the Status field value
func (o *ScheduleResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ScheduleResponse) SetStatus(v string) {
	o.Status = v
}

// GetSuccessCount returns the SuccessCount field value
func (o *ScheduleResponse) GetSuccessCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SuccessCount
}

// GetSuccessCountOk returns a tuple with the SuccessCount field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetSuccessCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessCount, true
}

// SetSuccessCount sets field value
func (o *ScheduleResponse) SetSuccessCount(v int32) {
	o.SuccessCount = v
}

// GetTimezone returns the Timezone field value
func (o *ScheduleResponse) GetTimezone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetTimezoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timezone, true
}

// SetTimezone sets field value
func (o *ScheduleResponse) SetTimezone(v string) {
	o.Timezone = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ScheduleResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ScheduleResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetUrl returns the Url field value
func (o *ScheduleResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ScheduleResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ScheduleResponse) SetUrl(v string) {
	o.Url = v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScheduleResponse) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookUrl.Get()
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScheduleResponse) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookUrl.Get(), o.WebhookUrl.IsSet()
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *ScheduleResponse) HasWebhookUrl() bool {
	if o != nil && o.WebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given NullableString and assigns it to the WebhookUrl field.
func (o *ScheduleResponse) SetWebhookUrl(v string) {
	o.WebhookUrl.Set(&v)
}
// SetWebhookUrlNil sets the value for WebhookUrl to be an explicit nil
func (o *ScheduleResponse) SetWebhookUrlNil() {
	o.WebhookUrl.Set(nil)
}

// UnsetWebhookUrl ensures that no value is present for WebhookUrl, not even an explicit nil
func (o *ScheduleResponse) UnsetWebhookUrl() {
	o.WebhookUrl.Unset()
}

func (o ScheduleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alertOnFailure"] = o.AlertOnFailure
	if o.AutoPauseAfterFailures.IsSet() {
		toSerialize["autoPauseAfterFailures"] = o.AutoPauseAfterFailures.Get()
	}
	toSerialize["consecutiveFailures"] = o.ConsecutiveFailures
	toSerialize["createdAt"] = o.CreatedAt
	if o.Destinations != nil {
		toSerialize["destinations"] = o.Destinations
	}
	if o.DiffThreshold.IsSet() {
		toSerialize["diffThreshold"] = o.DiffThreshold.Get()
	}
	if o.EndsAt.IsSet() {
		toSerialize["endsAt"] = o.EndsAt.Get()
	}
	toSerialize["executionCount"] = o.ExecutionCount
	toSerialize["failureCount"] = o.FailureCount
	toSerialize["id"] = o.Id
	if o.LastExecutedAt.IsSet() {
		toSerialize["lastExecutedAt"] = o.LastExecutedAt.Get()
	}
	toSerialize["name"] = o.Name
	if o.NextExecutionAt.IsSet() {
		toSerialize["nextExecutionAt"] = o.NextExecutionAt.Get()
	}
	toSerialize["onlyOnChange"] = o.OnlyOnChange
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	toSerialize["retentionDays"] = o.RetentionDays
	toSerialize["schedule"] = o.Schedule
	toSerialize["scheduleDescription"] = o.ScheduleDescription
	if o.StartsAt.IsSet() {
		toSerialize["startsAt"] = o.StartsAt.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["successCount"] = o.SuccessCount
	toSerialize["timezone"] = o.Timezone
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["url"] = o.Url
	if o.WebhookUrl.IsSet() {
		toSerialize["webhookUrl"] = o.WebhookUrl.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScheduleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alertOnFailure",
		"consecutiveFailures",
		"createdAt",
		"executionCount",
		"failureCount",
		"id",
		"name",
		"onlyOnChange",
		"retentionDays",
		"schedule",
		"scheduleDescription",
		"status",
		"successCount",
		"timezone",
		"updatedAt",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScheduleResponse := _ScheduleResponse{}

	err = json.Unmarshal(data, &varScheduleResponse)

	if err != nil {
		return err
	}

	*o = ScheduleResponse(varScheduleResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "alertOnFailure")
		delete(additionalProperties, "autoPauseAfterFailures")
		delete(additionalProperties, "consecutiveFailures")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "destinations")
		delete(additionalProperties, "diffThreshold")
		delete(additionalProperties, "endsAt")
		delete(additionalProperties, "executionCount")
		delete(additionalProperties, "failureCount")
		delete(additionalProperties, "id")
		delete(additionalProperties, "lastExecutedAt")
		delete(additionalProperties, "name")
		delete(additionalProperties, "nextExecutionAt")
		delete(additionalProperties, "onlyOnChange")
		delete(additionalProperties, "options")
		delete(additionalProperties, "retentionDays")
		delete(additionalProperties, "schedule")
		delete(additionalProperties, "scheduleDescription")
		delete(additionalProperties, "startsAt")
		delete(additionalProperties, "status")
		delete(additionalProperties, "successCount")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "url")
		delete(additionalProperties, "webhookUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScheduleResponse struct {
	value *ScheduleResponse
	isSet bool
}

func (v NullableScheduleResponse) Get() *ScheduleResponse {
	return v.value
}

func (v *NullableScheduleResponse) Set(val *ScheduleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduleResponse(val *ScheduleResponse) *NullableScheduleResponse {
	return &NullableScheduleResponse{value: val, isSet: true}
}

func (v NullableScheduleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


