/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the HtmlOutputSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HtmlOutputSpec{}

// HtmlOutputSpec struct for HtmlOutputSpec
type HtmlOutputSpec struct {
	Clean *bool `json:"clean,omitempty"`
	Id NullableString `json:"id,omitempty"`
	MainContentOnly *bool `json:"mainContentOnly,omitempty"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _HtmlOutputSpec HtmlOutputSpec

// NewHtmlOutputSpec instantiates a new HtmlOutputSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHtmlOutputSpec(type_ string) *HtmlOutputSpec {
	this := HtmlOutputSpec{}
	var clean bool = true
	this.Clean = &clean
	var mainContentOnly bool = false
	this.MainContentOnly = &mainContentOnly
	this.Type = type_
	return &this
}

// NewHtmlOutputSpecWithDefaults instantiates a new HtmlOutputSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHtmlOutputSpecWithDefaults() *HtmlOutputSpec {
	this := HtmlOutputSpec{}
	var clean bool = true
	this.Clean = &clean
	var mainContentOnly bool = false
	this.MainContentOnly = &mainContentOnly
	return &this
}

// GetClean returns the Clean field value if set, zero value otherwise.
func (o *HtmlOutputSpec) GetClean() bool {
	if o == nil || IsNil(o.Clean) {
		var ret bool
		return ret
	}
	return *o.Clean
}

// GetCleanOk returns a tuple with the Clean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlOutputSpec) GetCleanOk() (*bool, bool) {
	if o == nil || IsNil(o.Clean) {
		return nil, false
	}
	return o.Clean, true
}

// HasClean returns a boolean if a field has been set.
func (o *HtmlOutputSpec) HasClean() bool {
	if o != nil && !IsNil(o.Clean) {
		return true
	}

	return false
}

// SetClean gets a reference to the given bool and assigns it to the Clean field.
func (o *HtmlOutputSpec) SetClean(v bool) {
	o.Clean = &v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HtmlOutputSpec) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HtmlOutputSpec) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *HtmlOutputSpec) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *HtmlOutputSpec) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *HtmlOutputSpec) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *HtmlOutputSpec) UnsetId() {
	o.Id.Unset()
}

// GetMainContentOnly returns the MainContentOnly field value if set, zero value otherwise.
func (o *HtmlOutputSpec) GetMainContentOnly() bool {
	if o == nil || IsNil(o.MainContentOnly) {
		var ret bool
		return ret
	}
	return *o.MainContentOnly
}

// GetMainContentOnlyOk returns a tuple with the MainContentOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlOutputSpec) GetMainContentOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.MainContentOnly) {
		return nil, false
	}
	return o.MainContentOnly, true
}

// HasMainContentOnly returns a boolean if a field has been set.
func (o *HtmlOutputSpec) HasMainContentOnly() bool {
	if o != nil && !IsNil(o.MainContentOnly) {
		return true
	}

	return false
}

// SetMainContentOnly gets a reference to the given bool and assigns it to the MainContentOnly field.
func (o *HtmlOutputSpec) SetMainContentOnly(v bool) {
	o.MainContentOnly = &v
}

// GetType returns the Type field value
func (o *HtmlOutputSpec) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HtmlOutputSpec) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HtmlOutputSpec) SetType(v string) {
	o.Type = v
}

func (o HtmlOutputSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HtmlOutputSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Clean) {
		toSerialize["clean"] = o.Clean
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.MainContentOnly) {
		toSerialize["mainContentOnly"] = o.MainContentOnly
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *HtmlOutputSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHtmlOutputSpec := _HtmlOutputSpec{}

	err = json.Unmarshal(data, &varHtmlOutputSpec)

	if err != nil {
		return err
	}

	*o = HtmlOutputSpec(varHtmlOutputSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "clean")
		delete(additionalProperties, "id")
		delete(additionalProperties, "mainContentOnly")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableHtmlOutputSpec struct {
	value *HtmlOutputSpec
	isSet bool
}

func (v NullableHtmlOutputSpec) Get() *HtmlOutputSpec {
	return v.value
}

func (v *NullableHtmlOutputSpec) Set(val *HtmlOutputSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableHtmlOutputSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableHtmlOutputSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHtmlOutputSpec(val *HtmlOutputSpec) *NullableHtmlOutputSpec {
	return &NullableHtmlOutputSpec{value: val, isSet: true}
}

func (v NullableHtmlOutputSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHtmlOutputSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


