/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the JsonOutputSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonOutputSpec{}

// JsonOutputSpec struct for JsonOutputSpec
type JsonOutputSpec struct {
	Id NullableString `json:"id,omitempty"`
	Schema map[string]JsonFieldSpec `json:"schema"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _JsonOutputSpec JsonOutputSpec

// NewJsonOutputSpec instantiates a new JsonOutputSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonOutputSpec(schema map[string]JsonFieldSpec, type_ string) *JsonOutputSpec {
	this := JsonOutputSpec{}
	this.Schema = schema
	this.Type = type_
	return &this
}

// NewJsonOutputSpecWithDefaults instantiates a new JsonOutputSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonOutputSpecWithDefaults() *JsonOutputSpec {
	this := JsonOutputSpec{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JsonOutputSpec) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JsonOutputSpec) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *JsonOutputSpec) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *JsonOutputSpec) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *JsonOutputSpec) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *JsonOutputSpec) UnsetId() {
	o.Id.Unset()
}

// GetSchema returns the Schema field value
func (o *JsonOutputSpec) GetSchema() map[string]JsonFieldSpec {
	if o == nil {
		var ret map[string]JsonFieldSpec
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
func (o *JsonOutputSpec) GetSchemaOk() (*map[string]JsonFieldSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *JsonOutputSpec) SetSchema(v map[string]JsonFieldSpec) {
	o.Schema = v
}

// GetType returns the Type field value
func (o *JsonOutputSpec) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *JsonOutputSpec) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *JsonOutputSpec) SetType(v string) {
	o.Type = v
}

func (o JsonOutputSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonOutputSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	toSerialize["schema"] = o.Schema
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JsonOutputSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schema",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJsonOutputSpec := _JsonOutputSpec{}

	err = json.Unmarshal(data, &varJsonOutputSpec)

	if err != nil {
		return err
	}

	*o = JsonOutputSpec(varJsonOutputSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "schema")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJsonOutputSpec struct {
	value *JsonOutputSpec
	isSet bool
}

func (v NullableJsonOutputSpec) Get() *JsonOutputSpec {
	return v.value
}

func (v *NullableJsonOutputSpec) Set(val *JsonOutputSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonOutputSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonOutputSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonOutputSpec(val *JsonOutputSpec) *NullableJsonOutputSpec {
	return &NullableJsonOutputSpec{value: val, isSet: true}
}

func (v NullableJsonOutputSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonOutputSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


