/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the PlacementPreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlacementPreview{}

// PlacementPreview struct for PlacementPreview
type PlacementPreview struct {
	Height int32 `json:"height"`
	Index int32 `json:"index"`
	Label NullableString `json:"label,omitempty"`
	Width int32 `json:"width"`
	X int32 `json:"x"`
	Y int32 `json:"y"`
	AdditionalProperties map[string]interface{}
}

type _PlacementPreview PlacementPreview

// NewPlacementPreview instantiates a new PlacementPreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlacementPreview(height int32, index int32, width int32, x int32, y int32) *PlacementPreview {
	this := PlacementPreview{}
	this.Height = height
	this.Index = index
	this.Width = width
	this.X = x
	this.Y = y
	return &this
}

// NewPlacementPreviewWithDefaults instantiates a new PlacementPreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlacementPreviewWithDefaults() *PlacementPreview {
	this := PlacementPreview{}
	return &this
}

// GetHeight returns the Height field value
func (o *PlacementPreview) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *PlacementPreview) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *PlacementPreview) SetHeight(v int32) {
	o.Height = v
}

// GetIndex returns the Index field value
func (o *PlacementPreview) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *PlacementPreview) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *PlacementPreview) SetIndex(v int32) {
	o.Index = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PlacementPreview) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PlacementPreview) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *PlacementPreview) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *PlacementPreview) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *PlacementPreview) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *PlacementPreview) UnsetLabel() {
	o.Label.Unset()
}

// GetWidth returns the Width field value
func (o *PlacementPreview) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *PlacementPreview) GetWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *PlacementPreview) SetWidth(v int32) {
	o.Width = v
}

// GetX returns the X field value
func (o *PlacementPreview) GetX() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.X
}

// GetXOk returns a tuple with the X field value
// and a boolean to check if the value has been set.
func (o *PlacementPreview) GetXOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.X, true
}

// SetX sets field value
func (o *PlacementPreview) SetX(v int32) {
	o.X = v
}

// GetY returns the Y field value
func (o *PlacementPreview) GetY() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Y
}

// GetYOk returns a tuple with the Y field value
// and a boolean to check if the value has been set.
func (o *PlacementPreview) GetYOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Y, true
}

// SetY sets field value
func (o *PlacementPreview) SetY(v int32) {
	o.Y = v
}

func (o PlacementPreview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlacementPreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["height"] = o.Height
	toSerialize["index"] = o.Index
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	toSerialize["width"] = o.Width
	toSerialize["x"] = o.X
	toSerialize["y"] = o.Y

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlacementPreview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"height",
		"index",
		"width",
		"x",
		"y",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlacementPreview := _PlacementPreview{}

	err = json.Unmarshal(data, &varPlacementPreview)

	if err != nil {
		return err
	}

	*o = PlacementPreview(varPlacementPreview)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "height")
		delete(additionalProperties, "index")
		delete(additionalProperties, "label")
		delete(additionalProperties, "width")
		delete(additionalProperties, "x")
		delete(additionalProperties, "y")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlacementPreview struct {
	value *PlacementPreview
	isSet bool
}

func (v NullablePlacementPreview) Get() *PlacementPreview {
	return v.value
}

func (v *NullablePlacementPreview) Set(val *PlacementPreview) {
	v.value = val
	v.isSet = true
}

func (v NullablePlacementPreview) IsSet() bool {
	return v.isSet
}

func (v *NullablePlacementPreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlacementPreview(val *PlacementPreview) *NullablePlacementPreview {
	return &NullablePlacementPreview{value: val, isSet: true}
}

func (v NullablePlacementPreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlacementPreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


