/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// OutputSpec - struct for OutputSpec
type OutputSpec struct {
	HtmlOutputSpec *HtmlOutputSpec
	JsonOutputSpec *JsonOutputSpec
	MarkdownOutputSpec *MarkdownOutputSpec
	PdfOutputSpec *PdfOutputSpec
	ScreenshotOutputSpec *ScreenshotOutputSpec
}

// HtmlOutputSpecAsOutputSpec is a convenience function that returns HtmlOutputSpec wrapped in OutputSpec
func HtmlOutputSpecAsOutputSpec(v *HtmlOutputSpec) OutputSpec {
	return OutputSpec{
		HtmlOutputSpec: v,
	}
}

// JsonOutputSpecAsOutputSpec is a convenience function that returns JsonOutputSpec wrapped in OutputSpec
func JsonOutputSpecAsOutputSpec(v *JsonOutputSpec) OutputSpec {
	return OutputSpec{
		JsonOutputSpec: v,
	}
}

// MarkdownOutputSpecAsOutputSpec is a convenience function that returns MarkdownOutputSpec wrapped in OutputSpec
func MarkdownOutputSpecAsOutputSpec(v *MarkdownOutputSpec) OutputSpec {
	return OutputSpec{
		MarkdownOutputSpec: v,
	}
}

// PdfOutputSpecAsOutputSpec is a convenience function that returns PdfOutputSpec wrapped in OutputSpec
func PdfOutputSpecAsOutputSpec(v *PdfOutputSpec) OutputSpec {
	return OutputSpec{
		PdfOutputSpec: v,
	}
}

// ScreenshotOutputSpecAsOutputSpec is a convenience function that returns ScreenshotOutputSpec wrapped in OutputSpec
func ScreenshotOutputSpecAsOutputSpec(v *ScreenshotOutputSpec) OutputSpec {
	return OutputSpec{
		ScreenshotOutputSpec: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OutputSpec) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'html'
	if jsonDict["type"] == "html" {
		// try to unmarshal JSON data into HtmlOutputSpec
		err = json.Unmarshal(data, &dst.HtmlOutputSpec)
		if err == nil {
			return nil // data stored in dst.HtmlOutputSpec, return on the first match
		} else {
			dst.HtmlOutputSpec = nil
			return fmt.Errorf("failed to unmarshal OutputSpec as HtmlOutputSpec: %s", err.Error())
		}
	}

	// check if the discriminator value is 'json'
	if jsonDict["type"] == "json" {
		// try to unmarshal JSON data into JsonOutputSpec
		err = json.Unmarshal(data, &dst.JsonOutputSpec)
		if err == nil {
			return nil // data stored in dst.JsonOutputSpec, return on the first match
		} else {
			dst.JsonOutputSpec = nil
			return fmt.Errorf("failed to unmarshal OutputSpec as JsonOutputSpec: %s", err.Error())
		}
	}

	// check if the discriminator value is 'markdown'
	if jsonDict["type"] == "markdown" {
		// try to unmarshal JSON data into MarkdownOutputSpec
		err = json.Unmarshal(data, &dst.MarkdownOutputSpec)
		if err == nil {
			return nil // data stored in dst.MarkdownOutputSpec, return on the first match
		} else {
			dst.MarkdownOutputSpec = nil
			return fmt.Errorf("failed to unmarshal OutputSpec as MarkdownOutputSpec: %s", err.Error())
		}
	}

	// check if the discriminator value is 'pdf'
	if jsonDict["type"] == "pdf" {
		// try to unmarshal JSON data into PdfOutputSpec
		err = json.Unmarshal(data, &dst.PdfOutputSpec)
		if err == nil {
			return nil // data stored in dst.PdfOutputSpec, return on the first match
		} else {
			dst.PdfOutputSpec = nil
			return fmt.Errorf("failed to unmarshal OutputSpec as PdfOutputSpec: %s", err.Error())
		}
	}

	// check if the discriminator value is 'screenshot'
	if jsonDict["type"] == "screenshot" {
		// try to unmarshal JSON data into ScreenshotOutputSpec
		err = json.Unmarshal(data, &dst.ScreenshotOutputSpec)
		if err == nil {
			return nil // data stored in dst.ScreenshotOutputSpec, return on the first match
		} else {
			dst.ScreenshotOutputSpec = nil
			return fmt.Errorf("failed to unmarshal OutputSpec as ScreenshotOutputSpec: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OutputSpec) MarshalJSON() ([]byte, error) {
	if src.HtmlOutputSpec != nil {
		return json.Marshal(&src.HtmlOutputSpec)
	}

	if src.JsonOutputSpec != nil {
		return json.Marshal(&src.JsonOutputSpec)
	}

	if src.MarkdownOutputSpec != nil {
		return json.Marshal(&src.MarkdownOutputSpec)
	}

	if src.PdfOutputSpec != nil {
		return json.Marshal(&src.PdfOutputSpec)
	}

	if src.ScreenshotOutputSpec != nil {
		return json.Marshal(&src.ScreenshotOutputSpec)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OutputSpec) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.HtmlOutputSpec != nil {
		return obj.HtmlOutputSpec
	}

	if obj.JsonOutputSpec != nil {
		return obj.JsonOutputSpec
	}

	if obj.MarkdownOutputSpec != nil {
		return obj.MarkdownOutputSpec
	}

	if obj.PdfOutputSpec != nil {
		return obj.PdfOutputSpec
	}

	if obj.ScreenshotOutputSpec != nil {
		return obj.ScreenshotOutputSpec
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OutputSpec) GetActualInstanceValue() (interface{}) {
	if obj.HtmlOutputSpec != nil {
		return *obj.HtmlOutputSpec
	}

	if obj.JsonOutputSpec != nil {
		return *obj.JsonOutputSpec
	}

	if obj.MarkdownOutputSpec != nil {
		return *obj.MarkdownOutputSpec
	}

	if obj.PdfOutputSpec != nil {
		return *obj.PdfOutputSpec
	}

	if obj.ScreenshotOutputSpec != nil {
		return *obj.ScreenshotOutputSpec
	}

	// all schemas are nil
	return nil
}

type NullableOutputSpec struct {
	value *OutputSpec
	isSet bool
}

func (v NullableOutputSpec) Get() *OutputSpec {
	return v.value
}

func (v *NullableOutputSpec) Set(val *OutputSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputSpec(val *OutputSpec) *NullableOutputSpec {
	return &NullableOutputSpec{value: val, isSet: true}
}

func (v NullableOutputSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


