/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the CreditBalanceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditBalanceResponse{}

// CreditBalanceResponse struct for CreditBalanceResponse
type CreditBalanceResponse struct {
	AllowanceType string `json:"allowanceType"`
	Balance int32 `json:"balance"`
	ResetsAt NullableString `json:"resetsAt,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreditBalanceResponse CreditBalanceResponse

// NewCreditBalanceResponse instantiates a new CreditBalanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditBalanceResponse(allowanceType string, balance int32) *CreditBalanceResponse {
	this := CreditBalanceResponse{}
	this.AllowanceType = allowanceType
	this.Balance = balance
	return &this
}

// NewCreditBalanceResponseWithDefaults instantiates a new CreditBalanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditBalanceResponseWithDefaults() *CreditBalanceResponse {
	this := CreditBalanceResponse{}
	return &this
}

// GetAllowanceType returns the AllowanceType field value
func (o *CreditBalanceResponse) GetAllowanceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AllowanceType
}

// GetAllowanceTypeOk returns a tuple with the AllowanceType field value
// and a boolean to check if the value has been set.
func (o *CreditBalanceResponse) GetAllowanceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowanceType, true
}

// SetAllowanceType sets field value
func (o *CreditBalanceResponse) SetAllowanceType(v string) {
	o.AllowanceType = v
}

// GetBalance returns the Balance field value
func (o *CreditBalanceResponse) GetBalance() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *CreditBalanceResponse) GetBalanceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *CreditBalanceResponse) SetBalance(v int32) {
	o.Balance = v
}

// GetResetsAt returns the ResetsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreditBalanceResponse) GetResetsAt() string {
	if o == nil || IsNil(o.ResetsAt.Get()) {
		var ret string
		return ret
	}
	return *o.ResetsAt.Get()
}

// GetResetsAtOk returns a tuple with the ResetsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreditBalanceResponse) GetResetsAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResetsAt.Get(), o.ResetsAt.IsSet()
}

// HasResetsAt returns a boolean if a field has been set.
func (o *CreditBalanceResponse) HasResetsAt() bool {
	if o != nil && o.ResetsAt.IsSet() {
		return true
	}

	return false
}

// SetResetsAt gets a reference to the given NullableString and assigns it to the ResetsAt field.
func (o *CreditBalanceResponse) SetResetsAt(v string) {
	o.ResetsAt.Set(&v)
}
// SetResetsAtNil sets the value for ResetsAt to be an explicit nil
func (o *CreditBalanceResponse) SetResetsAtNil() {
	o.ResetsAt.Set(nil)
}

// UnsetResetsAt ensures that no value is present for ResetsAt, not even an explicit nil
func (o *CreditBalanceResponse) UnsetResetsAt() {
	o.ResetsAt.Unset()
}

func (o CreditBalanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditBalanceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allowanceType"] = o.AllowanceType
	toSerialize["balance"] = o.Balance
	if o.ResetsAt.IsSet() {
		toSerialize["resetsAt"] = o.ResetsAt.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreditBalanceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowanceType",
		"balance",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditBalanceResponse := _CreditBalanceResponse{}

	err = json.Unmarshal(data, &varCreditBalanceResponse)

	if err != nil {
		return err
	}

	*o = CreditBalanceResponse(varCreditBalanceResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "allowanceType")
		delete(additionalProperties, "balance")
		delete(additionalProperties, "resetsAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreditBalanceResponse struct {
	value *CreditBalanceResponse
	isSet bool
}

func (v NullableCreditBalanceResponse) Get() *CreditBalanceResponse {
	return v.value
}

func (v *NullableCreditBalanceResponse) Set(val *CreditBalanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditBalanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditBalanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditBalanceResponse(val *CreditBalanceResponse) *NullableCreditBalanceResponse {
	return &NullableCreditBalanceResponse{value: val, isSet: true}
}

func (v NullableCreditBalanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditBalanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


