/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the UsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsageResponse{}

// UsageResponse struct for UsageResponse
type UsageResponse struct {
	Credits CreditBalanceResponse `json:"credits"`
	CurrentPeriod PeriodUsageResponse `json:"currentPeriod"`
	History []PeriodUsageResponse `json:"history"`
	Organization UsageOrganizationResponse `json:"organization"`
	Quota QuotaResponse `json:"quota"`
	Tier string `json:"tier"`
	Totals TotalsResponse `json:"totals"`
	AdditionalProperties map[string]interface{}
}

type _UsageResponse UsageResponse

// NewUsageResponse instantiates a new UsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageResponse(credits CreditBalanceResponse, currentPeriod PeriodUsageResponse, history []PeriodUsageResponse, organization UsageOrganizationResponse, quota QuotaResponse, tier string, totals TotalsResponse) *UsageResponse {
	this := UsageResponse{}
	this.Credits = credits
	this.CurrentPeriod = currentPeriod
	this.History = history
	this.Organization = organization
	this.Quota = quota
	this.Tier = tier
	this.Totals = totals
	return &this
}

// NewUsageResponseWithDefaults instantiates a new UsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageResponseWithDefaults() *UsageResponse {
	this := UsageResponse{}
	return &this
}

// GetCredits returns the Credits field value
func (o *UsageResponse) GetCredits() CreditBalanceResponse {
	if o == nil {
		var ret CreditBalanceResponse
		return ret
	}

	return o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetCreditsOk() (*CreditBalanceResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credits, true
}

// SetCredits sets field value
func (o *UsageResponse) SetCredits(v CreditBalanceResponse) {
	o.Credits = v
}

// GetCurrentPeriod returns the CurrentPeriod field value
func (o *UsageResponse) GetCurrentPeriod() PeriodUsageResponse {
	if o == nil {
		var ret PeriodUsageResponse
		return ret
	}

	return o.CurrentPeriod
}

// GetCurrentPeriodOk returns a tuple with the CurrentPeriod field value
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetCurrentPeriodOk() (*PeriodUsageResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentPeriod, true
}

// SetCurrentPeriod sets field value
func (o *UsageResponse) SetCurrentPeriod(v PeriodUsageResponse) {
	o.CurrentPeriod = v
}

// GetHistory returns the History field value
func (o *UsageResponse) GetHistory() []PeriodUsageResponse {
	if o == nil {
		var ret []PeriodUsageResponse
		return ret
	}

	return o.History
}

// GetHistoryOk returns a tuple with the History field value
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetHistoryOk() ([]PeriodUsageResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.History, true
}

// SetHistory sets field value
func (o *UsageResponse) SetHistory(v []PeriodUsageResponse) {
	o.History = v
}

// GetOrganization returns the Organization field value
func (o *UsageResponse) GetOrganization() UsageOrganizationResponse {
	if o == nil {
		var ret UsageOrganizationResponse
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetOrganizationOk() (*UsageOrganizationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *UsageResponse) SetOrganization(v UsageOrganizationResponse) {
	o.Organization = v
}

// GetQuota returns the Quota field value
func (o *UsageResponse) GetQuota() QuotaResponse {
	if o == nil {
		var ret QuotaResponse
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetQuotaOk() (*QuotaResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *UsageResponse) SetQuota(v QuotaResponse) {
	o.Quota = v
}

// GetTier returns the Tier field value
func (o *UsageResponse) GetTier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tier
}

// GetTierOk returns a tuple with the Tier field value
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tier, true
}

// SetTier sets field value
func (o *UsageResponse) SetTier(v string) {
	o.Tier = v
}

// GetTotals returns the Totals field value
func (o *UsageResponse) GetTotals() TotalsResponse {
	if o == nil {
		var ret TotalsResponse
		return ret
	}

	return o.Totals
}

// GetTotalsOk returns a tuple with the Totals field value
// and a boolean to check if the value has been set.
func (o *UsageResponse) GetTotalsOk() (*TotalsResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Totals, true
}

// SetTotals sets field value
func (o *UsageResponse) SetTotals(v TotalsResponse) {
	o.Totals = v
}

func (o UsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credits"] = o.Credits
	toSerialize["currentPeriod"] = o.CurrentPeriod
	toSerialize["history"] = o.History
	toSerialize["organization"] = o.Organization
	toSerialize["quota"] = o.Quota
	toSerialize["tier"] = o.Tier
	toSerialize["totals"] = o.Totals

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UsageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credits",
		"currentPeriod",
		"history",
		"organization",
		"quota",
		"tier",
		"totals",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsageResponse := _UsageResponse{}

	err = json.Unmarshal(data, &varUsageResponse)

	if err != nil {
		return err
	}

	*o = UsageResponse(varUsageResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "credits")
		delete(additionalProperties, "currentPeriod")
		delete(additionalProperties, "history")
		delete(additionalProperties, "organization")
		delete(additionalProperties, "quota")
		delete(additionalProperties, "tier")
		delete(additionalProperties, "totals")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUsageResponse struct {
	value *UsageResponse
	isSet bool
}

func (v NullableUsageResponse) Get() *UsageResponse {
	return v.value
}

func (v *NullableUsageResponse) Set(val *UsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageResponse(val *UsageResponse) *NullableUsageResponse {
	return &NullableUsageResponse{value: val, isSet: true}
}

func (v NullableUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


