/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the CrawlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrawlRequest{}

// CrawlRequest struct for CrawlRequest
type CrawlRequest struct {
	BlockAds *bool `json:"blockAds,omitempty"`
	BlockCookieBanners *bool `json:"blockCookieBanners,omitempty"`
	BlockPopups *bool `json:"blockPopups,omitempty"`
	CrawlDelayMs *int32 `json:"crawlDelayMs,omitempty"`
	DarkMode *bool `json:"darkMode,omitempty"`
	Depth *int32 `json:"depth,omitempty"`
	ExcludePatterns []string `json:"excludePatterns,omitempty"`
	Format *string `json:"format,omitempty" validate:"regexp=^(png|jpeg|jpg)$"`
	FullPage *bool `json:"fullPage,omitempty"`
	IncludePatterns []string `json:"includePatterns,omitempty"`
	IncludeSubdomains *bool `json:"includeSubdomains,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Outputs []OutputSpec `json:"outputs,omitempty"`
	Quality *int32 `json:"quality,omitempty"`
	RenderDelay *int32 `json:"renderDelay,omitempty"`
	Timeout *int32 `json:"timeout,omitempty"`
	Url string `json:"url" validate:"regexp=^https?://.*"`
	Viewport *ViewportConfig `json:"viewport,omitempty"`
	WaitUntil *string `json:"waitUntil,omitempty" validate:"regexp=^(load|domcontentloaded|networkidle)$"`
	AdditionalProperties map[string]interface{}
}

type _CrawlRequest CrawlRequest

// NewCrawlRequest instantiates a new CrawlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrawlRequest(url string) *CrawlRequest {
	this := CrawlRequest{}
	var blockAds bool = true
	this.BlockAds = &blockAds
	var blockCookieBanners bool = true
	this.BlockCookieBanners = &blockCookieBanners
	var blockPopups bool = true
	this.BlockPopups = &blockPopups
	var crawlDelayMs int32 = 500
	this.CrawlDelayMs = &crawlDelayMs
	var darkMode bool = false
	this.DarkMode = &darkMode
	var depth int32 = 2
	this.Depth = &depth
	var format string = "png"
	this.Format = &format
	var fullPage bool = true
	this.FullPage = &fullPage
	var includeSubdomains bool = false
	this.IncludeSubdomains = &includeSubdomains
	var limit int32 = 25
	this.Limit = &limit
	var quality int32 = 80
	this.Quality = &quality
	var renderDelay int32 = 0
	this.RenderDelay = &renderDelay
	var timeout int32 = 30000
	this.Timeout = &timeout
	this.Url = url
	var waitUntil string = "domcontentloaded"
	this.WaitUntil = &waitUntil
	return &this
}

// NewCrawlRequestWithDefaults instantiates a new CrawlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrawlRequestWithDefaults() *CrawlRequest {
	this := CrawlRequest{}
	var blockAds bool = true
	this.BlockAds = &blockAds
	var blockCookieBanners bool = true
	this.BlockCookieBanners = &blockCookieBanners
	var blockPopups bool = true
	this.BlockPopups = &blockPopups
	var crawlDelayMs int32 = 500
	this.CrawlDelayMs = &crawlDelayMs
	var darkMode bool = false
	this.DarkMode = &darkMode
	var depth int32 = 2
	this.Depth = &depth
	var format string = "png"
	this.Format = &format
	var fullPage bool = true
	this.FullPage = &fullPage
	var includeSubdomains bool = false
	this.IncludeSubdomains = &includeSubdomains
	var limit int32 = 25
	this.Limit = &limit
	var quality int32 = 80
	this.Quality = &quality
	var renderDelay int32 = 0
	this.RenderDelay = &renderDelay
	var timeout int32 = 30000
	this.Timeout = &timeout
	var waitUntil string = "domcontentloaded"
	this.WaitUntil = &waitUntil
	return &this
}

// GetBlockAds returns the BlockAds field value if set, zero value otherwise.
func (o *CrawlRequest) GetBlockAds() bool {
	if o == nil || IsNil(o.BlockAds) {
		var ret bool
		return ret
	}
	return *o.BlockAds
}

// GetBlockAdsOk returns a tuple with the BlockAds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetBlockAdsOk() (*bool, bool) {
	if o == nil || IsNil(o.BlockAds) {
		return nil, false
	}
	return o.BlockAds, true
}

// HasBlockAds returns a boolean if a field has been set.
func (o *CrawlRequest) HasBlockAds() bool {
	if o != nil && !IsNil(o.BlockAds) {
		return true
	}

	return false
}

// SetBlockAds gets a reference to the given bool and assigns it to the BlockAds field.
func (o *CrawlRequest) SetBlockAds(v bool) {
	o.BlockAds = &v
}

// GetBlockCookieBanners returns the BlockCookieBanners field value if set, zero value otherwise.
func (o *CrawlRequest) GetBlockCookieBanners() bool {
	if o == nil || IsNil(o.BlockCookieBanners) {
		var ret bool
		return ret
	}
	return *o.BlockCookieBanners
}

// GetBlockCookieBannersOk returns a tuple with the BlockCookieBanners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetBlockCookieBannersOk() (*bool, bool) {
	if o == nil || IsNil(o.BlockCookieBanners) {
		return nil, false
	}
	return o.BlockCookieBanners, true
}

// HasBlockCookieBanners returns a boolean if a field has been set.
func (o *CrawlRequest) HasBlockCookieBanners() bool {
	if o != nil && !IsNil(o.BlockCookieBanners) {
		return true
	}

	return false
}

// SetBlockCookieBanners gets a reference to the given bool and assigns it to the BlockCookieBanners field.
func (o *CrawlRequest) SetBlockCookieBanners(v bool) {
	o.BlockCookieBanners = &v
}

// GetBlockPopups returns the BlockPopups field value if set, zero value otherwise.
func (o *CrawlRequest) GetBlockPopups() bool {
	if o == nil || IsNil(o.BlockPopups) {
		var ret bool
		return ret
	}
	return *o.BlockPopups
}

// GetBlockPopupsOk returns a tuple with the BlockPopups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetBlockPopupsOk() (*bool, bool) {
	if o == nil || IsNil(o.BlockPopups) {
		return nil, false
	}
	return o.BlockPopups, true
}

// HasBlockPopups returns a boolean if a field has been set.
func (o *CrawlRequest) HasBlockPopups() bool {
	if o != nil && !IsNil(o.BlockPopups) {
		return true
	}

	return false
}

// SetBlockPopups gets a reference to the given bool and assigns it to the BlockPopups field.
func (o *CrawlRequest) SetBlockPopups(v bool) {
	o.BlockPopups = &v
}

// GetCrawlDelayMs returns the CrawlDelayMs field value if set, zero value otherwise.
func (o *CrawlRequest) GetCrawlDelayMs() int32 {
	if o == nil || IsNil(o.CrawlDelayMs) {
		var ret int32
		return ret
	}
	return *o.CrawlDelayMs
}

// GetCrawlDelayMsOk returns a tuple with the CrawlDelayMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetCrawlDelayMsOk() (*int32, bool) {
	if o == nil || IsNil(o.CrawlDelayMs) {
		return nil, false
	}
	return o.CrawlDelayMs, true
}

// HasCrawlDelayMs returns a boolean if a field has been set.
func (o *CrawlRequest) HasCrawlDelayMs() bool {
	if o != nil && !IsNil(o.CrawlDelayMs) {
		return true
	}

	return false
}

// SetCrawlDelayMs gets a reference to the given int32 and assigns it to the CrawlDelayMs field.
func (o *CrawlRequest) SetCrawlDelayMs(v int32) {
	o.CrawlDelayMs = &v
}

// GetDarkMode returns the DarkMode field value if set, zero value otherwise.
func (o *CrawlRequest) GetDarkMode() bool {
	if o == nil || IsNil(o.DarkMode) {
		var ret bool
		return ret
	}
	return *o.DarkMode
}

// GetDarkModeOk returns a tuple with the DarkMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetDarkModeOk() (*bool, bool) {
	if o == nil || IsNil(o.DarkMode) {
		return nil, false
	}
	return o.DarkMode, true
}

// HasDarkMode returns a boolean if a field has been set.
func (o *CrawlRequest) HasDarkMode() bool {
	if o != nil && !IsNil(o.DarkMode) {
		return true
	}

	return false
}

// SetDarkMode gets a reference to the given bool and assigns it to the DarkMode field.
func (o *CrawlRequest) SetDarkMode(v bool) {
	o.DarkMode = &v
}

// GetDepth returns the Depth field value if set, zero value otherwise.
func (o *CrawlRequest) GetDepth() int32 {
	if o == nil || IsNil(o.Depth) {
		var ret int32
		return ret
	}
	return *o.Depth
}

// GetDepthOk returns a tuple with the Depth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.Depth) {
		return nil, false
	}
	return o.Depth, true
}

// HasDepth returns a boolean if a field has been set.
func (o *CrawlRequest) HasDepth() bool {
	if o != nil && !IsNil(o.Depth) {
		return true
	}

	return false
}

// SetDepth gets a reference to the given int32 and assigns it to the Depth field.
func (o *CrawlRequest) SetDepth(v int32) {
	o.Depth = &v
}

// GetExcludePatterns returns the ExcludePatterns field value if set, zero value otherwise.
func (o *CrawlRequest) GetExcludePatterns() []string {
	if o == nil || IsNil(o.ExcludePatterns) {
		var ret []string
		return ret
	}
	return o.ExcludePatterns
}

// GetExcludePatternsOk returns a tuple with the ExcludePatterns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetExcludePatternsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludePatterns) {
		return nil, false
	}
	return o.ExcludePatterns, true
}

// HasExcludePatterns returns a boolean if a field has been set.
func (o *CrawlRequest) HasExcludePatterns() bool {
	if o != nil && !IsNil(o.ExcludePatterns) {
		return true
	}

	return false
}

// SetExcludePatterns gets a reference to the given []string and assigns it to the ExcludePatterns field.
func (o *CrawlRequest) SetExcludePatterns(v []string) {
	o.ExcludePatterns = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *CrawlRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *CrawlRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *CrawlRequest) SetFormat(v string) {
	o.Format = &v
}

// GetFullPage returns the FullPage field value if set, zero value otherwise.
func (o *CrawlRequest) GetFullPage() bool {
	if o == nil || IsNil(o.FullPage) {
		var ret bool
		return ret
	}
	return *o.FullPage
}

// GetFullPageOk returns a tuple with the FullPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetFullPageOk() (*bool, bool) {
	if o == nil || IsNil(o.FullPage) {
		return nil, false
	}
	return o.FullPage, true
}

// HasFullPage returns a boolean if a field has been set.
func (o *CrawlRequest) HasFullPage() bool {
	if o != nil && !IsNil(o.FullPage) {
		return true
	}

	return false
}

// SetFullPage gets a reference to the given bool and assigns it to the FullPage field.
func (o *CrawlRequest) SetFullPage(v bool) {
	o.FullPage = &v
}

// GetIncludePatterns returns the IncludePatterns field value if set, zero value otherwise.
func (o *CrawlRequest) GetIncludePatterns() []string {
	if o == nil || IsNil(o.IncludePatterns) {
		var ret []string
		return ret
	}
	return o.IncludePatterns
}

// GetIncludePatternsOk returns a tuple with the IncludePatterns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetIncludePatternsOk() ([]string, bool) {
	if o == nil || IsNil(o.IncludePatterns) {
		return nil, false
	}
	return o.IncludePatterns, true
}

// HasIncludePatterns returns a boolean if a field has been set.
func (o *CrawlRequest) HasIncludePatterns() bool {
	if o != nil && !IsNil(o.IncludePatterns) {
		return true
	}

	return false
}

// SetIncludePatterns gets a reference to the given []string and assigns it to the IncludePatterns field.
func (o *CrawlRequest) SetIncludePatterns(v []string) {
	o.IncludePatterns = v
}

// GetIncludeSubdomains returns the IncludeSubdomains field value if set, zero value otherwise.
func (o *CrawlRequest) GetIncludeSubdomains() bool {
	if o == nil || IsNil(o.IncludeSubdomains) {
		var ret bool
		return ret
	}
	return *o.IncludeSubdomains
}

// GetIncludeSubdomainsOk returns a tuple with the IncludeSubdomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetIncludeSubdomainsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeSubdomains) {
		return nil, false
	}
	return o.IncludeSubdomains, true
}

// HasIncludeSubdomains returns a boolean if a field has been set.
func (o *CrawlRequest) HasIncludeSubdomains() bool {
	if o != nil && !IsNil(o.IncludeSubdomains) {
		return true
	}

	return false
}

// SetIncludeSubdomains gets a reference to the given bool and assigns it to the IncludeSubdomains field.
func (o *CrawlRequest) SetIncludeSubdomains(v bool) {
	o.IncludeSubdomains = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *CrawlRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *CrawlRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *CrawlRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetOutputs returns the Outputs field value if set, zero value otherwise.
func (o *CrawlRequest) GetOutputs() []OutputSpec {
	if o == nil || IsNil(o.Outputs) {
		var ret []OutputSpec
		return ret
	}
	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetOutputsOk() ([]OutputSpec, bool) {
	if o == nil || IsNil(o.Outputs) {
		return nil, false
	}
	return o.Outputs, true
}

// HasOutputs returns a boolean if a field has been set.
func (o *CrawlRequest) HasOutputs() bool {
	if o != nil && !IsNil(o.Outputs) {
		return true
	}

	return false
}

// SetOutputs gets a reference to the given []OutputSpec and assigns it to the Outputs field.
func (o *CrawlRequest) SetOutputs(v []OutputSpec) {
	o.Outputs = v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *CrawlRequest) GetQuality() int32 {
	if o == nil || IsNil(o.Quality) {
		var ret int32
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetQualityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *CrawlRequest) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given int32 and assigns it to the Quality field.
func (o *CrawlRequest) SetQuality(v int32) {
	o.Quality = &v
}

// GetRenderDelay returns the RenderDelay field value if set, zero value otherwise.
func (o *CrawlRequest) GetRenderDelay() int32 {
	if o == nil || IsNil(o.RenderDelay) {
		var ret int32
		return ret
	}
	return *o.RenderDelay
}

// GetRenderDelayOk returns a tuple with the RenderDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetRenderDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.RenderDelay) {
		return nil, false
	}
	return o.RenderDelay, true
}

// HasRenderDelay returns a boolean if a field has been set.
func (o *CrawlRequest) HasRenderDelay() bool {
	if o != nil && !IsNil(o.RenderDelay) {
		return true
	}

	return false
}

// SetRenderDelay gets a reference to the given int32 and assigns it to the RenderDelay field.
func (o *CrawlRequest) SetRenderDelay(v int32) {
	o.RenderDelay = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *CrawlRequest) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *CrawlRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *CrawlRequest) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetUrl returns the Url field value
func (o *CrawlRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CrawlRequest) SetUrl(v string) {
	o.Url = v
}

// GetViewport returns the Viewport field value if set, zero value otherwise.
func (o *CrawlRequest) GetViewport() ViewportConfig {
	if o == nil || IsNil(o.Viewport) {
		var ret ViewportConfig
		return ret
	}
	return *o.Viewport
}

// GetViewportOk returns a tuple with the Viewport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetViewportOk() (*ViewportConfig, bool) {
	if o == nil || IsNil(o.Viewport) {
		return nil, false
	}
	return o.Viewport, true
}

// HasViewport returns a boolean if a field has been set.
func (o *CrawlRequest) HasViewport() bool {
	if o != nil && !IsNil(o.Viewport) {
		return true
	}

	return false
}

// SetViewport gets a reference to the given ViewportConfig and assigns it to the Viewport field.
func (o *CrawlRequest) SetViewport(v ViewportConfig) {
	o.Viewport = &v
}

// GetWaitUntil returns the WaitUntil field value if set, zero value otherwise.
func (o *CrawlRequest) GetWaitUntil() string {
	if o == nil || IsNil(o.WaitUntil) {
		var ret string
		return ret
	}
	return *o.WaitUntil
}

// GetWaitUntilOk returns a tuple with the WaitUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrawlRequest) GetWaitUntilOk() (*string, bool) {
	if o == nil || IsNil(o.WaitUntil) {
		return nil, false
	}
	return o.WaitUntil, true
}

// HasWaitUntil returns a boolean if a field has been set.
func (o *CrawlRequest) HasWaitUntil() bool {
	if o != nil && !IsNil(o.WaitUntil) {
		return true
	}

	return false
}

// SetWaitUntil gets a reference to the given string and assigns it to the WaitUntil field.
func (o *CrawlRequest) SetWaitUntil(v string) {
	o.WaitUntil = &v
}

func (o CrawlRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrawlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlockAds) {
		toSerialize["blockAds"] = o.BlockAds
	}
	if !IsNil(o.BlockCookieBanners) {
		toSerialize["blockCookieBanners"] = o.BlockCookieBanners
	}
	if !IsNil(o.BlockPopups) {
		toSerialize["blockPopups"] = o.BlockPopups
	}
	if !IsNil(o.CrawlDelayMs) {
		toSerialize["crawlDelayMs"] = o.CrawlDelayMs
	}
	if !IsNil(o.DarkMode) {
		toSerialize["darkMode"] = o.DarkMode
	}
	if !IsNil(o.Depth) {
		toSerialize["depth"] = o.Depth
	}
	if !IsNil(o.ExcludePatterns) {
		toSerialize["excludePatterns"] = o.ExcludePatterns
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.FullPage) {
		toSerialize["fullPage"] = o.FullPage
	}
	if !IsNil(o.IncludePatterns) {
		toSerialize["includePatterns"] = o.IncludePatterns
	}
	if !IsNil(o.IncludeSubdomains) {
		toSerialize["includeSubdomains"] = o.IncludeSubdomains
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Outputs) {
		toSerialize["outputs"] = o.Outputs
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	if !IsNil(o.RenderDelay) {
		toSerialize["renderDelay"] = o.RenderDelay
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	toSerialize["url"] = o.Url
	if !IsNil(o.Viewport) {
		toSerialize["viewport"] = o.Viewport
	}
	if !IsNil(o.WaitUntil) {
		toSerialize["waitUntil"] = o.WaitUntil
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CrawlRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrawlRequest := _CrawlRequest{}

	err = json.Unmarshal(data, &varCrawlRequest)

	if err != nil {
		return err
	}

	*o = CrawlRequest(varCrawlRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "blockAds")
		delete(additionalProperties, "blockCookieBanners")
		delete(additionalProperties, "blockPopups")
		delete(additionalProperties, "crawlDelayMs")
		delete(additionalProperties, "darkMode")
		delete(additionalProperties, "depth")
		delete(additionalProperties, "excludePatterns")
		delete(additionalProperties, "format")
		delete(additionalProperties, "fullPage")
		delete(additionalProperties, "includePatterns")
		delete(additionalProperties, "includeSubdomains")
		delete(additionalProperties, "limit")
		delete(additionalProperties, "outputs")
		delete(additionalProperties, "quality")
		delete(additionalProperties, "renderDelay")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "url")
		delete(additionalProperties, "viewport")
		delete(additionalProperties, "waitUntil")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCrawlRequest struct {
	value *CrawlRequest
	isSet bool
}

func (v NullableCrawlRequest) Get() *CrawlRequest {
	return v.value
}

func (v *NullableCrawlRequest) Set(val *CrawlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCrawlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCrawlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrawlRequest(val *CrawlRequest) *NullableCrawlRequest {
	return &NullableCrawlRequest{value: val, isSet: true}
}

func (v NullableCrawlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrawlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


