/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
)

// checks if the BrowserSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrowserSessionRequest{}

// BrowserSessionRequest struct for BrowserSessionRequest
type BrowserSessionRequest struct {
	Cookies []BrowserCookieRequest `json:"cookies,omitempty"`
	Headers []BrowserHeaderRequest `json:"headers,omitempty"`
	Storage []BrowserStorageOriginRequest `json:"storage,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BrowserSessionRequest BrowserSessionRequest

// NewBrowserSessionRequest instantiates a new BrowserSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrowserSessionRequest() *BrowserSessionRequest {
	this := BrowserSessionRequest{}
	return &this
}

// NewBrowserSessionRequestWithDefaults instantiates a new BrowserSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrowserSessionRequestWithDefaults() *BrowserSessionRequest {
	this := BrowserSessionRequest{}
	return &this
}

// GetCookies returns the Cookies field value if set, zero value otherwise.
func (o *BrowserSessionRequest) GetCookies() []BrowserCookieRequest {
	if o == nil || IsNil(o.Cookies) {
		var ret []BrowserCookieRequest
		return ret
	}
	return o.Cookies
}

// GetCookiesOk returns a tuple with the Cookies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrowserSessionRequest) GetCookiesOk() ([]BrowserCookieRequest, bool) {
	if o == nil || IsNil(o.Cookies) {
		return nil, false
	}
	return o.Cookies, true
}

// HasCookies returns a boolean if a field has been set.
func (o *BrowserSessionRequest) HasCookies() bool {
	if o != nil && !IsNil(o.Cookies) {
		return true
	}

	return false
}

// SetCookies gets a reference to the given []BrowserCookieRequest and assigns it to the Cookies field.
func (o *BrowserSessionRequest) SetCookies(v []BrowserCookieRequest) {
	o.Cookies = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *BrowserSessionRequest) GetHeaders() []BrowserHeaderRequest {
	if o == nil || IsNil(o.Headers) {
		var ret []BrowserHeaderRequest
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrowserSessionRequest) GetHeadersOk() ([]BrowserHeaderRequest, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *BrowserSessionRequest) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given []BrowserHeaderRequest and assigns it to the Headers field.
func (o *BrowserSessionRequest) SetHeaders(v []BrowserHeaderRequest) {
	o.Headers = v
}

// GetStorage returns the Storage field value if set, zero value otherwise.
func (o *BrowserSessionRequest) GetStorage() []BrowserStorageOriginRequest {
	if o == nil || IsNil(o.Storage) {
		var ret []BrowserStorageOriginRequest
		return ret
	}
	return o.Storage
}

// GetStorageOk returns a tuple with the Storage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrowserSessionRequest) GetStorageOk() ([]BrowserStorageOriginRequest, bool) {
	if o == nil || IsNil(o.Storage) {
		return nil, false
	}
	return o.Storage, true
}

// HasStorage returns a boolean if a field has been set.
func (o *BrowserSessionRequest) HasStorage() bool {
	if o != nil && !IsNil(o.Storage) {
		return true
	}

	return false
}

// SetStorage gets a reference to the given []BrowserStorageOriginRequest and assigns it to the Storage field.
func (o *BrowserSessionRequest) SetStorage(v []BrowserStorageOriginRequest) {
	o.Storage = v
}

func (o BrowserSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrowserSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cookies) {
		toSerialize["cookies"] = o.Cookies
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Storage) {
		toSerialize["storage"] = o.Storage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BrowserSessionRequest) UnmarshalJSON(data []byte) (err error) {
	varBrowserSessionRequest := _BrowserSessionRequest{}

	err = json.Unmarshal(data, &varBrowserSessionRequest)

	if err != nil {
		return err
	}

	*o = BrowserSessionRequest(varBrowserSessionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cookies")
		delete(additionalProperties, "headers")
		delete(additionalProperties, "storage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBrowserSessionRequest struct {
	value *BrowserSessionRequest
	isSet bool
}

func (v NullableBrowserSessionRequest) Get() *BrowserSessionRequest {
	return v.value
}

func (v *NullableBrowserSessionRequest) Set(val *BrowserSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBrowserSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBrowserSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrowserSessionRequest(val *BrowserSessionRequest) *NullableBrowserSessionRequest {
	return &NullableBrowserSessionRequest{value: val, isSet: true}
}

func (v NullableBrowserSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrowserSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


