/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the TypeAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypeAction{}

// TypeAction struct for TypeAction
type TypeAction struct {
	Clear *bool `json:"clear,omitempty"`
	Optional *bool `json:"optional,omitempty"`
	Selector string `json:"selector"`
	Text string `json:"text"`
	Timeout NullableInt32 `json:"timeout,omitempty"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _TypeAction TypeAction

// NewTypeAction instantiates a new TypeAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypeAction(selector string, text string, type_ string) *TypeAction {
	this := TypeAction{}
	var clear bool = true
	this.Clear = &clear
	var optional bool = false
	this.Optional = &optional
	this.Selector = selector
	this.Text = text
	this.Type = type_
	return &this
}

// NewTypeActionWithDefaults instantiates a new TypeAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypeActionWithDefaults() *TypeAction {
	this := TypeAction{}
	var clear bool = true
	this.Clear = &clear
	var optional bool = false
	this.Optional = &optional
	return &this
}

// GetClear returns the Clear field value if set, zero value otherwise.
func (o *TypeAction) GetClear() bool {
	if o == nil || IsNil(o.Clear) {
		var ret bool
		return ret
	}
	return *o.Clear
}

// GetClearOk returns a tuple with the Clear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypeAction) GetClearOk() (*bool, bool) {
	if o == nil || IsNil(o.Clear) {
		return nil, false
	}
	return o.Clear, true
}

// HasClear returns a boolean if a field has been set.
func (o *TypeAction) HasClear() bool {
	if o != nil && !IsNil(o.Clear) {
		return true
	}

	return false
}

// SetClear gets a reference to the given bool and assigns it to the Clear field.
func (o *TypeAction) SetClear(v bool) {
	o.Clear = &v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *TypeAction) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TypeAction) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *TypeAction) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *TypeAction) SetOptional(v bool) {
	o.Optional = &v
}

// GetSelector returns the Selector field value
func (o *TypeAction) GetSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value
// and a boolean to check if the value has been set.
func (o *TypeAction) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selector, true
}

// SetSelector sets field value
func (o *TypeAction) SetSelector(v string) {
	o.Selector = v
}

// GetText returns the Text field value
func (o *TypeAction) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *TypeAction) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *TypeAction) SetText(v string) {
	o.Text = v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TypeAction) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout.Get()) {
		var ret int32
		return ret
	}
	return *o.Timeout.Get()
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TypeAction) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeout.Get(), o.Timeout.IsSet()
}

// HasTimeout returns a boolean if a field has been set.
func (o *TypeAction) HasTimeout() bool {
	if o != nil && o.Timeout.IsSet() {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given NullableInt32 and assigns it to the Timeout field.
func (o *TypeAction) SetTimeout(v int32) {
	o.Timeout.Set(&v)
}
// SetTimeoutNil sets the value for Timeout to be an explicit nil
func (o *TypeAction) SetTimeoutNil() {
	o.Timeout.Set(nil)
}

// UnsetTimeout ensures that no value is present for Timeout, not even an explicit nil
func (o *TypeAction) UnsetTimeout() {
	o.Timeout.Unset()
}

// GetType returns the Type field value
func (o *TypeAction) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TypeAction) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TypeAction) SetType(v string) {
	o.Type = v
}

func (o TypeAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypeAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Clear) {
		toSerialize["clear"] = o.Clear
	}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	toSerialize["selector"] = o.Selector
	toSerialize["text"] = o.Text
	if o.Timeout.IsSet() {
		toSerialize["timeout"] = o.Timeout.Get()
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TypeAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selector",
		"text",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTypeAction := _TypeAction{}

	err = json.Unmarshal(data, &varTypeAction)

	if err != nil {
		return err
	}

	*o = TypeAction(varTypeAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "clear")
		delete(additionalProperties, "optional")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "text")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTypeAction struct {
	value *TypeAction
	isSet bool
}

func (v NullableTypeAction) Get() *TypeAction {
	return v.value
}

func (v *NullableTypeAction) Set(val *TypeAction) {
	v.value = val
	v.isSet = true
}

func (v NullableTypeAction) IsSet() bool {
	return v.isSet
}

func (v *NullableTypeAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypeAction(val *TypeAction) *NullableTypeAction {
	return &NullableTypeAction{value: val, isSet: true}
}

func (v NullableTypeAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypeAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


