/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the ScreenshotRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScreenshotRequest{}

// ScreenshotRequest struct for ScreenshotRequest
type ScreenshotRequest struct {
	Actions []PageAction `json:"actions,omitempty"`
	BlockAds *bool `json:"blockAds,omitempty"`
	BlockCookieBanners *bool `json:"blockCookieBanners,omitempty"`
	BlockLevel *string `json:"blockLevel,omitempty" validate:"regexp=^(none|light|normal|pro|pro_plus|ultimate)$"`
	BlockPopups *bool `json:"blockPopups,omitempty"`
	CustomCss NullableString `json:"customCss,omitempty"`
	DarkMode *bool `json:"darkMode,omitempty"`
	Delay *int32 `json:"delay,omitempty"`
	Device NullableString `json:"device,omitempty"`
	Format *string `json:"format,omitempty" validate:"regexp=^(png|jpeg|jpg|webp|pdf)$"`
	FreezeFixed *bool `json:"freezeFixed,omitempty"`
	FullPage *bool `json:"fullPage,omitempty"`
	FullPageMode *string `json:"fullPageMode,omitempty" validate:"regexp=^(native|stitch)$"`
	HideSelectors []string `json:"hideSelectors,omitempty"`
	MaxHeight NullableInt32 `json:"maxHeight,omitempty"`
	MaxSections *int32 `json:"maxSections,omitempty"`
	Outputs []OutputSpec `json:"outputs,omitempty"`
	Quality *int32 `json:"quality,omitempty"`
	ResponseType *string `json:"responseType,omitempty"`
	ScrollInterval *int32 `json:"scrollInterval,omitempty"`
	Selector NullableString `json:"selector,omitempty"`
	Session NullableBrowserSessionRequest `json:"session,omitempty"`
	StealthMode *bool `json:"stealthMode,omitempty"`
	Timeout *int32 `json:"timeout,omitempty"`
	Url string `json:"url" validate:"regexp=^https?://.*"`
	Viewport NullableViewportConfig `json:"viewport,omitempty"`
	WaitFor NullableString `json:"waitFor,omitempty"`
	WaitUntil *string `json:"waitUntil,omitempty" validate:"regexp=^(load|domcontentloaded|networkidle)$"`
	WebhookSecret NullableString `json:"webhookSecret,omitempty"`
	WebhookUrl NullableString `json:"webhookUrl,omitempty" validate:"regexp=^https?://.*"`
	AdditionalProperties map[string]interface{}
}

type _ScreenshotRequest ScreenshotRequest

// NewScreenshotRequest instantiates a new ScreenshotRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenshotRequest(url string) *ScreenshotRequest {
	this := ScreenshotRequest{}
	var blockAds bool = true
	this.BlockAds = &blockAds
	var blockCookieBanners bool = true
	this.BlockCookieBanners = &blockCookieBanners
	var blockLevel string = "none"
	this.BlockLevel = &blockLevel
	var blockPopups bool = true
	this.BlockPopups = &blockPopups
	var darkMode bool = false
	this.DarkMode = &darkMode
	var delay int32 = 0
	this.Delay = &delay
	var format string = "png"
	this.Format = &format
	var freezeFixed bool = true
	this.FreezeFixed = &freezeFixed
	var fullPage bool = false
	this.FullPage = &fullPage
	var fullPageMode string = "stitch"
	this.FullPageMode = &fullPageMode
	var maxSections int32 = 50
	this.MaxSections = &maxSections
	var quality int32 = 80
	this.Quality = &quality
	var responseType string = "BINARY"
	this.ResponseType = &responseType
	var scrollInterval int32 = 150
	this.ScrollInterval = &scrollInterval
	var stealthMode bool = false
	this.StealthMode = &stealthMode
	var timeout int32 = 30000
	this.Timeout = &timeout
	this.Url = url
	var waitUntil string = "domcontentloaded"
	this.WaitUntil = &waitUntil
	return &this
}

// NewScreenshotRequestWithDefaults instantiates a new ScreenshotRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenshotRequestWithDefaults() *ScreenshotRequest {
	this := ScreenshotRequest{}
	var blockAds bool = true
	this.BlockAds = &blockAds
	var blockCookieBanners bool = true
	this.BlockCookieBanners = &blockCookieBanners
	var blockLevel string = "none"
	this.BlockLevel = &blockLevel
	var blockPopups bool = true
	this.BlockPopups = &blockPopups
	var darkMode bool = false
	this.DarkMode = &darkMode
	var delay int32 = 0
	this.Delay = &delay
	var format string = "png"
	this.Format = &format
	var freezeFixed bool = true
	this.FreezeFixed = &freezeFixed
	var fullPage bool = false
	this.FullPage = &fullPage
	var fullPageMode string = "stitch"
	this.FullPageMode = &fullPageMode
	var maxSections int32 = 50
	this.MaxSections = &maxSections
	var quality int32 = 80
	this.Quality = &quality
	var responseType string = "BINARY"
	this.ResponseType = &responseType
	var scrollInterval int32 = 150
	this.ScrollInterval = &scrollInterval
	var stealthMode bool = false
	this.StealthMode = &stealthMode
	var timeout int32 = 30000
	this.Timeout = &timeout
	var waitUntil string = "domcontentloaded"
	this.WaitUntil = &waitUntil
	return &this
}

// GetActions returns the Actions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetActions() []PageAction {
	if o == nil {
		var ret []PageAction
		return ret
	}
	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetActionsOk() ([]PageAction, bool) {
	if o == nil || IsNil(o.Actions) {
		return nil, false
	}
	return o.Actions, true
}

// HasActions returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasActions() bool {
	if o != nil && !IsNil(o.Actions) {
		return true
	}

	return false
}

// SetActions gets a reference to the given []PageAction and assigns it to the Actions field.
func (o *ScreenshotRequest) SetActions(v []PageAction) {
	o.Actions = v
}

// GetBlockAds returns the BlockAds field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetBlockAds() bool {
	if o == nil || IsNil(o.BlockAds) {
		var ret bool
		return ret
	}
	return *o.BlockAds
}

// GetBlockAdsOk returns a tuple with the BlockAds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetBlockAdsOk() (*bool, bool) {
	if o == nil || IsNil(o.BlockAds) {
		return nil, false
	}
	return o.BlockAds, true
}

// HasBlockAds returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasBlockAds() bool {
	if o != nil && !IsNil(o.BlockAds) {
		return true
	}

	return false
}

// SetBlockAds gets a reference to the given bool and assigns it to the BlockAds field.
func (o *ScreenshotRequest) SetBlockAds(v bool) {
	o.BlockAds = &v
}

// GetBlockCookieBanners returns the BlockCookieBanners field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetBlockCookieBanners() bool {
	if o == nil || IsNil(o.BlockCookieBanners) {
		var ret bool
		return ret
	}
	return *o.BlockCookieBanners
}

// GetBlockCookieBannersOk returns a tuple with the BlockCookieBanners field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetBlockCookieBannersOk() (*bool, bool) {
	if o == nil || IsNil(o.BlockCookieBanners) {
		return nil, false
	}
	return o.BlockCookieBanners, true
}

// HasBlockCookieBanners returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasBlockCookieBanners() bool {
	if o != nil && !IsNil(o.BlockCookieBanners) {
		return true
	}

	return false
}

// SetBlockCookieBanners gets a reference to the given bool and assigns it to the BlockCookieBanners field.
func (o *ScreenshotRequest) SetBlockCookieBanners(v bool) {
	o.BlockCookieBanners = &v
}

// GetBlockLevel returns the BlockLevel field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetBlockLevel() string {
	if o == nil || IsNil(o.BlockLevel) {
		var ret string
		return ret
	}
	return *o.BlockLevel
}

// GetBlockLevelOk returns a tuple with the BlockLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetBlockLevelOk() (*string, bool) {
	if o == nil || IsNil(o.BlockLevel) {
		return nil, false
	}
	return o.BlockLevel, true
}

// HasBlockLevel returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasBlockLevel() bool {
	if o != nil && !IsNil(o.BlockLevel) {
		return true
	}

	return false
}

// SetBlockLevel gets a reference to the given string and assigns it to the BlockLevel field.
func (o *ScreenshotRequest) SetBlockLevel(v string) {
	o.BlockLevel = &v
}

// GetBlockPopups returns the BlockPopups field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetBlockPopups() bool {
	if o == nil || IsNil(o.BlockPopups) {
		var ret bool
		return ret
	}
	return *o.BlockPopups
}

// GetBlockPopupsOk returns a tuple with the BlockPopups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetBlockPopupsOk() (*bool, bool) {
	if o == nil || IsNil(o.BlockPopups) {
		return nil, false
	}
	return o.BlockPopups, true
}

// HasBlockPopups returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasBlockPopups() bool {
	if o != nil && !IsNil(o.BlockPopups) {
		return true
	}

	return false
}

// SetBlockPopups gets a reference to the given bool and assigns it to the BlockPopups field.
func (o *ScreenshotRequest) SetBlockPopups(v bool) {
	o.BlockPopups = &v
}

// GetCustomCss returns the CustomCss field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetCustomCss() string {
	if o == nil || IsNil(o.CustomCss.Get()) {
		var ret string
		return ret
	}
	return *o.CustomCss.Get()
}

// GetCustomCssOk returns a tuple with the CustomCss field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetCustomCssOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomCss.Get(), o.CustomCss.IsSet()
}

// HasCustomCss returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasCustomCss() bool {
	if o != nil && o.CustomCss.IsSet() {
		return true
	}

	return false
}

// SetCustomCss gets a reference to the given NullableString and assigns it to the CustomCss field.
func (o *ScreenshotRequest) SetCustomCss(v string) {
	o.CustomCss.Set(&v)
}
// SetCustomCssNil sets the value for CustomCss to be an explicit nil
func (o *ScreenshotRequest) SetCustomCssNil() {
	o.CustomCss.Set(nil)
}

// UnsetCustomCss ensures that no value is present for CustomCss, not even an explicit nil
func (o *ScreenshotRequest) UnsetCustomCss() {
	o.CustomCss.Unset()
}

// GetDarkMode returns the DarkMode field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetDarkMode() bool {
	if o == nil || IsNil(o.DarkMode) {
		var ret bool
		return ret
	}
	return *o.DarkMode
}

// GetDarkModeOk returns a tuple with the DarkMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetDarkModeOk() (*bool, bool) {
	if o == nil || IsNil(o.DarkMode) {
		return nil, false
	}
	return o.DarkMode, true
}

// HasDarkMode returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasDarkMode() bool {
	if o != nil && !IsNil(o.DarkMode) {
		return true
	}

	return false
}

// SetDarkMode gets a reference to the given bool and assigns it to the DarkMode field.
func (o *ScreenshotRequest) SetDarkMode(v bool) {
	o.DarkMode = &v
}

// GetDelay returns the Delay field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetDelay() int32 {
	if o == nil || IsNil(o.Delay) {
		var ret int32
		return ret
	}
	return *o.Delay
}

// GetDelayOk returns a tuple with the Delay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.Delay) {
		return nil, false
	}
	return o.Delay, true
}

// HasDelay returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasDelay() bool {
	if o != nil && !IsNil(o.Delay) {
		return true
	}

	return false
}

// SetDelay gets a reference to the given int32 and assigns it to the Delay field.
func (o *ScreenshotRequest) SetDelay(v int32) {
	o.Delay = &v
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetDevice() string {
	if o == nil || IsNil(o.Device.Get()) {
		var ret string
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableString and assigns it to the Device field.
func (o *ScreenshotRequest) SetDevice(v string) {
	o.Device.Set(&v)
}
// SetDeviceNil sets the value for Device to be an explicit nil
func (o *ScreenshotRequest) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *ScreenshotRequest) UnsetDevice() {
	o.Device.Unset()
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *ScreenshotRequest) SetFormat(v string) {
	o.Format = &v
}

// GetFreezeFixed returns the FreezeFixed field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetFreezeFixed() bool {
	if o == nil || IsNil(o.FreezeFixed) {
		var ret bool
		return ret
	}
	return *o.FreezeFixed
}

// GetFreezeFixedOk returns a tuple with the FreezeFixed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetFreezeFixedOk() (*bool, bool) {
	if o == nil || IsNil(o.FreezeFixed) {
		return nil, false
	}
	return o.FreezeFixed, true
}

// HasFreezeFixed returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasFreezeFixed() bool {
	if o != nil && !IsNil(o.FreezeFixed) {
		return true
	}

	return false
}

// SetFreezeFixed gets a reference to the given bool and assigns it to the FreezeFixed field.
func (o *ScreenshotRequest) SetFreezeFixed(v bool) {
	o.FreezeFixed = &v
}

// GetFullPage returns the FullPage field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetFullPage() bool {
	if o == nil || IsNil(o.FullPage) {
		var ret bool
		return ret
	}
	return *o.FullPage
}

// GetFullPageOk returns a tuple with the FullPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetFullPageOk() (*bool, bool) {
	if o == nil || IsNil(o.FullPage) {
		return nil, false
	}
	return o.FullPage, true
}

// HasFullPage returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasFullPage() bool {
	if o != nil && !IsNil(o.FullPage) {
		return true
	}

	return false
}

// SetFullPage gets a reference to the given bool and assigns it to the FullPage field.
func (o *ScreenshotRequest) SetFullPage(v bool) {
	o.FullPage = &v
}

// GetFullPageMode returns the FullPageMode field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetFullPageMode() string {
	if o == nil || IsNil(o.FullPageMode) {
		var ret string
		return ret
	}
	return *o.FullPageMode
}

// GetFullPageModeOk returns a tuple with the FullPageMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetFullPageModeOk() (*string, bool) {
	if o == nil || IsNil(o.FullPageMode) {
		return nil, false
	}
	return o.FullPageMode, true
}

// HasFullPageMode returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasFullPageMode() bool {
	if o != nil && !IsNil(o.FullPageMode) {
		return true
	}

	return false
}

// SetFullPageMode gets a reference to the given string and assigns it to the FullPageMode field.
func (o *ScreenshotRequest) SetFullPageMode(v string) {
	o.FullPageMode = &v
}

// GetHideSelectors returns the HideSelectors field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetHideSelectors() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.HideSelectors
}

// GetHideSelectorsOk returns a tuple with the HideSelectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetHideSelectorsOk() ([]string, bool) {
	if o == nil || IsNil(o.HideSelectors) {
		return nil, false
	}
	return o.HideSelectors, true
}

// HasHideSelectors returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasHideSelectors() bool {
	if o != nil && !IsNil(o.HideSelectors) {
		return true
	}

	return false
}

// SetHideSelectors gets a reference to the given []string and assigns it to the HideSelectors field.
func (o *ScreenshotRequest) SetHideSelectors(v []string) {
	o.HideSelectors = v
}

// GetMaxHeight returns the MaxHeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetMaxHeight() int32 {
	if o == nil || IsNil(o.MaxHeight.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxHeight.Get()
}

// GetMaxHeightOk returns a tuple with the MaxHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetMaxHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxHeight.Get(), o.MaxHeight.IsSet()
}

// HasMaxHeight returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasMaxHeight() bool {
	if o != nil && o.MaxHeight.IsSet() {
		return true
	}

	return false
}

// SetMaxHeight gets a reference to the given NullableInt32 and assigns it to the MaxHeight field.
func (o *ScreenshotRequest) SetMaxHeight(v int32) {
	o.MaxHeight.Set(&v)
}
// SetMaxHeightNil sets the value for MaxHeight to be an explicit nil
func (o *ScreenshotRequest) SetMaxHeightNil() {
	o.MaxHeight.Set(nil)
}

// UnsetMaxHeight ensures that no value is present for MaxHeight, not even an explicit nil
func (o *ScreenshotRequest) UnsetMaxHeight() {
	o.MaxHeight.Unset()
}

// GetMaxSections returns the MaxSections field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetMaxSections() int32 {
	if o == nil || IsNil(o.MaxSections) {
		var ret int32
		return ret
	}
	return *o.MaxSections
}

// GetMaxSectionsOk returns a tuple with the MaxSections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetMaxSectionsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxSections) {
		return nil, false
	}
	return o.MaxSections, true
}

// HasMaxSections returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasMaxSections() bool {
	if o != nil && !IsNil(o.MaxSections) {
		return true
	}

	return false
}

// SetMaxSections gets a reference to the given int32 and assigns it to the MaxSections field.
func (o *ScreenshotRequest) SetMaxSections(v int32) {
	o.MaxSections = &v
}

// GetOutputs returns the Outputs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetOutputs() []OutputSpec {
	if o == nil {
		var ret []OutputSpec
		return ret
	}
	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetOutputsOk() ([]OutputSpec, bool) {
	if o == nil || IsNil(o.Outputs) {
		return nil, false
	}
	return o.Outputs, true
}

// HasOutputs returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasOutputs() bool {
	if o != nil && !IsNil(o.Outputs) {
		return true
	}

	return false
}

// SetOutputs gets a reference to the given []OutputSpec and assigns it to the Outputs field.
func (o *ScreenshotRequest) SetOutputs(v []OutputSpec) {
	o.Outputs = v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetQuality() int32 {
	if o == nil || IsNil(o.Quality) {
		var ret int32
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetQualityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given int32 and assigns it to the Quality field.
func (o *ScreenshotRequest) SetQuality(v int32) {
	o.Quality = &v
}

// GetResponseType returns the ResponseType field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetResponseType() string {
	if o == nil || IsNil(o.ResponseType) {
		var ret string
		return ret
	}
	return *o.ResponseType
}

// GetResponseTypeOk returns a tuple with the ResponseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetResponseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseType) {
		return nil, false
	}
	return o.ResponseType, true
}

// HasResponseType returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasResponseType() bool {
	if o != nil && !IsNil(o.ResponseType) {
		return true
	}

	return false
}

// SetResponseType gets a reference to the given string and assigns it to the ResponseType field.
func (o *ScreenshotRequest) SetResponseType(v string) {
	o.ResponseType = &v
}

// GetScrollInterval returns the ScrollInterval field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetScrollInterval() int32 {
	if o == nil || IsNil(o.ScrollInterval) {
		var ret int32
		return ret
	}
	return *o.ScrollInterval
}

// GetScrollIntervalOk returns a tuple with the ScrollInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetScrollIntervalOk() (*int32, bool) {
	if o == nil || IsNil(o.ScrollInterval) {
		return nil, false
	}
	return o.ScrollInterval, true
}

// HasScrollInterval returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasScrollInterval() bool {
	if o != nil && !IsNil(o.ScrollInterval) {
		return true
	}

	return false
}

// SetScrollInterval gets a reference to the given int32 and assigns it to the ScrollInterval field.
func (o *ScreenshotRequest) SetScrollInterval(v int32) {
	o.ScrollInterval = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetSelector() string {
	if o == nil || IsNil(o.Selector.Get()) {
		var ret string
		return ret
	}
	return *o.Selector.Get()
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Selector.Get(), o.Selector.IsSet()
}

// HasSelector returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasSelector() bool {
	if o != nil && o.Selector.IsSet() {
		return true
	}

	return false
}

// SetSelector gets a reference to the given NullableString and assigns it to the Selector field.
func (o *ScreenshotRequest) SetSelector(v string) {
	o.Selector.Set(&v)
}
// SetSelectorNil sets the value for Selector to be an explicit nil
func (o *ScreenshotRequest) SetSelectorNil() {
	o.Selector.Set(nil)
}

// UnsetSelector ensures that no value is present for Selector, not even an explicit nil
func (o *ScreenshotRequest) UnsetSelector() {
	o.Selector.Unset()
}

// GetSession returns the Session field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetSession() BrowserSessionRequest {
	if o == nil || IsNil(o.Session.Get()) {
		var ret BrowserSessionRequest
		return ret
	}
	return *o.Session.Get()
}

// GetSessionOk returns a tuple with the Session field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetSessionOk() (*BrowserSessionRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Session.Get(), o.Session.IsSet()
}

// HasSession returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasSession() bool {
	if o != nil && o.Session.IsSet() {
		return true
	}

	return false
}

// SetSession gets a reference to the given NullableBrowserSessionRequest and assigns it to the Session field.
func (o *ScreenshotRequest) SetSession(v BrowserSessionRequest) {
	o.Session.Set(&v)
}
// SetSessionNil sets the value for Session to be an explicit nil
func (o *ScreenshotRequest) SetSessionNil() {
	o.Session.Set(nil)
}

// UnsetSession ensures that no value is present for Session, not even an explicit nil
func (o *ScreenshotRequest) UnsetSession() {
	o.Session.Unset()
}

// GetStealthMode returns the StealthMode field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetStealthMode() bool {
	if o == nil || IsNil(o.StealthMode) {
		var ret bool
		return ret
	}
	return *o.StealthMode
}

// GetStealthModeOk returns a tuple with the StealthMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetStealthModeOk() (*bool, bool) {
	if o == nil || IsNil(o.StealthMode) {
		return nil, false
	}
	return o.StealthMode, true
}

// HasStealthMode returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasStealthMode() bool {
	if o != nil && !IsNil(o.StealthMode) {
		return true
	}

	return false
}

// SetStealthMode gets a reference to the given bool and assigns it to the StealthMode field.
func (o *ScreenshotRequest) SetStealthMode(v bool) {
	o.StealthMode = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *ScreenshotRequest) SetTimeout(v int32) {
	o.Timeout = &v
}

// GetUrl returns the Url field value
func (o *ScreenshotRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ScreenshotRequest) SetUrl(v string) {
	o.Url = v
}

// GetViewport returns the Viewport field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetViewport() ViewportConfig {
	if o == nil || IsNil(o.Viewport.Get()) {
		var ret ViewportConfig
		return ret
	}
	return *o.Viewport.Get()
}

// GetViewportOk returns a tuple with the Viewport field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetViewportOk() (*ViewportConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Viewport.Get(), o.Viewport.IsSet()
}

// HasViewport returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasViewport() bool {
	if o != nil && o.Viewport.IsSet() {
		return true
	}

	return false
}

// SetViewport gets a reference to the given NullableViewportConfig and assigns it to the Viewport field.
func (o *ScreenshotRequest) SetViewport(v ViewportConfig) {
	o.Viewport.Set(&v)
}
// SetViewportNil sets the value for Viewport to be an explicit nil
func (o *ScreenshotRequest) SetViewportNil() {
	o.Viewport.Set(nil)
}

// UnsetViewport ensures that no value is present for Viewport, not even an explicit nil
func (o *ScreenshotRequest) UnsetViewport() {
	o.Viewport.Unset()
}

// GetWaitFor returns the WaitFor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetWaitFor() string {
	if o == nil || IsNil(o.WaitFor.Get()) {
		var ret string
		return ret
	}
	return *o.WaitFor.Get()
}

// GetWaitForOk returns a tuple with the WaitFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetWaitForOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WaitFor.Get(), o.WaitFor.IsSet()
}

// HasWaitFor returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasWaitFor() bool {
	if o != nil && o.WaitFor.IsSet() {
		return true
	}

	return false
}

// SetWaitFor gets a reference to the given NullableString and assigns it to the WaitFor field.
func (o *ScreenshotRequest) SetWaitFor(v string) {
	o.WaitFor.Set(&v)
}
// SetWaitForNil sets the value for WaitFor to be an explicit nil
func (o *ScreenshotRequest) SetWaitForNil() {
	o.WaitFor.Set(nil)
}

// UnsetWaitFor ensures that no value is present for WaitFor, not even an explicit nil
func (o *ScreenshotRequest) UnsetWaitFor() {
	o.WaitFor.Unset()
}

// GetWaitUntil returns the WaitUntil field value if set, zero value otherwise.
func (o *ScreenshotRequest) GetWaitUntil() string {
	if o == nil || IsNil(o.WaitUntil) {
		var ret string
		return ret
	}
	return *o.WaitUntil
}

// GetWaitUntilOk returns a tuple with the WaitUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotRequest) GetWaitUntilOk() (*string, bool) {
	if o == nil || IsNil(o.WaitUntil) {
		return nil, false
	}
	return o.WaitUntil, true
}

// HasWaitUntil returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasWaitUntil() bool {
	if o != nil && !IsNil(o.WaitUntil) {
		return true
	}

	return false
}

// SetWaitUntil gets a reference to the given string and assigns it to the WaitUntil field.
func (o *ScreenshotRequest) SetWaitUntil(v string) {
	o.WaitUntil = &v
}

// GetWebhookSecret returns the WebhookSecret field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetWebhookSecret() string {
	if o == nil || IsNil(o.WebhookSecret.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookSecret.Get()
}

// GetWebhookSecretOk returns a tuple with the WebhookSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetWebhookSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookSecret.Get(), o.WebhookSecret.IsSet()
}

// HasWebhookSecret returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasWebhookSecret() bool {
	if o != nil && o.WebhookSecret.IsSet() {
		return true
	}

	return false
}

// SetWebhookSecret gets a reference to the given NullableString and assigns it to the WebhookSecret field.
func (o *ScreenshotRequest) SetWebhookSecret(v string) {
	o.WebhookSecret.Set(&v)
}
// SetWebhookSecretNil sets the value for WebhookSecret to be an explicit nil
func (o *ScreenshotRequest) SetWebhookSecretNil() {
	o.WebhookSecret.Set(nil)
}

// UnsetWebhookSecret ensures that no value is present for WebhookSecret, not even an explicit nil
func (o *ScreenshotRequest) UnsetWebhookSecret() {
	o.WebhookSecret.Unset()
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotRequest) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookUrl.Get()
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotRequest) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookUrl.Get(), o.WebhookUrl.IsSet()
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *ScreenshotRequest) HasWebhookUrl() bool {
	if o != nil && o.WebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given NullableString and assigns it to the WebhookUrl field.
func (o *ScreenshotRequest) SetWebhookUrl(v string) {
	o.WebhookUrl.Set(&v)
}
// SetWebhookUrlNil sets the value for WebhookUrl to be an explicit nil
func (o *ScreenshotRequest) SetWebhookUrlNil() {
	o.WebhookUrl.Set(nil)
}

// UnsetWebhookUrl ensures that no value is present for WebhookUrl, not even an explicit nil
func (o *ScreenshotRequest) UnsetWebhookUrl() {
	o.WebhookUrl.Unset()
}

func (o ScreenshotRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScreenshotRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Actions != nil {
		toSerialize["actions"] = o.Actions
	}
	if !IsNil(o.BlockAds) {
		toSerialize["blockAds"] = o.BlockAds
	}
	if !IsNil(o.BlockCookieBanners) {
		toSerialize["blockCookieBanners"] = o.BlockCookieBanners
	}
	if !IsNil(o.BlockLevel) {
		toSerialize["blockLevel"] = o.BlockLevel
	}
	if !IsNil(o.BlockPopups) {
		toSerialize["blockPopups"] = o.BlockPopups
	}
	if o.CustomCss.IsSet() {
		toSerialize["customCss"] = o.CustomCss.Get()
	}
	if !IsNil(o.DarkMode) {
		toSerialize["darkMode"] = o.DarkMode
	}
	if !IsNil(o.Delay) {
		toSerialize["delay"] = o.Delay
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.FreezeFixed) {
		toSerialize["freezeFixed"] = o.FreezeFixed
	}
	if !IsNil(o.FullPage) {
		toSerialize["fullPage"] = o.FullPage
	}
	if !IsNil(o.FullPageMode) {
		toSerialize["fullPageMode"] = o.FullPageMode
	}
	if o.HideSelectors != nil {
		toSerialize["hideSelectors"] = o.HideSelectors
	}
	if o.MaxHeight.IsSet() {
		toSerialize["maxHeight"] = o.MaxHeight.Get()
	}
	if !IsNil(o.MaxSections) {
		toSerialize["maxSections"] = o.MaxSections
	}
	if o.Outputs != nil {
		toSerialize["outputs"] = o.Outputs
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	if !IsNil(o.ResponseType) {
		toSerialize["responseType"] = o.ResponseType
	}
	if !IsNil(o.ScrollInterval) {
		toSerialize["scrollInterval"] = o.ScrollInterval
	}
	if o.Selector.IsSet() {
		toSerialize["selector"] = o.Selector.Get()
	}
	if o.Session.IsSet() {
		toSerialize["session"] = o.Session.Get()
	}
	if !IsNil(o.StealthMode) {
		toSerialize["stealthMode"] = o.StealthMode
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	toSerialize["url"] = o.Url
	if o.Viewport.IsSet() {
		toSerialize["viewport"] = o.Viewport.Get()
	}
	if o.WaitFor.IsSet() {
		toSerialize["waitFor"] = o.WaitFor.Get()
	}
	if !IsNil(o.WaitUntil) {
		toSerialize["waitUntil"] = o.WaitUntil
	}
	if o.WebhookSecret.IsSet() {
		toSerialize["webhookSecret"] = o.WebhookSecret.Get()
	}
	if o.WebhookUrl.IsSet() {
		toSerialize["webhookUrl"] = o.WebhookUrl.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScreenshotRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScreenshotRequest := _ScreenshotRequest{}

	err = json.Unmarshal(data, &varScreenshotRequest)

	if err != nil {
		return err
	}

	*o = ScreenshotRequest(varScreenshotRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "actions")
		delete(additionalProperties, "blockAds")
		delete(additionalProperties, "blockCookieBanners")
		delete(additionalProperties, "blockLevel")
		delete(additionalProperties, "blockPopups")
		delete(additionalProperties, "customCss")
		delete(additionalProperties, "darkMode")
		delete(additionalProperties, "delay")
		delete(additionalProperties, "device")
		delete(additionalProperties, "format")
		delete(additionalProperties, "freezeFixed")
		delete(additionalProperties, "fullPage")
		delete(additionalProperties, "fullPageMode")
		delete(additionalProperties, "hideSelectors")
		delete(additionalProperties, "maxHeight")
		delete(additionalProperties, "maxSections")
		delete(additionalProperties, "outputs")
		delete(additionalProperties, "quality")
		delete(additionalProperties, "responseType")
		delete(additionalProperties, "scrollInterval")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "session")
		delete(additionalProperties, "stealthMode")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "url")
		delete(additionalProperties, "viewport")
		delete(additionalProperties, "waitFor")
		delete(additionalProperties, "waitUntil")
		delete(additionalProperties, "webhookSecret")
		delete(additionalProperties, "webhookUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScreenshotRequest struct {
	value *ScreenshotRequest
	isSet bool
}

func (v NullableScreenshotRequest) Get() *ScreenshotRequest {
	return v.value
}

func (v *NullableScreenshotRequest) Set(val *ScreenshotRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenshotRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenshotRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenshotRequest(val *ScreenshotRequest) *NullableScreenshotRequest {
	return &NullableScreenshotRequest{value: val, isSet: true}
}

func (v NullableScreenshotRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenshotRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


