/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the JsonFieldSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JsonFieldSpec{}

// JsonFieldSpec struct for JsonFieldSpec
type JsonFieldSpec struct {
	Attribute NullableString `json:"attribute,omitempty"`
	Multiple *bool `json:"multiple,omitempty"`
	Selector string `json:"selector"`
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _JsonFieldSpec JsonFieldSpec

// NewJsonFieldSpec instantiates a new JsonFieldSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJsonFieldSpec(selector string) *JsonFieldSpec {
	this := JsonFieldSpec{}
	var multiple bool = false
	this.Multiple = &multiple
	this.Selector = selector
	var type_ string = "text"
	this.Type = &type_
	return &this
}

// NewJsonFieldSpecWithDefaults instantiates a new JsonFieldSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJsonFieldSpecWithDefaults() *JsonFieldSpec {
	this := JsonFieldSpec{}
	var multiple bool = false
	this.Multiple = &multiple
	var type_ string = "text"
	this.Type = &type_
	return &this
}

// GetAttribute returns the Attribute field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JsonFieldSpec) GetAttribute() string {
	if o == nil || IsNil(o.Attribute.Get()) {
		var ret string
		return ret
	}
	return *o.Attribute.Get()
}

// GetAttributeOk returns a tuple with the Attribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JsonFieldSpec) GetAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Attribute.Get(), o.Attribute.IsSet()
}

// HasAttribute returns a boolean if a field has been set.
func (o *JsonFieldSpec) HasAttribute() bool {
	if o != nil && o.Attribute.IsSet() {
		return true
	}

	return false
}

// SetAttribute gets a reference to the given NullableString and assigns it to the Attribute field.
func (o *JsonFieldSpec) SetAttribute(v string) {
	o.Attribute.Set(&v)
}
// SetAttributeNil sets the value for Attribute to be an explicit nil
func (o *JsonFieldSpec) SetAttributeNil() {
	o.Attribute.Set(nil)
}

// UnsetAttribute ensures that no value is present for Attribute, not even an explicit nil
func (o *JsonFieldSpec) UnsetAttribute() {
	o.Attribute.Unset()
}

// GetMultiple returns the Multiple field value if set, zero value otherwise.
func (o *JsonFieldSpec) GetMultiple() bool {
	if o == nil || IsNil(o.Multiple) {
		var ret bool
		return ret
	}
	return *o.Multiple
}

// GetMultipleOk returns a tuple with the Multiple field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonFieldSpec) GetMultipleOk() (*bool, bool) {
	if o == nil || IsNil(o.Multiple) {
		return nil, false
	}
	return o.Multiple, true
}

// HasMultiple returns a boolean if a field has been set.
func (o *JsonFieldSpec) HasMultiple() bool {
	if o != nil && !IsNil(o.Multiple) {
		return true
	}

	return false
}

// SetMultiple gets a reference to the given bool and assigns it to the Multiple field.
func (o *JsonFieldSpec) SetMultiple(v bool) {
	o.Multiple = &v
}

// GetSelector returns the Selector field value
func (o *JsonFieldSpec) GetSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Selector
}

// GetSelectorOk returns a tuple with the Selector field value
// and a boolean to check if the value has been set.
func (o *JsonFieldSpec) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Selector, true
}

// SetSelector sets field value
func (o *JsonFieldSpec) SetSelector(v string) {
	o.Selector = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *JsonFieldSpec) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JsonFieldSpec) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *JsonFieldSpec) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *JsonFieldSpec) SetType(v string) {
	o.Type = &v
}

func (o JsonFieldSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JsonFieldSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Attribute.IsSet() {
		toSerialize["attribute"] = o.Attribute.Get()
	}
	if !IsNil(o.Multiple) {
		toSerialize["multiple"] = o.Multiple
	}
	toSerialize["selector"] = o.Selector
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *JsonFieldSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"selector",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJsonFieldSpec := _JsonFieldSpec{}

	err = json.Unmarshal(data, &varJsonFieldSpec)

	if err != nil {
		return err
	}

	*o = JsonFieldSpec(varJsonFieldSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute")
		delete(additionalProperties, "multiple")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableJsonFieldSpec struct {
	value *JsonFieldSpec
	isSet bool
}

func (v NullableJsonFieldSpec) Get() *JsonFieldSpec {
	return v.value
}

func (v *NullableJsonFieldSpec) Set(val *JsonFieldSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableJsonFieldSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableJsonFieldSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJsonFieldSpec(val *JsonFieldSpec) *NullableJsonFieldSpec {
	return &NullableJsonFieldSpec{value: val, isSet: true}
}

func (v NullableJsonFieldSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJsonFieldSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


