/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the CrawlCreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrawlCreatedResponse{}

// CrawlCreatedResponse struct for CrawlCreatedResponse
type CrawlCreatedResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Id string `json:"id"`
	Status string `json:"status"`
	StatusUrl string `json:"statusUrl"`
	AdditionalProperties map[string]interface{}
}

type _CrawlCreatedResponse CrawlCreatedResponse

// NewCrawlCreatedResponse instantiates a new CrawlCreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrawlCreatedResponse(createdAt time.Time, id string, status string, statusUrl string) *CrawlCreatedResponse {
	this := CrawlCreatedResponse{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Status = status
	this.StatusUrl = statusUrl
	return &this
}

// NewCrawlCreatedResponseWithDefaults instantiates a new CrawlCreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrawlCreatedResponseWithDefaults() *CrawlCreatedResponse {
	this := CrawlCreatedResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *CrawlCreatedResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CrawlCreatedResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CrawlCreatedResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *CrawlCreatedResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CrawlCreatedResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CrawlCreatedResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *CrawlCreatedResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CrawlCreatedResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CrawlCreatedResponse) SetStatus(v string) {
	o.Status = v
}

// GetStatusUrl returns the StatusUrl field value
func (o *CrawlCreatedResponse) GetStatusUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusUrl
}

// GetStatusUrlOk returns a tuple with the StatusUrl field value
// and a boolean to check if the value has been set.
func (o *CrawlCreatedResponse) GetStatusUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusUrl, true
}

// SetStatusUrl sets field value
func (o *CrawlCreatedResponse) SetStatusUrl(v string) {
	o.StatusUrl = v
}

func (o CrawlCreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrawlCreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["statusUrl"] = o.StatusUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CrawlCreatedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"id",
		"status",
		"statusUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCrawlCreatedResponse := _CrawlCreatedResponse{}

	err = json.Unmarshal(data, &varCrawlCreatedResponse)

	if err != nil {
		return err
	}

	*o = CrawlCreatedResponse(varCrawlCreatedResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "statusUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCrawlCreatedResponse struct {
	value *CrawlCreatedResponse
	isSet bool
}

func (v NullableCrawlCreatedResponse) Get() *CrawlCreatedResponse {
	return v.value
}

func (v *NullableCrawlCreatedResponse) Set(val *CrawlCreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCrawlCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCrawlCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrawlCreatedResponse(val *CrawlCreatedResponse) *NullableCrawlCreatedResponse {
	return &NullableCrawlCreatedResponse{value: val, isSet: true}
}

func (v NullableCrawlCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrawlCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


