/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
)

// checks if the LabelConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabelConfig{}

// LabelConfig struct for LabelConfig
type LabelConfig struct {
	Background *string `json:"background,omitempty"`
	FontColor *string `json:"fontColor,omitempty"`
	FontSize *int32 `json:"fontSize,omitempty"`
	Padding *int32 `json:"padding,omitempty"`
	Position *string `json:"position,omitempty" validate:"regexp=^(top|bottom)$"`
	Show *bool `json:"show,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LabelConfig LabelConfig

// NewLabelConfig instantiates a new LabelConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabelConfig() *LabelConfig {
	this := LabelConfig{}
	var background string = "#ffffff"
	this.Background = &background
	var fontColor string = "#333333"
	this.FontColor = &fontColor
	var fontSize int32 = 14
	this.FontSize = &fontSize
	var padding int32 = 8
	this.Padding = &padding
	var position string = "bottom"
	this.Position = &position
	var show bool = true
	this.Show = &show
	return &this
}

// NewLabelConfigWithDefaults instantiates a new LabelConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabelConfigWithDefaults() *LabelConfig {
	this := LabelConfig{}
	var background string = "#ffffff"
	this.Background = &background
	var fontColor string = "#333333"
	this.FontColor = &fontColor
	var fontSize int32 = 14
	this.FontSize = &fontSize
	var padding int32 = 8
	this.Padding = &padding
	var position string = "bottom"
	this.Position = &position
	var show bool = true
	this.Show = &show
	return &this
}

// GetBackground returns the Background field value if set, zero value otherwise.
func (o *LabelConfig) GetBackground() string {
	if o == nil || IsNil(o.Background) {
		var ret string
		return ret
	}
	return *o.Background
}

// GetBackgroundOk returns a tuple with the Background field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelConfig) GetBackgroundOk() (*string, bool) {
	if o == nil || IsNil(o.Background) {
		return nil, false
	}
	return o.Background, true
}

// HasBackground returns a boolean if a field has been set.
func (o *LabelConfig) HasBackground() bool {
	if o != nil && !IsNil(o.Background) {
		return true
	}

	return false
}

// SetBackground gets a reference to the given string and assigns it to the Background field.
func (o *LabelConfig) SetBackground(v string) {
	o.Background = &v
}

// GetFontColor returns the FontColor field value if set, zero value otherwise.
func (o *LabelConfig) GetFontColor() string {
	if o == nil || IsNil(o.FontColor) {
		var ret string
		return ret
	}
	return *o.FontColor
}

// GetFontColorOk returns a tuple with the FontColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelConfig) GetFontColorOk() (*string, bool) {
	if o == nil || IsNil(o.FontColor) {
		return nil, false
	}
	return o.FontColor, true
}

// HasFontColor returns a boolean if a field has been set.
func (o *LabelConfig) HasFontColor() bool {
	if o != nil && !IsNil(o.FontColor) {
		return true
	}

	return false
}

// SetFontColor gets a reference to the given string and assigns it to the FontColor field.
func (o *LabelConfig) SetFontColor(v string) {
	o.FontColor = &v
}

// GetFontSize returns the FontSize field value if set, zero value otherwise.
func (o *LabelConfig) GetFontSize() int32 {
	if o == nil || IsNil(o.FontSize) {
		var ret int32
		return ret
	}
	return *o.FontSize
}

// GetFontSizeOk returns a tuple with the FontSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelConfig) GetFontSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.FontSize) {
		return nil, false
	}
	return o.FontSize, true
}

// HasFontSize returns a boolean if a field has been set.
func (o *LabelConfig) HasFontSize() bool {
	if o != nil && !IsNil(o.FontSize) {
		return true
	}

	return false
}

// SetFontSize gets a reference to the given int32 and assigns it to the FontSize field.
func (o *LabelConfig) SetFontSize(v int32) {
	o.FontSize = &v
}

// GetPadding returns the Padding field value if set, zero value otherwise.
func (o *LabelConfig) GetPadding() int32 {
	if o == nil || IsNil(o.Padding) {
		var ret int32
		return ret
	}
	return *o.Padding
}

// GetPaddingOk returns a tuple with the Padding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelConfig) GetPaddingOk() (*int32, bool) {
	if o == nil || IsNil(o.Padding) {
		return nil, false
	}
	return o.Padding, true
}

// HasPadding returns a boolean if a field has been set.
func (o *LabelConfig) HasPadding() bool {
	if o != nil && !IsNil(o.Padding) {
		return true
	}

	return false
}

// SetPadding gets a reference to the given int32 and assigns it to the Padding field.
func (o *LabelConfig) SetPadding(v int32) {
	o.Padding = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *LabelConfig) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelConfig) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *LabelConfig) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *LabelConfig) SetPosition(v string) {
	o.Position = &v
}

// GetShow returns the Show field value if set, zero value otherwise.
func (o *LabelConfig) GetShow() bool {
	if o == nil || IsNil(o.Show) {
		var ret bool
		return ret
	}
	return *o.Show
}

// GetShowOk returns a tuple with the Show field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabelConfig) GetShowOk() (*bool, bool) {
	if o == nil || IsNil(o.Show) {
		return nil, false
	}
	return o.Show, true
}

// HasShow returns a boolean if a field has been set.
func (o *LabelConfig) HasShow() bool {
	if o != nil && !IsNil(o.Show) {
		return true
	}

	return false
}

// SetShow gets a reference to the given bool and assigns it to the Show field.
func (o *LabelConfig) SetShow(v bool) {
	o.Show = &v
}

func (o LabelConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabelConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Background) {
		toSerialize["background"] = o.Background
	}
	if !IsNil(o.FontColor) {
		toSerialize["fontColor"] = o.FontColor
	}
	if !IsNil(o.FontSize) {
		toSerialize["fontSize"] = o.FontSize
	}
	if !IsNil(o.Padding) {
		toSerialize["padding"] = o.Padding
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Show) {
		toSerialize["show"] = o.Show
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LabelConfig) UnmarshalJSON(data []byte) (err error) {
	varLabelConfig := _LabelConfig{}

	err = json.Unmarshal(data, &varLabelConfig)

	if err != nil {
		return err
	}

	*o = LabelConfig(varLabelConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "background")
		delete(additionalProperties, "fontColor")
		delete(additionalProperties, "fontSize")
		delete(additionalProperties, "padding")
		delete(additionalProperties, "position")
		delete(additionalProperties, "show")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLabelConfig struct {
	value *LabelConfig
	isSet bool
}

func (v NullableLabelConfig) Get() *LabelConfig {
	return v.value
}

func (v *NullableLabelConfig) Set(val *LabelConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableLabelConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableLabelConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabelConfig(val *LabelConfig) *NullableLabelConfig {
	return &NullableLabelConfig{value: val, isSet: true}
}

func (v NullableLabelConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabelConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


