/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the BrowserCookieRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrowserCookieRequest{}

// BrowserCookieRequest struct for BrowserCookieRequest
type BrowserCookieRequest struct {
	Domain NullableString `json:"domain,omitempty"`
	Expires NullableFloat64 `json:"expires,omitempty"`
	HttpOnly NullableBool `json:"httpOnly,omitempty"`
	Name string `json:"name"`
	Path NullableString `json:"path,omitempty"`
	SameSite NullableString `json:"sameSite,omitempty" validate:"regexp=^(strict|lax|none|no_restriction|unspecified)$"`
	Secure NullableBool `json:"secure,omitempty"`
	Value *string `json:"value,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BrowserCookieRequest BrowserCookieRequest

// NewBrowserCookieRequest instantiates a new BrowserCookieRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrowserCookieRequest(name string) *BrowserCookieRequest {
	this := BrowserCookieRequest{}
	this.Name = name
	var path string = "/"
	this.Path = *NewNullableString(&path)
	var value string = ""
	this.Value = &value
	return &this
}

// NewBrowserCookieRequestWithDefaults instantiates a new BrowserCookieRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrowserCookieRequestWithDefaults() *BrowserCookieRequest {
	this := BrowserCookieRequest{}
	var path string = "/"
	this.Path = *NewNullableString(&path)
	var value string = ""
	this.Value = &value
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrowserCookieRequest) GetDomain() string {
	if o == nil || IsNil(o.Domain.Get()) {
		var ret string
		return ret
	}
	return *o.Domain.Get()
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrowserCookieRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain.Get(), o.Domain.IsSet()
}

// HasDomain returns a boolean if a field has been set.
func (o *BrowserCookieRequest) HasDomain() bool {
	if o != nil && o.Domain.IsSet() {
		return true
	}

	return false
}

// SetDomain gets a reference to the given NullableString and assigns it to the Domain field.
func (o *BrowserCookieRequest) SetDomain(v string) {
	o.Domain.Set(&v)
}
// SetDomainNil sets the value for Domain to be an explicit nil
func (o *BrowserCookieRequest) SetDomainNil() {
	o.Domain.Set(nil)
}

// UnsetDomain ensures that no value is present for Domain, not even an explicit nil
func (o *BrowserCookieRequest) UnsetDomain() {
	o.Domain.Unset()
}

// GetExpires returns the Expires field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrowserCookieRequest) GetExpires() float64 {
	if o == nil || IsNil(o.Expires.Get()) {
		var ret float64
		return ret
	}
	return *o.Expires.Get()
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrowserCookieRequest) GetExpiresOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Expires.Get(), o.Expires.IsSet()
}

// HasExpires returns a boolean if a field has been set.
func (o *BrowserCookieRequest) HasExpires() bool {
	if o != nil && o.Expires.IsSet() {
		return true
	}

	return false
}

// SetExpires gets a reference to the given NullableFloat64 and assigns it to the Expires field.
func (o *BrowserCookieRequest) SetExpires(v float64) {
	o.Expires.Set(&v)
}
// SetExpiresNil sets the value for Expires to be an explicit nil
func (o *BrowserCookieRequest) SetExpiresNil() {
	o.Expires.Set(nil)
}

// UnsetExpires ensures that no value is present for Expires, not even an explicit nil
func (o *BrowserCookieRequest) UnsetExpires() {
	o.Expires.Unset()
}

// GetHttpOnly returns the HttpOnly field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrowserCookieRequest) GetHttpOnly() bool {
	if o == nil || IsNil(o.HttpOnly.Get()) {
		var ret bool
		return ret
	}
	return *o.HttpOnly.Get()
}

// GetHttpOnlyOk returns a tuple with the HttpOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrowserCookieRequest) GetHttpOnlyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.HttpOnly.Get(), o.HttpOnly.IsSet()
}

// HasHttpOnly returns a boolean if a field has been set.
func (o *BrowserCookieRequest) HasHttpOnly() bool {
	if o != nil && o.HttpOnly.IsSet() {
		return true
	}

	return false
}

// SetHttpOnly gets a reference to the given NullableBool and assigns it to the HttpOnly field.
func (o *BrowserCookieRequest) SetHttpOnly(v bool) {
	o.HttpOnly.Set(&v)
}
// SetHttpOnlyNil sets the value for HttpOnly to be an explicit nil
func (o *BrowserCookieRequest) SetHttpOnlyNil() {
	o.HttpOnly.Set(nil)
}

// UnsetHttpOnly ensures that no value is present for HttpOnly, not even an explicit nil
func (o *BrowserCookieRequest) UnsetHttpOnly() {
	o.HttpOnly.Unset()
}

// GetName returns the Name field value
func (o *BrowserCookieRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BrowserCookieRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BrowserCookieRequest) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrowserCookieRequest) GetPath() string {
	if o == nil || IsNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrowserCookieRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *BrowserCookieRequest) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *BrowserCookieRequest) SetPath(v string) {
	o.Path.Set(&v)
}
// SetPathNil sets the value for Path to be an explicit nil
func (o *BrowserCookieRequest) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *BrowserCookieRequest) UnsetPath() {
	o.Path.Unset()
}

// GetSameSite returns the SameSite field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrowserCookieRequest) GetSameSite() string {
	if o == nil || IsNil(o.SameSite.Get()) {
		var ret string
		return ret
	}
	return *o.SameSite.Get()
}

// GetSameSiteOk returns a tuple with the SameSite field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrowserCookieRequest) GetSameSiteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SameSite.Get(), o.SameSite.IsSet()
}

// HasSameSite returns a boolean if a field has been set.
func (o *BrowserCookieRequest) HasSameSite() bool {
	if o != nil && o.SameSite.IsSet() {
		return true
	}

	return false
}

// SetSameSite gets a reference to the given NullableString and assigns it to the SameSite field.
func (o *BrowserCookieRequest) SetSameSite(v string) {
	o.SameSite.Set(&v)
}
// SetSameSiteNil sets the value for SameSite to be an explicit nil
func (o *BrowserCookieRequest) SetSameSiteNil() {
	o.SameSite.Set(nil)
}

// UnsetSameSite ensures that no value is present for SameSite, not even an explicit nil
func (o *BrowserCookieRequest) UnsetSameSite() {
	o.SameSite.Unset()
}

// GetSecure returns the Secure field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BrowserCookieRequest) GetSecure() bool {
	if o == nil || IsNil(o.Secure.Get()) {
		var ret bool
		return ret
	}
	return *o.Secure.Get()
}

// GetSecureOk returns a tuple with the Secure field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BrowserCookieRequest) GetSecureOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Secure.Get(), o.Secure.IsSet()
}

// HasSecure returns a boolean if a field has been set.
func (o *BrowserCookieRequest) HasSecure() bool {
	if o != nil && o.Secure.IsSet() {
		return true
	}

	return false
}

// SetSecure gets a reference to the given NullableBool and assigns it to the Secure field.
func (o *BrowserCookieRequest) SetSecure(v bool) {
	o.Secure.Set(&v)
}
// SetSecureNil sets the value for Secure to be an explicit nil
func (o *BrowserCookieRequest) SetSecureNil() {
	o.Secure.Set(nil)
}

// UnsetSecure ensures that no value is present for Secure, not even an explicit nil
func (o *BrowserCookieRequest) UnsetSecure() {
	o.Secure.Unset()
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *BrowserCookieRequest) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrowserCookieRequest) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *BrowserCookieRequest) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *BrowserCookieRequest) SetValue(v string) {
	o.Value = &v
}

func (o BrowserCookieRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrowserCookieRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Domain.IsSet() {
		toSerialize["domain"] = o.Domain.Get()
	}
	if o.Expires.IsSet() {
		toSerialize["expires"] = o.Expires.Get()
	}
	if o.HttpOnly.IsSet() {
		toSerialize["httpOnly"] = o.HttpOnly.Get()
	}
	toSerialize["name"] = o.Name
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if o.SameSite.IsSet() {
		toSerialize["sameSite"] = o.SameSite.Get()
	}
	if o.Secure.IsSet() {
		toSerialize["secure"] = o.Secure.Get()
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BrowserCookieRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBrowserCookieRequest := _BrowserCookieRequest{}

	err = json.Unmarshal(data, &varBrowserCookieRequest)

	if err != nil {
		return err
	}

	*o = BrowserCookieRequest(varBrowserCookieRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "domain")
		delete(additionalProperties, "expires")
		delete(additionalProperties, "httpOnly")
		delete(additionalProperties, "name")
		delete(additionalProperties, "path")
		delete(additionalProperties, "sameSite")
		delete(additionalProperties, "secure")
		delete(additionalProperties, "value")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBrowserCookieRequest struct {
	value *BrowserCookieRequest
	isSet bool
}

func (v NullableBrowserCookieRequest) Get() *BrowserCookieRequest {
	return v.value
}

func (v *NullableBrowserCookieRequest) Set(val *BrowserCookieRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBrowserCookieRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBrowserCookieRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrowserCookieRequest(val *BrowserCookieRequest) *NullableBrowserCookieRequest {
	return &NullableBrowserCookieRequest{value: val, isSet: true}
}

func (v NullableBrowserCookieRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrowserCookieRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


