/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the PdfOutputSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PdfOutputSpec{}

// PdfOutputSpec struct for PdfOutputSpec
type PdfOutputSpec struct {
	Format NullableString `json:"format,omitempty"`
	Id NullableString `json:"id,omitempty"`
	Landscape *bool `json:"landscape,omitempty"`
	PrintBackground *bool `json:"printBackground,omitempty"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _PdfOutputSpec PdfOutputSpec

// NewPdfOutputSpec instantiates a new PdfOutputSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPdfOutputSpec(type_ string) *PdfOutputSpec {
	this := PdfOutputSpec{}
	var landscape bool = false
	this.Landscape = &landscape
	var printBackground bool = true
	this.PrintBackground = &printBackground
	this.Type = type_
	return &this
}

// NewPdfOutputSpecWithDefaults instantiates a new PdfOutputSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPdfOutputSpecWithDefaults() *PdfOutputSpec {
	this := PdfOutputSpec{}
	var landscape bool = false
	this.Landscape = &landscape
	var printBackground bool = true
	this.PrintBackground = &printBackground
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PdfOutputSpec) GetFormat() string {
	if o == nil || IsNil(o.Format.Get()) {
		var ret string
		return ret
	}
	return *o.Format.Get()
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdfOutputSpec) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Format.Get(), o.Format.IsSet()
}

// HasFormat returns a boolean if a field has been set.
func (o *PdfOutputSpec) HasFormat() bool {
	if o != nil && o.Format.IsSet() {
		return true
	}

	return false
}

// SetFormat gets a reference to the given NullableString and assigns it to the Format field.
func (o *PdfOutputSpec) SetFormat(v string) {
	o.Format.Set(&v)
}
// SetFormatNil sets the value for Format to be an explicit nil
func (o *PdfOutputSpec) SetFormatNil() {
	o.Format.Set(nil)
}

// UnsetFormat ensures that no value is present for Format, not even an explicit nil
func (o *PdfOutputSpec) UnsetFormat() {
	o.Format.Unset()
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PdfOutputSpec) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PdfOutputSpec) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *PdfOutputSpec) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *PdfOutputSpec) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *PdfOutputSpec) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *PdfOutputSpec) UnsetId() {
	o.Id.Unset()
}

// GetLandscape returns the Landscape field value if set, zero value otherwise.
func (o *PdfOutputSpec) GetLandscape() bool {
	if o == nil || IsNil(o.Landscape) {
		var ret bool
		return ret
	}
	return *o.Landscape
}

// GetLandscapeOk returns a tuple with the Landscape field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PdfOutputSpec) GetLandscapeOk() (*bool, bool) {
	if o == nil || IsNil(o.Landscape) {
		return nil, false
	}
	return o.Landscape, true
}

// HasLandscape returns a boolean if a field has been set.
func (o *PdfOutputSpec) HasLandscape() bool {
	if o != nil && !IsNil(o.Landscape) {
		return true
	}

	return false
}

// SetLandscape gets a reference to the given bool and assigns it to the Landscape field.
func (o *PdfOutputSpec) SetLandscape(v bool) {
	o.Landscape = &v
}

// GetPrintBackground returns the PrintBackground field value if set, zero value otherwise.
func (o *PdfOutputSpec) GetPrintBackground() bool {
	if o == nil || IsNil(o.PrintBackground) {
		var ret bool
		return ret
	}
	return *o.PrintBackground
}

// GetPrintBackgroundOk returns a tuple with the PrintBackground field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PdfOutputSpec) GetPrintBackgroundOk() (*bool, bool) {
	if o == nil || IsNil(o.PrintBackground) {
		return nil, false
	}
	return o.PrintBackground, true
}

// HasPrintBackground returns a boolean if a field has been set.
func (o *PdfOutputSpec) HasPrintBackground() bool {
	if o != nil && !IsNil(o.PrintBackground) {
		return true
	}

	return false
}

// SetPrintBackground gets a reference to the given bool and assigns it to the PrintBackground field.
func (o *PdfOutputSpec) SetPrintBackground(v bool) {
	o.PrintBackground = &v
}

// GetType returns the Type field value
func (o *PdfOutputSpec) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PdfOutputSpec) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PdfOutputSpec) SetType(v string) {
	o.Type = v
}

func (o PdfOutputSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PdfOutputSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Format.IsSet() {
		toSerialize["format"] = o.Format.Get()
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.Landscape) {
		toSerialize["landscape"] = o.Landscape
	}
	if !IsNil(o.PrintBackground) {
		toSerialize["printBackground"] = o.PrintBackground
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PdfOutputSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPdfOutputSpec := _PdfOutputSpec{}

	err = json.Unmarshal(data, &varPdfOutputSpec)

	if err != nil {
		return err
	}

	*o = PdfOutputSpec(varPdfOutputSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "format")
		delete(additionalProperties, "id")
		delete(additionalProperties, "landscape")
		delete(additionalProperties, "printBackground")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePdfOutputSpec struct {
	value *PdfOutputSpec
	isSet bool
}

func (v NullablePdfOutputSpec) Get() *PdfOutputSpec {
	return v.value
}

func (v *NullablePdfOutputSpec) Set(val *PdfOutputSpec) {
	v.value = val
	v.isSet = true
}

func (v NullablePdfOutputSpec) IsSet() bool {
	return v.isSet
}

func (v *NullablePdfOutputSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePdfOutputSpec(val *PdfOutputSpec) *NullablePdfOutputSpec {
	return &NullablePdfOutputSpec{value: val, isSet: true}
}

func (v NullablePdfOutputSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePdfOutputSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


