/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkUrlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkUrlRequest{}

// BulkUrlRequest struct for BulkUrlRequest
type BulkUrlRequest struct {
	Options NullableBulkUrlOptions `json:"options,omitempty"`
	Url string `json:"url" validate:"regexp=^https?://.*"`
	AdditionalProperties map[string]interface{}
}

type _BulkUrlRequest BulkUrlRequest

// NewBulkUrlRequest instantiates a new BulkUrlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkUrlRequest(url string) *BulkUrlRequest {
	this := BulkUrlRequest{}
	this.Url = url
	return &this
}

// NewBulkUrlRequestWithDefaults instantiates a new BulkUrlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkUrlRequestWithDefaults() *BulkUrlRequest {
	this := BulkUrlRequest{}
	return &this
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkUrlRequest) GetOptions() BulkUrlOptions {
	if o == nil || IsNil(o.Options.Get()) {
		var ret BulkUrlOptions
		return ret
	}
	return *o.Options.Get()
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkUrlRequest) GetOptionsOk() (*BulkUrlOptions, bool) {
	if o == nil {
		return nil, false
	}
	return o.Options.Get(), o.Options.IsSet()
}

// HasOptions returns a boolean if a field has been set.
func (o *BulkUrlRequest) HasOptions() bool {
	if o != nil && o.Options.IsSet() {
		return true
	}

	return false
}

// SetOptions gets a reference to the given NullableBulkUrlOptions and assigns it to the Options field.
func (o *BulkUrlRequest) SetOptions(v BulkUrlOptions) {
	o.Options.Set(&v)
}
// SetOptionsNil sets the value for Options to be an explicit nil
func (o *BulkUrlRequest) SetOptionsNil() {
	o.Options.Set(nil)
}

// UnsetOptions ensures that no value is present for Options, not even an explicit nil
func (o *BulkUrlRequest) UnsetOptions() {
	o.Options.Unset()
}

// GetUrl returns the Url field value
func (o *BulkUrlRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *BulkUrlRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *BulkUrlRequest) SetUrl(v string) {
	o.Url = v
}

func (o BulkUrlRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkUrlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Options.IsSet() {
		toSerialize["options"] = o.Options.Get()
	}
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkUrlRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkUrlRequest := _BulkUrlRequest{}

	err = json.Unmarshal(data, &varBulkUrlRequest)

	if err != nil {
		return err
	}

	*o = BulkUrlRequest(varBulkUrlRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "options")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkUrlRequest struct {
	value *BulkUrlRequest
	isSet bool
}

func (v NullableBulkUrlRequest) Get() *BulkUrlRequest {
	return v.value
}

func (v *NullableBulkUrlRequest) Set(val *BulkUrlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkUrlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkUrlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkUrlRequest(val *BulkUrlRequest) *NullableBulkUrlRequest {
	return &NullableBulkUrlRequest{value: val, isSet: true}
}

func (v NullableBulkUrlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkUrlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


