/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the ScreenshotOutputSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScreenshotOutputSpec{}

// ScreenshotOutputSpec struct for ScreenshotOutputSpec
type ScreenshotOutputSpec struct {
	Format *string `json:"format,omitempty"`
	FullPage *bool `json:"fullPage,omitempty"`
	Id NullableString `json:"id,omitempty"`
	Quality *int32 `json:"quality,omitempty"`
	Selector NullableString `json:"selector,omitempty"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _ScreenshotOutputSpec ScreenshotOutputSpec

// NewScreenshotOutputSpec instantiates a new ScreenshotOutputSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScreenshotOutputSpec(type_ string) *ScreenshotOutputSpec {
	this := ScreenshotOutputSpec{}
	var format string = "png"
	this.Format = &format
	var fullPage bool = false
	this.FullPage = &fullPage
	var quality int32 = 80
	this.Quality = &quality
	this.Type = type_
	return &this
}

// NewScreenshotOutputSpecWithDefaults instantiates a new ScreenshotOutputSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScreenshotOutputSpecWithDefaults() *ScreenshotOutputSpec {
	this := ScreenshotOutputSpec{}
	var format string = "png"
	this.Format = &format
	var fullPage bool = false
	this.FullPage = &fullPage
	var quality int32 = 80
	this.Quality = &quality
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *ScreenshotOutputSpec) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotOutputSpec) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *ScreenshotOutputSpec) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *ScreenshotOutputSpec) SetFormat(v string) {
	o.Format = &v
}

// GetFullPage returns the FullPage field value if set, zero value otherwise.
func (o *ScreenshotOutputSpec) GetFullPage() bool {
	if o == nil || IsNil(o.FullPage) {
		var ret bool
		return ret
	}
	return *o.FullPage
}

// GetFullPageOk returns a tuple with the FullPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotOutputSpec) GetFullPageOk() (*bool, bool) {
	if o == nil || IsNil(o.FullPage) {
		return nil, false
	}
	return o.FullPage, true
}

// HasFullPage returns a boolean if a field has been set.
func (o *ScreenshotOutputSpec) HasFullPage() bool {
	if o != nil && !IsNil(o.FullPage) {
		return true
	}

	return false
}

// SetFullPage gets a reference to the given bool and assigns it to the FullPage field.
func (o *ScreenshotOutputSpec) SetFullPage(v bool) {
	o.FullPage = &v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotOutputSpec) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotOutputSpec) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ScreenshotOutputSpec) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ScreenshotOutputSpec) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *ScreenshotOutputSpec) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ScreenshotOutputSpec) UnsetId() {
	o.Id.Unset()
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *ScreenshotOutputSpec) GetQuality() int32 {
	if o == nil || IsNil(o.Quality) {
		var ret int32
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScreenshotOutputSpec) GetQualityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *ScreenshotOutputSpec) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given int32 and assigns it to the Quality field.
func (o *ScreenshotOutputSpec) SetQuality(v int32) {
	o.Quality = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScreenshotOutputSpec) GetSelector() string {
	if o == nil || IsNil(o.Selector.Get()) {
		var ret string
		return ret
	}
	return *o.Selector.Get()
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScreenshotOutputSpec) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Selector.Get(), o.Selector.IsSet()
}

// HasSelector returns a boolean if a field has been set.
func (o *ScreenshotOutputSpec) HasSelector() bool {
	if o != nil && o.Selector.IsSet() {
		return true
	}

	return false
}

// SetSelector gets a reference to the given NullableString and assigns it to the Selector field.
func (o *ScreenshotOutputSpec) SetSelector(v string) {
	o.Selector.Set(&v)
}
// SetSelectorNil sets the value for Selector to be an explicit nil
func (o *ScreenshotOutputSpec) SetSelectorNil() {
	o.Selector.Set(nil)
}

// UnsetSelector ensures that no value is present for Selector, not even an explicit nil
func (o *ScreenshotOutputSpec) UnsetSelector() {
	o.Selector.Unset()
}

// GetType returns the Type field value
func (o *ScreenshotOutputSpec) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ScreenshotOutputSpec) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ScreenshotOutputSpec) SetType(v string) {
	o.Type = v
}

func (o ScreenshotOutputSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScreenshotOutputSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.FullPage) {
		toSerialize["fullPage"] = o.FullPage
	}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	if o.Selector.IsSet() {
		toSerialize["selector"] = o.Selector.Get()
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScreenshotOutputSpec) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScreenshotOutputSpec := _ScreenshotOutputSpec{}

	err = json.Unmarshal(data, &varScreenshotOutputSpec)

	if err != nil {
		return err
	}

	*o = ScreenshotOutputSpec(varScreenshotOutputSpec)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "format")
		delete(additionalProperties, "fullPage")
		delete(additionalProperties, "id")
		delete(additionalProperties, "quality")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScreenshotOutputSpec struct {
	value *ScreenshotOutputSpec
	isSet bool
}

func (v NullableScreenshotOutputSpec) Get() *ScreenshotOutputSpec {
	return v.value
}

func (v *NullableScreenshotOutputSpec) Set(val *ScreenshotOutputSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableScreenshotOutputSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableScreenshotOutputSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScreenshotOutputSpec(val *ScreenshotOutputSpec) *NullableScreenshotOutputSpec {
	return &NullableScreenshotOutputSpec{value: val, isSet: true}
}

func (v NullableScreenshotOutputSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScreenshotOutputSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


