/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ComposeJobCreatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComposeJobCreatedResponse{}

// ComposeJobCreatedResponse struct for ComposeJobCreatedResponse
type ComposeJobCreatedResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	JobId string `json:"jobId"`
	Status string `json:"status"`
	StatusUrl string `json:"statusUrl"`
	AdditionalProperties map[string]interface{}
}

type _ComposeJobCreatedResponse ComposeJobCreatedResponse

// NewComposeJobCreatedResponse instantiates a new ComposeJobCreatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComposeJobCreatedResponse(createdAt time.Time, jobId string, status string, statusUrl string) *ComposeJobCreatedResponse {
	this := ComposeJobCreatedResponse{}
	this.CreatedAt = createdAt
	this.JobId = jobId
	this.Status = status
	this.StatusUrl = statusUrl
	return &this
}

// NewComposeJobCreatedResponseWithDefaults instantiates a new ComposeJobCreatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComposeJobCreatedResponseWithDefaults() *ComposeJobCreatedResponse {
	this := ComposeJobCreatedResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *ComposeJobCreatedResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ComposeJobCreatedResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ComposeJobCreatedResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetJobId returns the JobId field value
func (o *ComposeJobCreatedResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *ComposeJobCreatedResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *ComposeJobCreatedResponse) SetJobId(v string) {
	o.JobId = v
}

// GetStatus returns the Status field value
func (o *ComposeJobCreatedResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ComposeJobCreatedResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ComposeJobCreatedResponse) SetStatus(v string) {
	o.Status = v
}

// GetStatusUrl returns the StatusUrl field value
func (o *ComposeJobCreatedResponse) GetStatusUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusUrl
}

// GetStatusUrlOk returns a tuple with the StatusUrl field value
// and a boolean to check if the value has been set.
func (o *ComposeJobCreatedResponse) GetStatusUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusUrl, true
}

// SetStatusUrl sets field value
func (o *ComposeJobCreatedResponse) SetStatusUrl(v string) {
	o.StatusUrl = v
}

func (o ComposeJobCreatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComposeJobCreatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["jobId"] = o.JobId
	toSerialize["status"] = o.Status
	toSerialize["statusUrl"] = o.StatusUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ComposeJobCreatedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"jobId",
		"status",
		"statusUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComposeJobCreatedResponse := _ComposeJobCreatedResponse{}

	err = json.Unmarshal(data, &varComposeJobCreatedResponse)

	if err != nil {
		return err
	}

	*o = ComposeJobCreatedResponse(varComposeJobCreatedResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "jobId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "statusUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableComposeJobCreatedResponse struct {
	value *ComposeJobCreatedResponse
	isSet bool
}

func (v NullableComposeJobCreatedResponse) Get() *ComposeJobCreatedResponse {
	return v.value
}

func (v *NullableComposeJobCreatedResponse) Set(val *ComposeJobCreatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableComposeJobCreatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableComposeJobCreatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComposeJobCreatedResponse(val *ComposeJobCreatedResponse) *NullableComposeJobCreatedResponse {
	return &NullableComposeJobCreatedResponse{value: val, isSet: true}
}

func (v NullableComposeJobCreatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComposeJobCreatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


