/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the PressAction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PressAction{}

// PressAction struct for PressAction
type PressAction struct {
	Key string `json:"key"`
	Optional *bool `json:"optional,omitempty"`
	Selector NullableString `json:"selector,omitempty"`
	Timeout NullableInt32 `json:"timeout,omitempty"`
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _PressAction PressAction

// NewPressAction instantiates a new PressAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPressAction(key string, type_ string) *PressAction {
	this := PressAction{}
	this.Key = key
	var optional bool = false
	this.Optional = &optional
	this.Type = type_
	return &this
}

// NewPressActionWithDefaults instantiates a new PressAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPressActionWithDefaults() *PressAction {
	this := PressAction{}
	var optional bool = false
	this.Optional = &optional
	return &this
}

// GetKey returns the Key field value
func (o *PressAction) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *PressAction) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *PressAction) SetKey(v string) {
	o.Key = v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *PressAction) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PressAction) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *PressAction) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *PressAction) SetOptional(v bool) {
	o.Optional = &v
}

// GetSelector returns the Selector field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PressAction) GetSelector() string {
	if o == nil || IsNil(o.Selector.Get()) {
		var ret string
		return ret
	}
	return *o.Selector.Get()
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PressAction) GetSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Selector.Get(), o.Selector.IsSet()
}

// HasSelector returns a boolean if a field has been set.
func (o *PressAction) HasSelector() bool {
	if o != nil && o.Selector.IsSet() {
		return true
	}

	return false
}

// SetSelector gets a reference to the given NullableString and assigns it to the Selector field.
func (o *PressAction) SetSelector(v string) {
	o.Selector.Set(&v)
}
// SetSelectorNil sets the value for Selector to be an explicit nil
func (o *PressAction) SetSelectorNil() {
	o.Selector.Set(nil)
}

// UnsetSelector ensures that no value is present for Selector, not even an explicit nil
func (o *PressAction) UnsetSelector() {
	o.Selector.Unset()
}

// GetTimeout returns the Timeout field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PressAction) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout.Get()) {
		var ret int32
		return ret
	}
	return *o.Timeout.Get()
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PressAction) GetTimeoutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timeout.Get(), o.Timeout.IsSet()
}

// HasTimeout returns a boolean if a field has been set.
func (o *PressAction) HasTimeout() bool {
	if o != nil && o.Timeout.IsSet() {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given NullableInt32 and assigns it to the Timeout field.
func (o *PressAction) SetTimeout(v int32) {
	o.Timeout.Set(&v)
}
// SetTimeoutNil sets the value for Timeout to be an explicit nil
func (o *PressAction) SetTimeoutNil() {
	o.Timeout.Set(nil)
}

// UnsetTimeout ensures that no value is present for Timeout, not even an explicit nil
func (o *PressAction) UnsetTimeout() {
	o.Timeout.Unset()
}

// GetType returns the Type field value
func (o *PressAction) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PressAction) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PressAction) SetType(v string) {
	o.Type = v
}

func (o PressAction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PressAction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	if o.Selector.IsSet() {
		toSerialize["selector"] = o.Selector.Get()
	}
	if o.Timeout.IsSet() {
		toSerialize["timeout"] = o.Timeout.Get()
	}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PressAction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPressAction := _PressAction{}

	err = json.Unmarshal(data, &varPressAction)

	if err != nil {
		return err
	}

	*o = PressAction(varPressAction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "optional")
		delete(additionalProperties, "selector")
		delete(additionalProperties, "timeout")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePressAction struct {
	value *PressAction
	isSet bool
}

func (v NullablePressAction) Get() *PressAction {
	return v.value
}

func (v *NullablePressAction) Set(val *PressAction) {
	v.value = val
	v.isSet = true
}

func (v NullablePressAction) IsSet() bool {
	return v.isSet
}

func (v *NullablePressAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePressAction(val *PressAction) *NullablePressAction {
	return &NullablePressAction{value: val, isSet: true}
}

func (v NullablePressAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePressAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


