/*
Allscreenshots public API

Capture websites, manage jobs, compose images, schedule captures, crawl sites, and read usage.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package allscreenshots

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkJobInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkJobInfo{}

// BulkJobInfo struct for BulkJobInfo
type BulkJobInfo struct {
	ErrorCode NullableString `json:"errorCode,omitempty"`
	ErrorMessage NullableString `json:"errorMessage,omitempty"`
	Id string `json:"id"`
	ResultUrl NullableString `json:"resultUrl,omitempty"`
	Status string `json:"status"`
	Url string `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _BulkJobInfo BulkJobInfo

// NewBulkJobInfo instantiates a new BulkJobInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkJobInfo(id string, status string, url string) *BulkJobInfo {
	this := BulkJobInfo{}
	this.Id = id
	this.Status = status
	this.Url = url
	return &this
}

// NewBulkJobInfoWithDefaults instantiates a new BulkJobInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkJobInfoWithDefaults() *BulkJobInfo {
	this := BulkJobInfo{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkJobInfo) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorCode.Get()
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkJobInfo) GetErrorCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorCode.Get(), o.ErrorCode.IsSet()
}

// HasErrorCode returns a boolean if a field has been set.
func (o *BulkJobInfo) HasErrorCode() bool {
	if o != nil && o.ErrorCode.IsSet() {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given NullableString and assigns it to the ErrorCode field.
func (o *BulkJobInfo) SetErrorCode(v string) {
	o.ErrorCode.Set(&v)
}
// SetErrorCodeNil sets the value for ErrorCode to be an explicit nil
func (o *BulkJobInfo) SetErrorCodeNil() {
	o.ErrorCode.Set(nil)
}

// UnsetErrorCode ensures that no value is present for ErrorCode, not even an explicit nil
func (o *BulkJobInfo) UnsetErrorCode() {
	o.ErrorCode.Unset()
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkJobInfo) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage.Get()) {
		var ret string
		return ret
	}
	return *o.ErrorMessage.Get()
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkJobInfo) GetErrorMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ErrorMessage.Get(), o.ErrorMessage.IsSet()
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *BulkJobInfo) HasErrorMessage() bool {
	if o != nil && o.ErrorMessage.IsSet() {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given NullableString and assigns it to the ErrorMessage field.
func (o *BulkJobInfo) SetErrorMessage(v string) {
	o.ErrorMessage.Set(&v)
}
// SetErrorMessageNil sets the value for ErrorMessage to be an explicit nil
func (o *BulkJobInfo) SetErrorMessageNil() {
	o.ErrorMessage.Set(nil)
}

// UnsetErrorMessage ensures that no value is present for ErrorMessage, not even an explicit nil
func (o *BulkJobInfo) UnsetErrorMessage() {
	o.ErrorMessage.Unset()
}

// GetId returns the Id field value
func (o *BulkJobInfo) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkJobInfo) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkJobInfo) SetId(v string) {
	o.Id = v
}

// GetResultUrl returns the ResultUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkJobInfo) GetResultUrl() string {
	if o == nil || IsNil(o.ResultUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ResultUrl.Get()
}

// GetResultUrlOk returns a tuple with the ResultUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkJobInfo) GetResultUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResultUrl.Get(), o.ResultUrl.IsSet()
}

// HasResultUrl returns a boolean if a field has been set.
func (o *BulkJobInfo) HasResultUrl() bool {
	if o != nil && o.ResultUrl.IsSet() {
		return true
	}

	return false
}

// SetResultUrl gets a reference to the given NullableString and assigns it to the ResultUrl field.
func (o *BulkJobInfo) SetResultUrl(v string) {
	o.ResultUrl.Set(&v)
}
// SetResultUrlNil sets the value for ResultUrl to be an explicit nil
func (o *BulkJobInfo) SetResultUrlNil() {
	o.ResultUrl.Set(nil)
}

// UnsetResultUrl ensures that no value is present for ResultUrl, not even an explicit nil
func (o *BulkJobInfo) UnsetResultUrl() {
	o.ResultUrl.Unset()
}

// GetStatus returns the Status field value
func (o *BulkJobInfo) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BulkJobInfo) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BulkJobInfo) SetStatus(v string) {
	o.Status = v
}

// GetUrl returns the Url field value
func (o *BulkJobInfo) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *BulkJobInfo) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *BulkJobInfo) SetUrl(v string) {
	o.Url = v
}

func (o BulkJobInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkJobInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorCode.IsSet() {
		toSerialize["errorCode"] = o.ErrorCode.Get()
	}
	if o.ErrorMessage.IsSet() {
		toSerialize["errorMessage"] = o.ErrorMessage.Get()
	}
	toSerialize["id"] = o.Id
	if o.ResultUrl.IsSet() {
		toSerialize["resultUrl"] = o.ResultUrl.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkJobInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkJobInfo := _BulkJobInfo{}

	err = json.Unmarshal(data, &varBulkJobInfo)

	if err != nil {
		return err
	}

	*o = BulkJobInfo(varBulkJobInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "errorCode")
		delete(additionalProperties, "errorMessage")
		delete(additionalProperties, "id")
		delete(additionalProperties, "resultUrl")
		delete(additionalProperties, "status")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkJobInfo struct {
	value *BulkJobInfo
	isSet bool
}

func (v NullableBulkJobInfo) Get() *BulkJobInfo {
	return v.value
}

func (v *NullableBulkJobInfo) Set(val *BulkJobInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkJobInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkJobInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkJobInfo(val *BulkJobInfo) *NullableBulkJobInfo {
	return &NullableBulkJobInfo{value: val, isSet: true}
}

func (v NullableBulkJobInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkJobInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


